### ISSUE TITLE
Invalid Java home directory 

### ISSUE THREAD

**Issue by okornoe** [TEAMMATES/teammates#6253] opened 2016-12-22 12:42 UTC
![teammatescapture](https://cloud.githubusercontent.com/assets/12277906/21425882/8e9f9962-c843-11e6-8414-e9ffc4b46080.PNG)
Am trying to setup my environment for the project, but when I run the command './gradlew appengineDownloadSdk' I have this error 

'ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-7-oracle/bin/java

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
' In my teammates-master directory.

**Comment by damithc** [comment] 2016-12-22 14:08
@okornoe did you follow the instructions in the error message? Looks like you don't even have java 7 on your computer (TEAMMATES requires Java 7)

**Comment by okornoe** [comment] 2016-12-22 14:14
@damithc I do have java7

**Comment by damithc** [comment] 2016-12-22 14:22
I'm not a Linux guy, but it seems the path given as item 2 in your list does not match the one given in the error message. i.e. the JAVA_HOME does not match your Java 7 location. Furthermore, I think you need Java 7 JDK. JRE is not enough.

**Comment by okornoe** [comment] 2016-12-22 14:29
@damithc Okay I will do that

**Comment by AnaghHegde** [comment] 2016-12-23 11:35
@okornoe you can do like this

Type in terminal,

echo $JAVA_HOME

Display JAVA_HOME variable path.

IF NOTHING APPEARS THEN SET IT WITH THIS

export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64

This will differ according to your JDK type & version

For displaying follow first command.

**Comment by AnaghHegde** [comment] 2016-12-23 11:38
@okornoe i also had the similar problem at first i followed the same steps which i posted above. I think it should work and if you still face any errors do post it.

**Comment by okornoe** [comment] 2016-12-23 19:46
@damithc @AnaghHegde I have decided to change from Linux environment to windows, I have being able to import the project but I have some errors. 
![build1](https://cloud.githubusercontent.com/assets/12277906/21461316/7b584966-c948-11e6-9ac9-a61f2e22839f.PNG)
![build2](https://cloud.githubusercontent.com/assets/12277906/21461317/7b5b5ca0-c948-11e6-9f07-c38d207a96f1.PNG)
![build3](https://cloud.githubusercontent.com/assets/12277906/21461315/7b55d06e-c948-11e6-9542-da6595575e4a.PNG)

**Comment by damithc** [comment] 2016-12-24 12:02
@okornoe Can you post screenshots after each step to show that each step was done correctly? Otherwise we can't pinpoint at which step things went wrong.

**Comment by chowyb** [comment] 2016-12-31 17:01
Hi, I have set up the TEAMMATES repo on a new system a few weeks ago, and I remember this was caused by Eclipse's validation, which should be fixed using [this answer](http://stackoverflow.com/a/2268714).

**Comment by okornoe** [comment] 2017-01-01 13:34
@damithc I have been able to setup the project am left with setting up the static analysis tools.
Thank you for your help so far.
@AnaghHegde

**Comment by ovshake** [comment] 2017-01-01 17:06
@damithc @AnaghHegde I am almost completed in setting up the dev environment but this XML problem came up.  How should I go about it? 
![xml](https://cloud.githubusercontent.com/assets/22028532/21582150/b92a1914-d072-11e6-99b6-a71dcddf1e7b.png)

**Comment by wkurniawan07** [comment] 2017-01-02 05:32
@ovshake we don't validate our XML files so you can skip those.

**Closed** 2017-01-11 03:13 UTC
Labels: a-DevHelp, c.Message
