### ISSUE TITLE
Instructor cannot change student email if the section has 100 students

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10851] opened 2020-12-04 02:53 UTC
If a section has 100 students already, TEAMMATES doesn't allow the instructor to change the email of a student in that section.

![image](https://user-images.githubusercontent.com/1673303/101115681-b9db2e00-361e-11eb-9315-71ec0061b8a1.png)

**Comment by wkurniawan07** [comment] 2020-12-05 11:38
I don't believe that's the problem. That error is thrown before any DB read is done, i.e. it has to be the students list.

**Comment by wkurniawan07** [comment] 2020-12-05 11:55
Ignore my previous message, but this still calls for more info.

Student email is the primary key of a student (along with course ID), so an operation to "change email" doesn't really make sense. Just consider this question: how to know which old email to replace? Relying on any other field, albeit reasonable ones like name, is a dangerous assumption.

**Comment by wkurniawan07** [comment] 2020-12-05 12:18
Alright, so the verdict is the described original issue stands.

But this should not be `p.High` because the instructor can delete the old student before enrolling a new one. Not convenient, but not a blocker.

**Comment by damithc** [comment] 2020-12-05 12:24
> But this should not be `p.High` because the instructor can delete the old student before enrolling a new one. Not convenient, but not a blocker.

In this specific case, the student has submitted responses to previous submissions but lost access to the email account and is asking the instructor to change the email.
The instructor (that's the user who reported this error) thinks the old submissions of the students will be preserved through this edit-email operation. I'm not sure if that's the case, but if it is, delete-and-add is not a good workaround.

**Comment by rrtheonlyone** [comment] 2020-12-06 04:35
I did some investigation on this issue. 

We use the `EnrollStudentsAction` even when updating a student and do the following steps:
1. Get and validate the API request paremeters: get a list of students who need to either be updated/added
2. Fetch ALL students in course
3. Iterate through list in (2) and check if the students in (1) have an existing email address inside (2)
4. If email address is inside, call update
5. Else, treat as a new student and add in

In the above case, since there is no email address inside the existing list, we treat the student as new and attempt add him in. This then throws the 100 limit error.

I feel there are some points for discussion here:

1. Why is an email address used as a primary key? This is generally not a [good idea](https://stackoverflow.com/questions/3804108/use-email-address-as-primary-key) as we already see from the above. Email Address's thus cannot be updated and the frontend should not even allow it.

2. What is the need to fetch all students and iterate in the API action? Why not separate the creation of a student from the updating of a student through different REST endpoints?

3. Error messages needs some improvement. The error message above is misleading to an end-user.

**Comment by wkurniawan07** [comment] 2020-12-06 05:15
> We use the `EnrollStudentsAction` even when updating a student and do the following steps

This is wrong.

**Comment by rrtheonlyone** [comment] 2020-12-06 15:47
Ah yes - sry should have been `UpdateStudentAction`!

I did a more thorough check now and found the error happens here: https://github.com/TEAMMATES/teammates/blob/2c7d0715b488d319a9ee95e13a05f082d84236bb/src/main/java/teammates/logic/core/StudentsLogic.java#L256-L274

The issue is that since the email has changed, we add it to our `mergedList` and think we have too many inside the same section. This is a regression from fixing #9747

I can fix this. Updating a student's email within a section should not cause it to throw an `EnrollException`

> The instructor (that's the user who reported this error) thinks the old submissions of the students will be preserved through this edit-email operation

This is correct as when we reset the email we do a cascading update.

**Closed** 2021-05-22 14:06 UTC
Labels: c.Bug
