### ISSUE TITLE
Server error when tracking view results

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11415] opened 2021-09-12 03:32 UTC
Feature accessed via `/instructor/track-result-view`

What I see when I tried it on an actual session that has been published

![image](https://user-images.githubusercontent.com/1673303/132970997-6d001ab3-4dba-4fec-ac45-0241a80171c2.png)

Error in the log

![image](https://user-images.githubusercontent.com/1673303/132971068-b5363418-8f40-4006-971c-90d415383c5e.png)

Let me know if you need more info

**Comment by wkurniawan07** [comment] 2021-09-12 05:42
Not reproducible and the log shown up there has nothing to do with this

**Comment by damithc** [comment] 2021-09-12 06:06
Happened for my course as well as for another course when I masqueraded as another user.  That's when I reported the problem.

I tried with a different course just now and it worked. However, CS2103 is still showing a server error as before, AND the stale results from the previous search shows up as well (I guess that's a different bug?)

![image](https://user-images.githubusercontent.com/1673303/132973913-d7130f82-d415-4b10-ad3b-552938aea6dc.png)

**Comment by damithc** [comment] 2021-09-12 06:13
@wkurniawan07 I gave you instructor access to the course in concern. See if you can repro the error on your side.

**Comment by halfwhole** [comment] 2022-04-09 14:32
Highly suspect that it is related to or a duplicate of #11497 as they're hitting the same backend endpoint for getting feedback session logs

**Comment by wkurniawan07** [comment] 2022-04-12 04:13
Duplicate of #11497

**Closed by wkurniawan07** 2022-04-12 04:13 UTC
Labels: s.ToInvestigate
