### ISSUE TITLE
Mark all tooltipped text with grey dotted underlines

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5696] opened 2016-06-22 01:22 UTC
Here is an example:
![image](https://cloud.githubusercontent.com/assets/1673303/16251696/ce9deb5a-385a-11e6-99bb-5ef73abdc982.png)

**Comment by damithc** [comment] 2016-06-22 01:24
@YongJieYongJie @wkurniawan07 is there a way to do this across the code base?

**Comment by YongJieYongJie** [comment] 2016-06-22 04:55
We can dynamically add the style by selecting all elements with tooltips enabled (using a CSS selector like `[data-toggle="tooltip"]`), and adding the style `text-decoration: underline dotted gray`.

Alternatively, we can search through the code base for occurrences of `data-toggle="tooltip"` and add a class for styling

The first way ensures all tooltips now and in the future will be covered (but may be more expensive).

**Comment by damithc** [comment] 2016-06-22 07:13
How is it that some already have the dotted line?

**Comment by YongJieYongJie** [comment] 2016-06-23 01:21
The results page uses the `<abbr>` tag, although there are currently some conflicting rules (duplicated underline and tooltip):

![underline dotted](https://cloud.githubusercontent.com/assets/14101781/16288810/5f8e5754-3922-11e6-8b23-e139a4c21c8f.png)

The `<abbr>` tag is intended for abbreviations and I think we should not use it out of semantic context unless necessary. We can use a new class for underline styling.

**Comment by damithc** [comment] 2016-06-23 01:30
Yes, let's not use the `<abbr>`

**Comment by rclakmal** [comment] 2016-06-29 21:09
@damithc @YongJieYongJie  Looks like #5614 a duplicate of this issue ?

**Comment by YongJieYongJie** [comment] 2016-06-30 00:27
@rclakmal Seems like #5614 is a subset of this issue. In any case, I'm actually waiting for @tarun14110 to add the underline CSS rule in #5627

**Comment by rclakmal** [comment] 2016-06-30 00:29
I see...then should I close the PR I made?....I added a fix for this. Didn't know it was work in progress.

**Comment by YongJieYongJie** [comment] 2016-06-30 00:32
@rclakmal Hold on a minute, let me take a look at the PR

**Closed** 2016-07-16 16:55 UTC
Labels: a-UIX, p.Medium
