### ISSUE TITLE
Instuctor : Feedback Questions : MCQ/MSQ questions : Disable drop down menu by default

### ISSUE THREAD

**Issue by sukanta-27** [TEAMMATES/teammates#8576] opened 2018-03-02 13:56 UTC
**Environment**
`master` branch

**Steps to reproduce:**
- Login as `Instructor`
- Create a new session or edit an existing one
- Click on `Add new questions`
- Select MCQ/MSQ question
- The checkbox for `Or, generate options from the list of all` is not be selected by default but the drop down menu will be enabled, where as the other options `Max number of *` and `Min number of *` will be disabled as usual (In case of MSQ question): 
![screenshot 395](https://user-images.githubusercontent.com/10681755/36901675-e55620ea-1e1f-11e8-8db2-e693ae7d63e9.png)
- Now select the checkbox and then deselect it 
- The drop down menu is now disabled (as it should be in the first place) : 
![screenshot 396](https://user-images.githubusercontent.com/10681755/36901865-7ffabf3e-1e20-11e8-81bf-b5087db26f85.png)

**Expected behaviour:** The drop down menu should be disabled by default and only get enabled when that option is selected.

**Actual behaviour:** The menu is enabled immediately after adding the questions, and gets disabled after we select-deselect the checkbox. or when we `Edit` the question after saving it.

**Comment by tshradheya** [comment] 2018-03-02 17:17
I could not reproduce this error. Everything works as expected for me

**Comment by sukanta-27** [comment] 2018-03-02 17:28
@tshradheya Checked both MCQ/MSQ? Added a new question or did you edit a existing one?

**Comment by tshradheya** [comment] 2018-03-02 17:44
Sorry my bad. Could reproduce this error.
I think I forgot to run `npm run build` and I was on my old branch :P

**Comment by OlhaHn** [comment] 2018-03-02 23:55
I would like to take it

**Comment by tshradheya** [comment] 2018-03-03 08:59
Need to investigate why doesn't it get disabled when this method gets executed on making a new question

https://github.com/TEAMMATES/teammates/blob/2ed552ed0950836a726fc0a8f16ad71ef5ae174a/src/main/webapp/dev/js/common/questionMcq.js#L56-L71

Line 67 should be disabling it.

**Comment by sukanta-27** [comment] 2018-03-03 09:30
> Line 67 should be disabling it

Was looking into it yesterday. The same question came to my mind. Further investigation is needed indeed.

**Comment by bqnguyen94** [comment] 2018-03-03 18:44
The problem is here:
https://github.com/TEAMMATES/teammates/blob/2ed552ed0950836a726fc0a8f16ad71ef5ae174a/src/main/webapp/dev/js/main/instructorFeedbackEdit.js#L540-L541
If you look closely, you will see the closing brackets on both lines are placed wrongly, therefore an `undefined` `questionNum` is passed to the function.

**Comment by sukanta-27** [comment] 2018-03-03 19:12
@bqnguyen94 Checked. The problem was definitely on those lines. Great finding that. :+1: 
If you want you can submit a PR for it, if @tshradheya is not working on it.

**Comment by bqnguyen94** [comment] 2018-03-03 19:26
Noted 👍 How about @OlhaHn ?

**Comment by OlhaHn** [comment] 2018-03-03 19:28
@bqnguyen94 you can create a PR, I have not started working on it yet

**Comment by sukanta-27** [comment] 2018-03-03 19:30
@bqnguyen94 @OlhaHn Sorry missed https://github.com/TEAMMATES/teammates/issues/8576#issuecomment-370091522 completely!!! :man_facepalming:

**Comment by tshradheya** [comment] 2018-03-03 21:34
I will just submit a quick fix right now. ( That bracket was actually my fault in one of my latest PR) :(

**Comment by tshradheya** [comment] 2018-03-04 02:58
@bqnguyen94 @sukanta-27 I made the bracket change and the `questionNum` is no longer `undefined`.

However, it has caused a regression. Which is, if I add a question, click on checkbox to genereate options from students and then cancel the question. Now on adding the same question again, it shows the `mcqChoiceTable` and also the `checkbox` as checked.

I tried to investigate why the `toggleMcqGeneratedOptions(checkbox, questionNum)` is  unable to disable the `choiceTable` when the checkbox is checked.

Surprisingly this is what I found.

If I modified code to the following for `instructorFeedbackEdit.js`

``` javascript
    if ($(`#generateMcqOptionsCheckbox-${NEW_QUESTION}`).prop('checked')) {
        alert("checked outside");
    } else {
        alert("unchecked outside");
    }

    toggleMcqGeneratedOptions($(`#generateMcqOptionsCheckbox-${NEW_QUESTION}`), NEW_QUESTION);
    toggleMsqGeneratedOptions($(`#generateMsqOptionsCheckbox-${NEW_QUESTION}`), NEW_QUESTION);
```

and inside the `toggleMcqGeneratedOptions()` function I wrote the following
``` javascript
function toggleMcqGeneratedOptions(checkbox, questionNum) {
    alert(questionNum);
    if (checkbox.checked) {
        alert("checked inside function");
        $(`#mcqChoiceTable-${questionNum}`).find('input[type=text]').prop('disabled', true);
        $(`#mcqChoiceTable-${questionNum}`).hide();
        $(`#mcqGenerateForSelect-${questionNum}`).prop('disabled', false);
        $(`#mcqOtherOptionFlag-${questionNum}`).closest('.checkbox').hide();
        $(`#generatedOptions-${questionNum}`).attr('value',
                $(`#mcqGenerateForSelect-${questionNum}`).prop('value'));
    } else {
        alert("unchecked inside function");
        $(`#mcqChoiceTable-${questionNum}`).find('input[type=text]').prop('disabled', false);
        $(`#mcqChoiceTable-${questionNum}`).show();
        $(`#mcqGenerateForSelect-${questionNum}`).prop('disabled', true);
        $(`#mcqOtherOptionFlag-${questionNum}`).closest('.checkbox').show();
        $(`#generatedOptions-${questionNum}`).attr('value', 'NONE');
    }
}
```

Then on the second time of adding the question ( supposing I checked the box on the first time and canceled the question)
I will get alert of **checked outside** and **unchecked inside function** when the checkbox is actually checked in the webpage.

Any of you have any idea why this would happen?

**Comment by bqnguyen94** [comment] 2018-03-04 07:00
> P.S. I have fixed the problem by using $(checkbox).prop('checked') inside the toggle...() functions

Lol I guess since `checkbox` is a jQuery object `.checked` wouldn't work on it. You can use `$(checkbox)[0]` to get the DOM element.

**Comment by tshradheya** [comment] 2018-03-04 07:44
`.checked` works fine when the checkbox is toggled after adding the question. Its only when the question is being added that it returns undefined.
This works as expected on jquery objects as well : `$(checkbox).prop('checked')`

**Comment by bqnguyen94** [comment] 2018-03-04 08:41
Here
https://github.com/TEAMMATES/teammates/blob/2ed552ed0950836a726fc0a8f16ad71ef5ae174a/src/main/resources/feedbackQuestionMcqEditFormTemplate.html#L35-L40
I guess the checkbox toggling works afterward is because `this` here is the DOM element.

**Closed** 2018-03-22 06:53 UTC
Labels: a-UIX, d.Contributors, e.4, f-Questions, p.Low
