### ISSUE TITLE
Show loading message below response loading spinner

### ISSUE THREAD

**Issue by moziliar** [TEAMMATES/teammates#10986] opened 2021-02-27 07:34 UTC
From PR #10960 

**Description of feature/enhancement**

If a course has many students (or in general many responses per question), add extra loading text below the spinner to inform the user that the students are being loaded (after perhaps 5s).

![image](https://user-images.githubusercontent.com/19870898/109378773-25782300-7910-11eb-82af-dda66fc57782.png)

**Justification**

From @damithc 
> Provided the load operation will not time out, perhaps simply show a message below the spinner cautioning the user that this particular question will take a long time to load?

This would give user more assurance that there is progress in the loading.

**Existing similar features and their shortcomings**

Experimented with using `forkJoin` in the frontend to fetch questions in parallel in #10960: the parallel calls create too much instantaneous load at the backend and causes new instances to be spun up. The cost here is not justified.

**Comment by anshuman-dev** [comment] 2021-03-17 04:14
Hi. Is this issue resolved? Or anyone working still on it?

**Comment by t-cheepeng** [comment] 2021-03-17 09:50
@anshuman-dev Priority will be given to the previous commenter as they have a PR up. You can try to find another `good first issue` to work on

**Comment by P-Fabian** [comment] 2021-11-12 00:11
Is this issue resolved?

**Comment by shivamsharma01** [comment] 2022-01-16 16:11
Is the issue resolved? I would like to take this up.

**Comment by ypinhsuan** [comment] 2022-01-18 02:40
@shivamsharma01 The issue is still open, you can work on it

**Comment by hhdqirui** [comment] 2022-01-19 16:25
@shivamsharma01 Hi, for the first error it may be because your folder `Open Source` contains a space in the folder name? Maybe can try changing the folder name to `OpenSource` or something that do not contain a space.

**Comment by arnavk1872** [comment] 2022-03-01 12:46
Is this issue still open? I would like to work on it.

**Comment by shivamsharma01** [comment] 2022-03-01 13:24
Yes, probably. I was able to setup the workspace with the help of @hhdqirui 's suggestions but now I am not able to login to the application. Don't know how to create a user.

**Comment by rom-me** [comment] 2022-03-04 12:52
Can I also attempt working on this issue if it's still not resolved?

**Comment by t-cheepeng** [comment] 2022-03-05 04:15
@rom-me Hi, please look for another issue to work on as there are previous users who wish to tackle this

**Comment by t-cheepeng** [comment] 2022-03-05 04:16
@shivamsharma01 you can refer to https://github.com/TEAMMATES/teammates/blob/master/docs/development.md to see how to create users

**Comment by shivamsharma01** [comment] 2022-03-06 00:24
In my understanding, there is a switch between the loading-spinner component (via loading-spinner directive) and the templateref using ngIf directive. There is no direct way to show the message while the loader is being displayed. I have added the logic to display 'Loading Records...' after 5 seconds but this is now not limited to records being loaded in the feedback page but every time the loader component is visible for more than 5 seconds on any screen. Kindly let me know if instead this should be limited to only a specific case and any suggestions to handle it.

![image](https://user-images.githubusercontent.com/21052557/156904100-a3f6844a-932c-4b91-a977-2ed5204c0975.png)

**Comment by hlee18lee46** [comment] 2022-10-03 03:43
Can I take this issue?

**Comment by NicolasCwy** [comment] 2022-10-04 04:45
@hlee18lee46 Go ahead!

**Comment by PrakritiShetty** [comment] 2022-10-07 10:31
Can I work on this issue, or is it already assigned to someone?

**Comment by fsgmhoward** [comment] 2022-10-07 11:12
@PrakritiShetty Someone else has taken it. Please find other issues to work on instead!

**Comment by sumit970** [comment] 2023-02-15 20:14
Assign this issue to me

**Comment by samuelfangjw** [comment] 2023-02-16 01:52
> Assign this issue to me

Our Development Workflow can be found [here](https://teammates.github.io/teammates/process.html).

**Comment by asn001013** [comment] 2023-03-12 07:32
@sumit970 Hey! Are you still working on this? If not, I'd like to work on it

**Comment by MMilou24** [comment] 2023-03-28 13:58
Hi, I would like to take this issue up

**Comment by domlimm** [comment] 2023-03-28 14:22
@sumit970 Hello, are you still working on this issue? If not, we can have others to take this up.

@MMilou24 Hey there! Let's give @sumit970 some time to respond. If not, you may look at other issues [here](https://github.com/TEAMMATES/teammates/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) for first time contributors.

**Comment by domlimm** [comment] 2023-03-29 01:53
@sumit970 Thanks for getting back! Much appreciated.

@MMilou24 Feel free to work on this issue.

**Comment by nielsly** [comment] 2023-03-31 16:53
@MMilou24 and I are working on this together for a university course, therefore I have created the pull request.

**Closed** 2023-04-10 13:52 UTC
Labels: a-UIX, good first issue, c.Feature
