### ISSUE TITLE
Instructor session results page: better label for questions without specific recipients

### ISSUE THREAD

**Issue by niqiukun** [TEAMMATES/teammates#10595] opened 2020-08-13 16:25 UTC
Currently recipients of questions that do not require specifc recipients are identified as "-". This may be a bit confusing especially when grouped by recipients. Can give it a better label (e.g. no specific recipients)
![image](https://user-images.githubusercontent.com/5328196/90160660-aaf91300-ddc4-11ea-8707-dc6c6a1b7b32.png)

**Comment by niqiukun** [comment] 2020-08-16 08:46
Actually, anyone knows what is the difference between "None" and "No specific section" for the section selection?
![image](https://user-images.githubusercontent.com/5328196/90330526-e15eaa00-dfdf-11ea-93fc-6bf295450043.png)

**Comment by damithc** [comment] 2020-08-16 08:50
> Actually, anyone knows what is the difference between "None" and "No specific section" for the section selection?

I suspect `None` is the default section used internally to indicate someone is not in a section. At least that's how it used to be sometime back. Not a good practice to use a regular word `None` for a special purpose.

**Comment by madanalogy** [comment] 2020-08-17 07:08
> Actually, anyone knows what is the difference between "None" and "No specific section" for the section selection?

They're supposed to mean the same thing, `None` is the default section name given if an instructor leaves it blank when enrolling students. I think your screenshot might have been something that was missed out in #10209

**Comment by EmberCS15** [comment] 2020-10-02 18:35
Is this issue open, if so I would like to work on it.

**Comment by madanalogy** [comment] 2020-10-03 03:21
> Is this issue open, if so I would like to work on it.

Sure, please read our contributing guide and development guide, and send in a PR to fix this when you're ready.

**Comment by EmberCS15** [comment] 2020-10-03 06:04
I wanted help regarding the following -

* What is the exact text to be displayed for the `To` section in case no one is assigned there
    * Is it `None`
    * Is it `No Specific Recipients`
    * Or something else
* Is there any change required for the dropdown shown in the screenshot (correspondence #2) or is it a question.

**Comment by EmberCS15** [comment] 2020-10-03 09:11
I am having a bit of a problem navigating the website, when I login using the Admin mode on dev server and try masquerade mode to view instructor and student pages it shows an error message like the one in the screenshot

<img width="1436" alt="Error_Screen" src="https://user-images.githubusercontent.com/24290847/94987744-38b3dc00-0586-11eb-9e07-1dad64fa1e86.png">

Any way to by pass this ? I am kind of new to this repo, would really appreciate some help

**Comment by madanalogy** [comment] 2020-10-04 09:42
> What is the exact text to be displayed for the `To` section in case no one is assigned there

It should be "No specific recipients"

> Is there any change required for the dropdown shown in the screenshot (correspondence 2) or is it a question.

It was a question, changing that is not required to be in the scope of a PR tackling this issue

> Any way to by pass this ? I am kind of new to this repo, would really appreciate some help

You will first need to have the instructor you added join the course (with the join link you generated as an administrator)

**Comment by EmberCS15** [comment] 2020-10-04 10:05
I followed the steps -

* Added Instructor, join link is generated
* Logged out of the admin console
* Logged in as the instructor
* When I then paste the join link in the url bar, I see Unable to connect, Is there some other server that needs to be running ?
    * I have the dev server running serving both frontend and backend files

**Comment by EmberCS15** [comment] 2020-10-04 10:06
Actually just changing the port to 8080 did the trick. Thanks

**Comment by EmberCS15** [comment] 2020-10-04 10:13
Is there any discord channel for discussion general questions ? Or are all correspondences held over the issue ?

**Comment by EmberCS15** [comment] 2020-10-04 10:17
Hi @niqiukun, what are the exact steps to reproduce the bug ? It would be helpful to know this information.

**Comment by EmberCS15** [comment] 2020-10-04 10:25
Np, I could reproduce the bug with the following steps - 

* On the instructor tab go to `Sample Course 101` collapsible dropdown
* Go to the row with `Session with different question types` -> Select `Results` -> `View Results`
* For `View` -> Select `Group by > Receipient > Giver > Question`
* For `Section` -> Select `All`
* Under the `No Specific section` the bug can be seen

**Comment by madanalogy** [comment] 2020-10-04 10:33
> Is there any discord/slack channel for discussion general questions ? Or are all correspondences held over the issue ?

All correspondences are communicated via the issue tracker. I see you've managed to reproduce the issue, let us know if you need any help resolving it yea

**Comment by EmberCS15** [comment] 2020-10-04 12:20
Couple of Observations - 
* The Information from the server for the user is coming as -, - because of which it is being rendered as such.
* There is already a check on empty user here so the backend is returning "-" as team name and user name. [Code Line](https://github.com/TEAMMATES/teammates/blob/master/src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.html#L41)

Based on this I have a question -
* Is this the expected behaviour of the data, `RGQ, No Specific Section` means the server returns the user, team as `-, -` ?
* Would it be valid to have the following check
    * if `!isGrq && !(sectionInfo.key === 'None')` then render `No Specific Recipient/Team`

Possible Places to change - 
* Change the To in grouped-response [Link](https://github.com/TEAMMATES/teammates/blob/master/src/web/app/components/question-responses/grouped-responses/grouped-responses.component.html#L5-L19)
* Change in grq-rgq module for rendering To team - [Link](https://github.com/TEAMMATES/teammates/blob/master/src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.html#L5)
* Change in rendering the To User, Team in collapsible - [Link](https://github.com/TEAMMATES/teammates/blob/master/src/web/app/components/question-responses/grq-rgq-view-responses/grq-rgq-view-responses.component.html#L36-L43)

**Comment by madanalogy** [comment] 2020-10-04 13:16
> The Information from the server for the user is coming as -

Your observation is correct

> Is this the expected behaviour of the data

Yes, there are question types that are not directed at any particular person / recipient, and it is currently represented as `-` via the server response

> Would it be valid to have the following check

`sectionInfo.key` seems to imply that you're trying to check for a user's section. What you want to look at instead is the `userInfo` which would be populated with the intended name of the recipient / giver depending on which question view component is attempting to access the information.

Currently, the frontend system displays whatever value that was received from the server. So there are two approaches here, either you change the displayed content (i.e. `if userInfo == '-'`) or change what is returned from the server. Since this is a first timer issue we are only expecting the former.

Another place you could look at is the [`per-question-view-responses.component`](https://github.com/TEAMMATES/teammates/blob/master/src/web/app/components/question-responses/per-question-view-responses/per-question-view-responses.component.html).

**Comment by EmberCS15** [comment] 2020-10-04 13:43
Thanks, @madanalogy  for the clarification

I will go with the proposed solution of adding check on `if userInfo == '-'`

##### For the student name
Since this is used in a lot of places why not add the check to the `student-name-with-photo` html ? This will ensure that for userInfo marked as '-' is given to the  `student-name-with-photo` it will render `No Specific User`

##### For the team marker
Since there is no component for the team marker one, I will have to change that in all places

Let me know which will be more suitable for the student one, changing at all places or the `student-name-with-photo`

**Comment by madanalogy** [comment] 2020-10-04 14:33
> Since this is used in a lot of places why not add the check to the student-name-with-photo html

This sounds like a good suggestion. Give it a go and submit a PR. Include screenshots showing your manual verification of the display changes :)

**Closed** 2020-10-07 05:20 UTC
Labels: Hacktoberfest, good first issue, p.Low
