### ISSUE TITLE
invalid values in "Recommended length for the response" field cause server error

### ISSUE THREAD

**Issue by Skippari** [TEAMMATES/teammates#9215] opened 2018-10-25 12:58 UTC
Editing the Essay Questions it was possible to add negative numbers to the field "Recommended length for the response". This should allow only positive numbers to some limit.

It is also possible to add number like "1E-16" which cause error in the server. This error reproduced every time with such value.
![image](https://user-images.githubusercontent.com/43610898/47501524-6e1a0000-d86e-11e8-990d-45e64fa07bb6.png)

**Comment by xpdavid** [comment] 2018-10-25 13:02
We should restrict that the number should only be integer in frontend.

**Comment by damithc** [comment] 2018-10-25 14:07
Thanks for the bug report @Skippari 

> We should restrict that the number should only be integer in frontend.

Yes, but low priority. This is a case of the user shooting own foot by choice :-) Maybe no need to fix at all?

**Comment by kurzelakamil** [comment] 2018-10-26 12:03
Hi, I'd like to take this one

**Comment by xpdavid** [comment] 2018-10-26 14:08
@kurzelakamil Go ahead.

I think it's OK to fix this. Be sure to take a look at the HTML5 front-end verification attribute https://www.w3.org/wiki/HTML/Elements/input/number.

**Comment by kurzelakamil** [comment] 2018-10-26 14:45
I can't push changes from my local repo to 'teammatesv7' as I can see below errors - 
remote: Permission to TEAMMATES/teammates.git denied to kurzelakamil.
fatal: unable to access 'https://github.com/TEAMMATES/teammates.git/': The requested URL returned error: 403

**Comment by kurzelakamil** [comment] 2018-10-27 07:19
Guys, I think I don't have permissions to push whatever to 'teammatesv7' branch. I get such message: remote: Permission to TEAMMATES/teammates.git denied to kurzelakamil.
fatal: unable to access 'https://github.com/TEAMMATES/teammates.git/': The requested URL returned error: 403

**Comment by xpdavid** [comment] 2018-10-27 07:56
@kurzelakamil I'd appreciate if you take a look at our development process https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#overview

**Comment by borregore** [comment] 2018-11-02 19:43
Hello there guys, I'll like to contribute in this issue.

**Comment by AlexPelaez** [comment] 2018-11-14 06:10
Hi, I would like to contribute.

**Comment by AlexPelaez** [comment] 2018-11-14 06:10
Hi, I would like to contribute.

**Comment by crownedlake** [comment] 2019-01-31 10:54
@Skippari Hi, I'd like to contribute if this issue is still open.

**Comment by xpdavid** [comment] 2019-01-31 14:02
@Skippari Hi, I believe the issue is resolved in the current `master`.

**Closed by xpdavid** 2019-01-31 14:02 UTC
Labels: a-FaultTolerance, c.Bug, d.FirstTimers, f-Sessions, t-JS
