### ISSUE TITLE
Instructor courses page: other actions dropdown cut off

### ISSUE THREAD

**Issue by weiquu** [TEAMMATES/teammates#12345] opened 2023-04-05 15:56 UTC
Path: Instructor pages -> Courses tab

The `Other Actions` button in the courses table brings up a dropdown that is cut off at the end of the table:
![instructor courses other actions not ok](https://user-images.githubusercontent.com/48304907/230136167-af8f9c1c-a545-4d21-99b2-e6c54a405165.PNG)

The second course is fine as the dropdown appears upwards:
![instructor courses other actions ok](https://user-images.githubusercontent.com/48304907/230136370-5d61b80e-f0a4-4459-886a-4f0973346593.PNG)

I've quickly checked other similar tables and they don't seem to face the same issue.

**Comment by sumitshinde-84** [comment] 2023-04-06 13:12
@weiquu  i am working on that issue .

**Comment by b-walton** [comment] 2023-04-10 01:45
Hi @weiquu . I am a first-time contributor and would love to take on this issue.

**Comment by domlimm** [comment] 2023-04-10 02:02
@b-walton Hello, go ahead and work on this! 👍🏻

**Comment by Mohamed-khattab** [comment] 2023-04-14 03:06
hello @weiquu  , is it still open to work on ?

**Comment by domlimm** [comment] 2023-04-14 03:20
@Mohamed-khattab Hello, thank you for your interest in contributing! Someone has started working on it. Would suggest that you pick another good first issue to work on 👍🏻

**Comment by Mohamed-khattab** [comment] 2023-04-14 03:49
Thank you for letting me know. I appreciate your suggestion and will look for another issue to work on. Have a great day! 😊

**Comment by Anshul-target** [comment] 2023-04-19 17:25
Is this issue still open 
Can I work on it

**Comment by b-walton** [comment] 2023-04-19 19:48
I am no longer working on this issue, but others in the thread might be.

**Comment by domlimm** [comment] 2023-04-20 16:53
@b-walton Thanks!

@Anshul-target Feel free to submit a PR.

**Comment by rk22277** [comment] 2023-04-20 20:43
hi @domlimm can i submit a PR?

**Comment by domlimm** [comment] 2023-04-21 02:22
@rk22277 Hello, let's wait for @Anshul-target to get back first if they are working on it.

**Comment by Anshul-target** [comment] 2023-04-21 16:40
@domlimm sir I have set the system locally could you please tell how to reach to that issue

**Comment by domlimm** [comment] 2023-04-21 16:56
@Anshul-target Hey! Please refer to the description of this issue. You should have both the frontend and backend running in order to test this. Good to look at the [developer documentation](https://teammates.github.io/teammates/setting-up.html) too!

**Comment by weiquu** [comment] 2023-05-13 13:19
Hi @nikhilagastya, I think you can go ahead and work on it

**Comment by nikhilagastya** [comment] 2023-05-14 09:40
sure @weiquu

**Comment by MoosaMemon** [comment] 2023-05-17 13:15
Hey @nikhilagastya, are you still working on it? if not, i'd like to start working on it.

**Comment by AyushSinghRawat-hub** [comment] 2023-05-20 15:44
can you assign it to me i can work on it

**Comment by jasonqiu212** [comment] 2023-05-20 16:42
@MoosaMemon I think you can go ahead and start working on it.

@AyushSinghRawat-hub Thanks for expressing interest to contribute. Let's give others who expressed interest first to work on this issue first. Please feel free to find another issue to work on :)

**Comment by MoosaMemon** [comment] 2023-05-20 17:07
@AyushSinghRawat-hub Sure, you can start working on it.

**Comment by vishnu861** [comment] 2023-05-26 05:06
Is this issue still open? 
I have checked other actions drop down menu, it seems working fine for all rows.

**Comment by weiquu** [comment] 2023-05-26 06:51
@vishnu861, yes please feel free to submit a PR for this issue

**Comment by AndrewVreeland** [comment] 2023-06-15 21:25
I just pulled down the repo locally and have the server running on my end. Where do I access this page? Is this something I need to create an account to access? I would like to see the bug on my end and test my edits

**Comment by weiquu** [comment] 2023-06-16 19:02
Hi @AndrewVreeland, you'll have to [log in as an instructor](https://teammates.github.io/teammates/development.html#logging-in-to-a-teammates-instance) and then navigate to the Courses tab. You can then view the issue by pressing the `Other Actions` button as shown in the issue description above.

**Comment by AndrewVreeland** [comment] 2023-06-17 01:57
hey! @weiquu so we were able to replicate the bug the issue is finding the correct code to fix the bug. I am working with a couple other developers and think we found the issue in the code. the file name is instructor-courses-page.component.scss, the specific line of code we think is at fault is at line 91.  currently the line of code is 
`.table-responsive {
  overflow: auto;
}`
and we believe it should be 
`
.table-responsive {
  overflow: visible;
}
`

here is the difference between these two code blocks. 

overflow: auto;: With this setting, the container will display scrollbars (both horizontal and vertical) when the content overflows its boundaries. If the content fits within the container, no scrollbars will appear. When the content exceeds the container's dimensions, users can scroll within the container to view the hidden content.

overflow: visible;: This setting allows the content to overflow the container without any scrollbars. The content that extends beyond the container's boundaries will be fully visible and may overlap other elements on the page. In other words, it doesn't provide any built-in scrolling mechanism, and any overflow is simply visible.

I am unable to test locally due to an issue of getting the back end running properly so if you could look over this for me I would greatly appreciate it. Thank you! :D

**Comment by weiquu** [comment] 2023-06-17 18:59
Hi @AndrewVreeland, thanks for researching the issue. May I know what issue you're facing regarding the running of the backend? I think it would be better if we resolve that so that you are able to verify the solution on your own (: 

Here's my suggestion: do open up a [discussion](https://github.com/TEAMMATES/teammates/discussions) so that we can try to troubleshoot your backend issue. In the meantime, you can open up a PR with the solution you've outlined if you want, and I'll see if it resolves this issue.

**Comment by Cordoncharge83** [comment] 2023-09-27 12:25
Hello, is this problem solved or not ? And if not, is there someone currently working on it ?

**Comment by jasonqiu212** [comment] 2023-09-28 14:20
Hi @Cordoncharge83, Feel free to submit a PR for this issue!

**Comment by yangyangdotcom** [comment] 2023-09-30 17:37
I would love to work on this issue. Is anyone working on this?

**Comment by jasonqiu212** [comment] 2023-10-01 20:12
@Cordoncharge83 Hi are you still working on this issue?

@yangyangdotcom Thank you for expressing interest to contribute to TEAMMATES! Let's give @Cordoncharge83 a couple more days to work on this issue, since he expressed interest first. You are welcome to tackle any other ongoing issues in the meantime :)

**Comment by yangyangdotcom** [comment] 2023-10-04 17:51
This is my first time being involved in an open-source project, I would like to work on something simpler. I searched through other issues but those required more experience. I would greatly appreciate it if you could direct me to a simpler issue if this issue is still occupied.

**Comment by weiquu** [comment] 2023-10-05 03:55
Hi @yangyangdotcom, since @Cordoncharge83 doesn't seem to be working on this issue, please feel free to take it up! Do keep us updated if you face any issues.

(Thanks for also pointing out that we're running low on `good first issues`s!)

**Comment by yangyangdotcom** [comment] 2023-10-05 04:07
No problem! I will start working on it.

**Comment by yangyangdotcom** [comment] 2023-10-05 16:49
I am trying to replicate the bug but everything seems fine to me.

![Screenshot 2023-10-05 113959](https://github.com/TEAMMATES/teammates/assets/70668131/03378ac5-86ff-4d43-8eb8-fa4edf72198b)

I am able to view all actions from my end. Am I looking at the right page where the bug exists? (I have tested it on different devices and different browsers)

**Comment by weiquu** [comment] 2023-10-09 11:22
Hi @yangyangdotcom, I'm still able to replicate the bug on my end. I'm on mobile, and here are the steps I took:
- Login as instructor
- Navigate to instructor courses page
- On the first active course, click on other actions button
- The result is below:
![photo_2023-10-09_19-22-20](https://github.com/TEAMMATES/teammates/assets/48304907/d32e6bdb-2660-49bf-9d57-be1efc6242d4)

**Comment by Xiawanggg** [comment] 2023-10-10 00:43
Hi guys, I'm interested in this problem and want to fix it. Is there anybody still working on it? If not, I'd like to fix it😄

**Comment by yangyangdotcom** [comment] 2023-10-10 00:53
Currently, I have other duties to fulfill. You can go ahead and work on this.

**Comment by Ting-TT** [comment] 2023-10-10 04:46
Hello,

I've come across this issue and I'm really interested in contributing to it :)))

I've noticed that @Xiawanggg has also expressed interest in working on it. I'd like to inquire if it's possible for me to work on this issue concurrently with @Xiawanggg. 

It's my first time working on an open-source project. I'm eager to start contributing to open-source projects and believe this could be a valuable experience :))

Thank you for your consideration, and I look forward to your response!

**Comment by Ting-TT** [comment] 2023-10-11 23:25
Hiii,

I've carefully read all the comments on this issue and followed the provided steps to replicate the bug. However, during my testing, I could not replicate the issue on my local environment (by using the admin account to log in and mock as an instructor). The dropdown menu appears to be working correctly across various screen sizes.

I've also recorded my testing process, and the dropdown menu seems to function as expected. You can view the recording [here](https://drive.google.com/file/d/1n7fGSJxvVgnEDMf3kUJkT4JFC9COPQQt/view?usp=sharing).

In the meantime, I've applied for an instructor account, and once it's granted, I will log in as an instructor on a mobile device to see if the issue manifests on the actual webpage :))

If anyone who can replicate the bug could kindly provide a screen recording, it would be greatly appreciated, as it will help replicate the issue better 😃 Thank you a lot!!

**Comment by Ting-TT** [comment] 2023-10-17 05:34
> Hiii,
> 
> I've carefully read all the comments on this issue and followed the provided steps to replicate the bug. However, during my testing, I could not replicate the issue on my local environment (by using the admin account to log in and mock as an instructor). The dropdown menu appears to be working correctly across various screen sizes.
> 
> I've also recorded my testing process, and the dropdown menu seems to function as expected. You can view the recording [here](https://drive.google.com/file/d/1n7fGSJxvVgnEDMf3kUJkT4JFC9COPQQt/view?usp=sharing).
> 
> In the meantime, I've applied for an instructor account, and once it's granted, I will log in as an instructor on a mobile device to see if the issue manifests on the actual webpage :))
> 
> If anyone who can replicate the bug could kindly provide a screen recording, it would be greatly appreciated, as it will help replicate the issue better 😃 Thank you a lot!!

Hi @weiquu, so sorry to bother you. I feel like I'm stuck on this issue at the moment. 

Could I get some help from you, please? Could I know what specific steps or scenarios you followed when you first encountered this issue?

Really really appreciated. Thank you.

**Comment by Ting-TT** [comment] 2023-10-18 10:11
Oh yeah, you're right!! Just got the instructor account yesterday, and I can see this bug using my phone's browser as well.
However, I still couldn't replicate this issue on my laptop/using the local instance :((

Would love to see how you fixed this issue!

**Comment by Xiawanggg** [comment] 2023-10-20 02:38
> Oh yeah, you're right!! Just got the instructor account yesterday, and I can see this bug using my phone's browser as well. However, I still couldn't replicate this issue on my laptop/using the local instance :((
> 
> Would love to see how you fixed this issue!


Hi, you can directly check my PR. There it shows the code I updated :)

**Comment by manojkumar20k3** [comment] 2023-10-31 11:52
Hello, I am a beginner in open source contribution. Is this issue open ? If it's open please assign it to me ,So that i can make my first contribution .

**Closed** 2023-11-29 03:50 UTC
Labels: a-UIX, p.Low, good first issue
