### ISSUE TITLE
Join as instructor: institute authentication failed

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10464] opened 2020-07-26 15:51 UTC
Got this error when I clicked on the join link of the instructor account I created. 
![image](https://user-images.githubusercontent.com/1673303/88483467-bb268b00-cf9a-11ea-80b9-47b49cb75bf9.png)

**Comment by wkurniawan07** [comment] 2020-07-26 15:58
The error is what it is shown: "Institute authentication failed". What is the URL used to join?

**Comment by damithc** [comment] 2020-07-26 16:06
> The error is what it is shown: "Institute authentication failed". What is the URL used to join?

What's _institute authentication_?

I used the link emailed by the system, but added `7-0-1-dot-` in front.

**Comment by wkurniawan07** [comment] 2020-07-26 16:09
Refer to #4854

If your old link doesn't have `mac` parameter, this is expected.

**Comment by damithc** [comment] 2020-07-26 16:12
Although I created the account using v7, the link is generated by v6 backend (which is the default instance) and hence not in the new format. Is that the case here?

**Comment by damithc** [comment] 2020-07-26 16:14
> Although I created the account using v7, the link is generated by v6 backend (which is the default instance) and hence not in the new format. Is that the case here?

hang on, the link has a mac. Here it is (key slightly modified)

`https://teammatesv4.appspot.com/web/join?key=XXY9423DCACF50537256EB7C4C04D6B6334D3C3F5761E0A4C800732944216992C57F9A740EA6B8410A99D2ED2AEAE453&instructorinstitution=National+University+of+Singapore%2C+Singapore&mac=481D21D691808A1EA3EC561AE9A5DCBDF41CAF5A&entitytype=instructor`

**Comment by wkurniawan07** [comment] 2020-07-26 16:14
> I created the account using v7, the link is generated by v6 backend

This is not supposed to happen.

**Comment by damithc** [comment] 2020-07-26 16:15
> > I created the account using v7, the link is generated by v6 backend
> 
> This is not supposed to happen.

Yes, that's not the case. I jumped to the wrong conclusion.

**Comment by damithc** [comment] 2020-07-26 16:16
Tried the link again, to be sure. Same error.

**Comment by damithc** [comment] 2020-07-26 16:29
The log doesn't show an error though (just an info message only)
![image](https://user-images.githubusercontent.com/1673303/88484228-a6002b00-cf9f-11ea-8996-3023343048a0.png)

**Comment by wkurniawan07** [comment] 2020-07-26 16:30
The last entry of that screenshot should be where the error is.

**Comment by wkurniawan07** [comment] 2020-07-26 16:47
I think I know what's wrong here.

@madanalogy that link shows `instructorinstitution=National+University+of+Singapore%2C+Singapore`. Does it ring a bell?

**Comment by damithc** [comment] 2020-07-26 16:54
> @madanalogy that link shows `instructorinstitution=National+University+of+Singapore%2C+Singapore`. Does it ring a bell?

To add, I tried without the comma and without the spaces. The second one worked.

**Comment by wkurniawan07** [comment] 2020-07-26 16:55
> To add, I tried without the comma and without the spaces. The second one worked.

If it is, then the problem is exactly what I thought it is.

**Comment by wkurniawan07** [comment] 2020-07-26 16:56
Duplicate of #10400.

**Closed by wkurniawan07** 2020-07-26 16:56 UTC
Labels: p.High, s.ToInvestigate
