### ISSUE TITLE
adminActivityLogPage: improve timezone conversion

### ISSUE THREAD

**Issue by darrenwee** [TEAMMATES/teammates#8386] opened 2018-02-01 05:12 UTC
On `admin/adminActivityLogPage`, the log entries have a time-stamp which may not be in the admin's time zone (to be honest I'm not sure what timezone it is in). Currently, upon clicking the time-stamp, an AJAX request is sent to the server to convert the time-stamp to the admin's local time.

![admin-log-bad](https://user-images.githubusercontent.com/12949331/35661981-95beeda4-0750-11e8-833b-f854a493667f.gif)

The result is not elegant. The time conversion can be either injected into the page or performed client-side, then displayed as a boolstrap tooltip. The ajax request also clears the entire cell which wipes out the time taken to fulfill the request (the bolded part in the above gif).

**Comment by darrenwee** [comment] 2018-02-01 05:12
@tran-tien-dat

**Comment by tran-tien-dat** [comment] 2018-02-01 07:42
The displayed date is wrong because of a bug in the method `TimeHelper#calendarToString`: `SimpleDateFormat` format time in local time, interpreting the `Date` as in UTC time, but this method is used to convert time that has been timezone-offset. I guess this confusion is exactly why we should move to the new `java.time` which separate non timezoned and timezoned time. We will fix this bug in our attempt to migrate to `java.time`

**Comment by tran-tien-dat** [comment] 2018-02-01 07:44
Nevertheless, we can still improve the experience by making timzone conversion happen in the browser instead of sending AJAX request. I will open a PR for this.

**Comment by damithc** [comment] 2018-02-01 08:47
From what I remember, the time shown is in admin's time zone and the time injected is in the user's time zone. Reason: When I communicate with a user, I sometimes need to give times relative to the user's time zone.
Is the current behavior as described above?

**Comment by damithc** [comment] 2018-02-01 09:06
It's correct on the live server, but note that the live server is running V6.0. The feature could have broken since then.
Another thing to note is that live server runs in the UTC+0, which means +8 to that gives us Singapore time zone. If your dev server is running in local time zone, +8 to that will give you UTC+16. Perhaps the code assumes the admin will always be in Singapore, which is fine. :-)

**Comment by tran-tien-dat** [comment] 2018-02-01 12:11
I see, the problem is only with the timezone of the server. The outdated pre-Java 8 time classes mess things up and only works correctly when the server is in UTC+0. Since our server is running in that timezone, things work correctly. Besides, we are migrating to Java 8's `java.time` so this thing will be fixed. Hence, I think we don't need to do any further actions regarding this from the server's side for now.

Regarding the client's side, at first I thought that the injected time is supposed to be admin's time, which can be converted to the browser's timezone client-side, skipping the AJAX requests. However, if it is supposed to be the timezone of the user generating the log entry, then generating the AJAX request to the server would be necessary. So the only change that this issue suggests is just the changing the current click-and-show behaviour to a hover-and-show one instead. Do you think it is necessary, Prof. @damithc since you are the majority of the users of this feature?

**Comment by damithc** [comment] 2018-02-01 13:55
> So the only change that this issue suggests is just changing the current click-and-show behaviour to a hover-and-show one instead. Do you think it is necessary, Prof. @damithc since you are the majority of the users of this feature?

Probably no need. We can spend that effort on something more useful. :-) Thanks for bringing this up and investigating further 👍

**Closed by damithc** 2018-02-01 13:55 UTC
