### ISSUE TITLE
NPE in instructorFeedbackQuestionEdit

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5954] opened 2016-08-03 09:38 UTC
Got this from live server.
```
java.lang.NullPointerException


Actual user abc
Request Method POST
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12
Request Url https://teammatesv4.appspot.com/page/instructorFeedbackQuestionEdit
Request Path /page
Request Parameters {showresponsesto::INSTRUCTORS, showrecipientto::INSTRUCTORS, numofrecipients::1, questionedittype::edit, questiontext::How could the team member improve his performance ?, fsname::Le Studio Feedback, questionid::ag1zfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgPmG-voIDA, numofrecipientstype::max, questiondescription-3::

1-2 sentences. If you dont feel in a position to judge write "cant judge".
, recipienttype::OWN_TEAM_MEMBERS, showgiverto::INSTRUCTORS, questiontype::TEXT, questionnum::1//3, givertype::STUDENTS, user::abc, courseid::75002}
Stack Trace



java.lang.NullPointerException
	at com.google.storage.onestore.v3.OnestoreEntity$PropertyValue.setStringValue(OnestoreEntity.java:3411)
	at com.google.appengine.api.datastore.DataTypeTranslator$BaseStringType.toV3Value(DataTypeTranslator.java:751)
	at com.google.appengine.api.datastore.DataTypeTranslator$TextType.toV3Value(DataTypeTranslator.java:1575)
	at com.google.appengine.api.datastore.DataTypeTranslator.addPropertyToPb(DataTypeTranslator.java:215)
	at com.google.appengine.api.datastore.DataTypeTranslator.addPropertiesToPb(DataTypeTranslator.java:162)
	at com.google.appengine.api.datastore.EntityTranslator.convertToPb(EntityTranslator.java:62)
	at com.google.appengine.api.datastore.AsyncDatastoreServiceImpl$4.toPb(AsyncDatastoreServiceImpl.java:178)
	at com.google.appengine.api.datastore.AsyncDatastoreServiceImpl$4.toPb(AsyncDatastoreServiceImpl.java:155)
	at com.google.appengine.api.datastore.Batcher$BatchIterator.(Batcher.java:180)
	at com.google.appengine.api.datastore.Batcher$2.(Batcher.java:317)
	at com.google.appengine.api.datastore.Batcher.getBatches(Batcher.java:317)
	at com.google.appengine.api.datastore.AsyncDatastoreServiceImpl.doBatchPut(AsyncDatastoreServiceImpl.java:365)
	at com.google.appengine.api.datastore.BaseAsyncDatastoreServiceImpl.put(BaseAsyncDatastoreServiceImpl.java:293)
	at com.google.appengine.api.datastore.BaseAsyncDatastoreServiceImpl$4.runInternal(BaseAsyncDatastoreServiceImpl.java:261)
	at com.google.appengine.api.datastore.TransactionRunner.runWriteInTransaction(TransactionRunner.java:53)
	at com.google.appengine.api.datastore.BaseAsyncDatastoreServiceImpl.put(BaseAsyncDatastoreServiceImpl.java:263)
	at com.google.appengine.api.datastore.BaseAsyncDatastoreServiceImpl.put(BaseAsyncDatastoreServiceImpl.java:234)
	at com.google.appengine.api.datastore.DatastoreServiceImpl.put(DatastoreServiceImpl.java:56)
	at org.datanucleus.store.appengine.RuntimeExceptionWrappingDatastoreService.put(RuntimeExceptionWrappingDatastoreService.java:96)
	at org.datanucleus.store.appengine.DatastorePersistenceHandler.put(DatastorePersistenceHandler.java:196)
	at org.datanucleus.store.appengine.DatastorePersistenceHandler.put(DatastorePersistenceHandler.java:149)
	at org.datanucleus.store.appengine.DatastorePersistenceHandler.put(DatastorePersistenceHandler.java:144)
	at org.datanucleus.store.appengine.DatastorePersistenceHandler.updateObject(DatastorePersistenceHandler.java:575)
	at org.datanucleus.state.JDOStateManagerImpl.flush(JDOStateManagerImpl.java:4576)
	at org.datanucleus.ObjectManagerImpl.flushInternal(ObjectManagerImpl.java:2814)
	at org.datanucleus.ObjectManagerImpl.flush(ObjectManagerImpl.java:2754)
	at org.datanucleus.ObjectManagerImpl.preCommit(ObjectManagerImpl.java:2893)
	at org.datanucleus.TransactionImpl.internalPreCommit(TransactionImpl.java:369)
	at org.datanucleus.TransactionImpl.commit(TransactionImpl.java:256)
	at org.datanucleus.ObjectManagerImpl.close(ObjectManagerImpl.java:801)
	at org.datanucleus.jdo.JDOPersistenceManager.close(JDOPersistenceManager.java:271)
	at teammates.storage.api.FeedbackQuestionsDb.updateFeedbackQuestion(FeedbackQuestionsDb.java:206)
	at teammates.storage.api.FeedbackQuestionsDb.updateFeedbackQuestion(FeedbackQuestionsDb.java:160)
	at teammates.logic.core.FeedbackQuestionsLogic.updateFeedbackQuestion(FeedbackQuestionsLogic.java:610)
	at teammates.logic.core.FeedbackQuestionsLogic.updateFeedbackQuestion(FeedbackQuestionsLogic.java:586)
	at teammates.logic.core.FeedbackQuestionsLogic.updateFeedbackQuestionNumber(FeedbackQuestionsLogic.java:515)
	at teammates.logic.api.Logic.updateFeedbackQuestionNumber(Logic.java:1734)
	at teammates.ui.controller.InstructorFeedbackQuestionEditAction.editQuestion(InstructorFeedbackQuestionEditAction.java:96)
	at teammates.ui.controller.InstructorFeedbackQuestionEditAction.execute(InstructorFeedbackQuestionEditAction.java:52)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:344)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:64)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:29)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)


	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:148)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:504)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:446)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:453)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:276)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:312)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:304)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:450)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by belyabl9** [comment] 2016-08-03 10:06
The reason of the problem seems to be 'questiondescription-3' instead of 'questiondescription'.
I can fix it, but I need to reproduce the problem. Could somebody check it ? I tried on dev server and on staging but question is edited without errors

**Comment by damithc** [comment] 2016-08-03 10:15
I can't reproduce it on my computer. Is this related to the browser? 
When I checked the database, some questions seemed to have duplicate question numbers (a known problem that can occur occasionally), which I fixed. Perhaps that is a different problem altogether.
![image](https://cloud.githubusercontent.com/assets/1673303/17362096/1d36b21c-59a6-11e6-9b18-34caba80505c.png)

**Comment by damithc** [comment] 2016-08-03 10:28
The user still cannot save questions even after I fixed the question number problem. So it is something else.

**Comment by damithc** [comment] 2016-08-03 10:29
Looks like the user is using Firefox on Mac, based on the log message.

**Comment by damithc** [comment] 2016-08-03 10:34
BTW, this error is produced by V5.85.01 which is the latest released version.

**Comment by damithc** [comment] 2016-08-03 14:01
User says she tried using Firefox and Safari, but no luck. However, she says it started working after a while. Our logs seem to match what the user is saying.  Any clue from the stack trace?

**Comment by damithc** [comment] 2016-08-10 02:12
The cause could be a buggy tinymce js file that some users loaded from an outdated CDN cache?

**Comment by damithc** [comment] 2016-08-10 02:15
This user is on Mac, but using Safari.

**Comment by damithc** [comment] 2016-08-10 05:48
User says it worked in Chrome.

**Comment by wkurniawan07** [comment] 2016-08-10 15:19
I don't think there is any "CDN cache" to talk about; we're hosting our own tinymce file and it's lifted directly from what's hosted in NPM.

**Comment by damithc** [comment] 2016-08-10 15:51
In that case it sounds like a browser issue, in which case it should be easy to reproduce. The first user said changing browser did not work but it started working on it's own again. Second user said it started working when she switched from safari to chrome. Of course we can't completely go by what users say because they might believe one thing when in fact it is something else.

**Comment by belyabl9** [comment] 2016-08-10 15:55
@damithc , all you've just described looks like problems with asynchronous execution that is going to be fixed in the provided PR.
Could you get the exact steps to reproduce ? May be we miss something while trying to reproduce the issue.

**Comment by belyabl9** [comment] 2016-08-10 15:59
If the feature doesn't work in browser at time T1, but works at time T2 in a common browser, it seems that there are two possible variables: user's behavior or CPU/network capability (i.e. time of execution of specific part of code)

**Comment by damithc** [comment] 2016-08-10 16:02
It's hard to get more data as end users are non-experts. Let's hope this PR fixes the problem. If not, we'll have to investigate more when it happens again. With more data points, we might start seeing some pattern.

**Closed** 2016-08-14 09:11 UTC
Labels: c.Bug, f-Submissions, p.Urgent
