### ISSUE TITLE
Issue templates: remove the requirement for issue title prefixes

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#6631] opened 2017-02-17 04:44 UTC
Requiring a prefix e.g. `Bug report:` is redundant as there are labels to indicate the type of an issue (e.g. `c.Bug`). Instead of using part of the issue title to show redundant info, it's more profitable to use prefixes (optionally) to indicate the scope of the issue. e.g. `Issue templates:`

**Comment by wkurniawan07** [comment] 2017-02-17 05:11
While labels do replace the value of prefixes in issues, they are short-lived in that they are not transferred to PRs and merge commit messages. Looking at a PR title or merge commit message does not immediately tell whether it is a bug fix, enhancement, etc. and if we ever want to make a changelog, being able to identify a commit type just by looking at such message is a necessity.

This limitation is introduced because we have to *precisely* copy-and-paste the issue title. Either we:
- Keep that AND require to prefix issue titles (like how it is done now).
- Scrap that and require prefix just for PR titles (and eventually merge commit messages), at the expense that the PR title will not be the carbon copy of its issue title anymore.

**Comment by damithc** [comment] 2017-02-17 06:02
That's a valid point. The change log, if we were to have one, is for internal use only (it's not end-user friendly anyway), so may be no need to have the type prefix in the change log?. Note that the title length is a big issue in commit titles. We need to limit it to 50 chars and `Feature request` is already 15 chars. Alternatively, we can insert the type prefix into the change log manually after generating it from the commit history?  

However, I do want to add a step to the workflow (may be just before merging) to ensure phrasing in the title matches the type of issue (i.e. a bug is not phrased like a feature) and matches what the issue eventually ended up doing (sometimes issues change direction mid-course).

**Comment by wkurniawan07** [comment] 2017-02-17 10:28
> The change log, if we were to have one, is for internal use only.

I don't think this gives a basis for the changelog to be any less informative.

> Note that the title length is a big issue in commit titles. We need to limit it to 50 chars and Feature request is already 15 chars.

Why 50? If it's from [this page](https://chris.beams.io/posts/git-commit/) (don't get me wrong, I agree with most of the content of that post), 50 is a good-to-reach goal but the hard limit is 72. If the issue is the prefix is too long, we can make it short like `Bug:`, `Feature:`, `Enhance:`, `Task:`, etc.

> Alternatively, we can insert the type prefix into the change log manually after generating it from the commit history

The only problem with this is many projects out there already automate their changelog generation process. We're living in the age where 99% of devops stuffs are automated. 😛

**Comment by damithc** [comment] 2017-02-17 11:29
Yes, 50 is a soft limit. 
Yes, shorter prefixes might be better.
Perhaps we can add that to merge commit title instead? e.g. `[Bug #123] student is not deleted (#124)` instead of issue title? Merging is done by fewer people and that means fewer points of failure. 
On a related note I don't think we can rely entirely on commit title to generate useful change logs. Probably will need to use commit message body as well.

**Comment by wkurniawan07** [comment] 2017-02-20 10:24
Indeed, it seems like the good solution will be to add the prefix on the merge commit message only. The prefix can follow the `c.*` label of the issue, but that means all the issues with PRs must be labelled with `c.*` label (not a difficult job though).
`[Bug #123] Issue title (#124)` or `[#123] Bug: Issue title (#124)`?

**Comment by damithc** [comment] 2017-02-20 14:08
I prefer first format because that allows us to include an optional scope prefix without needing multiple colons.

`[Bug #123] email templates: remove blank lines (#124)`
or 
`[#123 Bug] email templates: remove blank lines (#124)` 
// this one avoids possible confusion with GitHub's `Fixes #123` notation.

**Comment by wkurniawan07** [comment] 2017-02-23 19:10
So I guess here's the final decision on the workflow:
- Issue title: no prefix; accepted issues **must** be labelled with `c.*`.
- PR title: no prefix; still a verbatim copy of the issue title and issue number, as usual.
- Merge commit message: `[#123 Category] Issue title (#124)`. `Category` can be `Bug|Task|Enhancement|Story` as how our `c.*` label is defined.

**Comment by damithc** [comment] 2017-02-24 01:09
Yes, that seems to be the smoothest path from our legacy workflow with the least amount of extra work.
If the `c.*` label is not applied, the person merging can decide the category of the PR at the time of merging. That way, we can reduce the extra work even further.

**Comment by samsontmr** [comment] 2017-02-24 13:58
We could also use the first letter of the category to represent it to cut down on character count.

**Closed** 2017-03-05 10:28 UTC
Labels: a-Process, c.DevOps, p.Medium
