### ISSUE TITLE
Tables showing incorrect message after loading

### ISSUE THREAD

**Issue by FergusMok** [TEAMMATES/teammates#11551] opened 2022-02-01 12:48 UTC
When loading the home page, after the spinner has disappeared, the course shows the standard "Currently, there is no open feedback/response.." briefly, before displaying the actual results.
The bug seems to affect other tables that need to be populated with data from the backend too (e.g Instructor's Students page)

https://user-images.githubusercontent.com/10182564/151970902-cf626287-0c2a-4411-8830-9edd5c0f068e.mp4

- **Environment**: 
Live server V8.6.0, able to replicate on both the latest versions of Firefox and Chrome.

**Steps to reproduce**
1. Log in as Instructor or Student
2. Go to / Reload the home page

**Expected behaviour**
The displaying of the table's data should be accurate the moment the spinner stops.

**Actual behaviour**
The table shows the equivalent of 'no entries' after the spinner stops briefly, then displays the correct data.

**Comment by fsgmhoward** [comment] 2022-02-06 06:50
I am able to reproduce this on my Firefox browser. It looks like the loading circle vanishes after loading session list but before `hasResponses` being loaded. I guess I can take a look at this.

**Comment by fsgmhoward** [comment] 2022-02-11 05:37
I cannot reproduce the same issue for instructor. Could you please provide more detail for that?
For the student home page it should be fixed in my PR.

**Comment by FergusMok** [comment] 2022-02-11 07:42
@fsgmhoward The recording may show the problem more clearly. But basically the same problem with the student tables.

https://user-images.githubusercontent.com/10182564/153553882-0ac86109-d4ae-4b6c-989c-d67ee6c662a6.mp4

**Comment by fsgmhoward** [comment] 2022-02-11 11:01
@FergusMok Thanks for the recording. I only checked the Instructor Home page. Let me go check about it.

**Comment by fsgmhoward** [comment] 2022-02-12 04:44
I have pushed the changes to the PR. It should have fixed this issue.

**Comment by FergusMok** [comment] 2022-04-19 15:34
Seems like after the fix, I'm still able to replicate the problem on V8.14.0

https://user-images.githubusercontent.com/10182564/164041169-6f7b6905-747d-40f0-915c-a5a4ad132b4d.mp4

**Comment by fsgmhoward** [comment] 2022-04-19 15:41
@FergusMok That is weird. I will look into it later.

**Closed** 2022-04-24 03:08 UTC
Labels: c.Bug
