### ISSUE TITLE
CI tests skipped after merge branch

### ISSUE THREAD

**Issue by leeyimin** [TEAMMATES/teammates#6509] opened 2017-01-31 17:27 UTC
Tests were skipped after merging branch through the GitHub PR page. The build should not have passed as there was a failing test case. The merge commit also had code changes and not just doc changes.

https://travis-ci.org/TEAMMATES/teammates/builds/196991962

CI passing even though it should have failed: 
![image](https://cloud.githubusercontent.com/assets/6365864/22476268/ae735488-e81c-11e6-930d-d21048ea2054.png)

**Comment by AnaghHegde** [comment] 2017-01-31 17:57
@leeyimin It happened with me also 3 days back . 
![screenshot 63](https://cloud.githubusercontent.com/assets/12005551/22477562/9fdff558-e80c-11e6-81cb-d9c2619f38e1.png)

Later i just added 1 newline to the file and committed it gave error.

**Comment by AnaghHegde** [comment] 2017-01-31 18:00
@leeyimin It happened with me also .
![screenshot 64](https://cloud.githubusercontent.com/assets/12005551/22477706/21b49bce-e80d-11e6-9786-962f419bb5ad.png)

Later i just added 1 new line and committed and build failed.

**Comment by damithc** [comment] 2017-02-01 01:56
> Tests were skipped after merging branch through the GitHub PR page. The build should not have passed as there was a failing test case. The merge commit also had code changes and not just doc changes.
> 
> https://travis-ci.org/TEAMMATES/teammates/builds/196991962

@whipermr5 may be related to recent PR that makes Travis skip for 'docs only' commits?

**Comment by whipermr5** [comment] 2017-02-01 03:47
Yes; it is. The build log hints at the problem when the `git diff` fails with:
`fatal: Invalid symmetric difference expression dccb667c67bb26167a7e9b0f7c37bf660043032c...3ff9882665c14638812259e722327d0fdc25fc77`
At first I thought it might be due to [an open Travis issue](https://github.com/travis-ci/travis-ci/issues/4596), but it seems more like Git being unable to compare those two commits in the build environment. I thought to try reproducing the error locally first, but have not been able to so far:
<img width="1060" alt="screen shot 2017-02-01 at 11 44 57 am" src="https://cloud.githubusercontent.com/assets/6811428/22494621/e1dc9328-e873-11e6-8e0c-ffea3cbd9913.png">
The error in the last command shown in the screenshot was only because I intentionally botched the commit hash by changing the last character from 7 to 6. This is the error we need to reproduce.

Still investigating.

**Comment by wkurniawan07** [comment] 2017-02-01 07:54
It seems like the variable `TRAVIS_COMMIT_RANGE` is returning an erroneous commit hash for some reasons. So far we got three cases of this: [here](https://travis-ci.org/TEAMMATES/teammates/builds/197193160), [here](https://travis-ci.org/TEAMMATES/teammates/builds/197028227), [here](https://travis-ci.org/TEAMMATES/teammates/builds/197069054). It pales in comparison with the number of successful builds so it's not a big problem.

**Comment by whipermr5** [comment] 2017-02-01 08:15
And yet the commit hashes seem to be correct... the build https://travis-ci.org/TEAMMATES/teammates/builds/196991962 indeed corresponds to the PR commit [3ff9882665c14638812259e722327d0fdc25fc77](https://github.com/TEAMMATES/teammates/commit/3ff9882665c14638812259e722327d0fdc25fc77) that merged in the AppVeyor commit [dccb667c67bb26167a7e9b0f7c37bf660043032c](https://github.com/TEAMMATES/teammates/commit/dccb667c67bb26167a7e9b0f7c37bf660043032c) (the latest commit to master at the time).

**Comment by damithc** [comment] 2017-02-01 08:25
A dirty hack would be to run tests anyway in case of error. i.e. skip CI only if the conditions are met without any errors.

**Closed** 2017-02-02 17:34 UTC
