### ISSUE TITLE
Instructor creating courses: auto-trim text fields

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11941] opened 2022-08-21 03:02 UTC
v8.19.2, production

Current: When creating a course, there will be an error message if the course ID or the name has leading/trailing white spaces

![image](https://user-images.githubusercontent.com/1673303/185773399-d7322504-46bf-4ca4-bebe-8b3fd08aed57.png)

Suggestion: Auto-trim those fields as such leading/trailing spaces are sure to be accidental rather than intended.

**Comment by domlimm** [comment] 2022-08-21 03:12
Hello prof, I would like to please pick up this issue.

**Comment by damithc** [comment] 2022-08-21 03:36
@domlimm let's leave this to a first time contributor (unless someone from the dev team thinks it is too much for a first timer)

**Comment by thomasengels** [comment] 2022-08-21 08:40
I would like to take this on :D my first contribution to opensource

**Comment by Basfar** [comment] 2022-08-22 09:26
I would like to take this up

**Comment by Ranzeb** [comment] 2022-08-22 09:38
HI, I would like to take this issue up and try to fix it

**Comment by fsgmhoward** [comment] 2022-08-22 12:49
Lets make it first come first serve. @thomasengels Would you like to proceed with it?

**Comment by thomasengels** [comment] 2022-08-22 22:42
Definitely :D

**Comment by Shubhcs01** [comment] 2022-08-24 13:51
Is this issue resolved?

**Comment by thomasengels** [comment] 2022-08-24 14:53
I will check the code later today. Just have been super busy with my actual developer job

**Comment by akhil9281** [comment] 2022-08-28 06:23
Hello, I would like to work this issue. Can anyone tell me which file does this "COURSES" exist ??

**Comment by seb-lex** [comment] 2022-08-28 13:24
> Hello, I would like to work this issue. Can anyone tell me which file does this "COURSES" exist ??

I couldn't find it either. I did a text search for words on the page but found numerous files containing it. Not sure what we'd edit.

**Comment by fsgmhoward** [comment] 2022-08-29 03:05
@thomasengels Any updates?

@akhil9281 @seb-lex Hold on first. Someone has taken it and yet to give up. It would probably not be nice to post duplicated PR on the same issue. If you would still like to investigate the issue, for the handler, I would suggest to trace down by finding the correct servlet class from this file: https://github.com/TEAMMATES/teammates/blob/675374990ed027b474f63fc40ccfd7524ff0baaf/src/main/webapp/WEB-INF/web.xml

**Comment by harsitagarwalla187** [comment] 2022-08-29 15:14
Hi, I am newbie. What knowledge is required to solve this issue?

**Comment by fsgmhoward** [comment] 2022-09-13 12:26
I think it can be considered that @thomasengels gave up on this since no replied has been received.

@Basfar @Ranzeb @Shubhcs01 @akhil9281 @seb-lex Any of you would like to take a look at this? If not, will pass to @LokeshSingh1102 .

**Comment by ethanotran** [comment] 2022-09-14 04:56
Is this issue open? looking for my first contribution to open source projects.

**Comment by LokeshSingh1102** [comment] 2022-09-15 14:48
I think they are not taking this on. Should i proceed with this issue @fsgmhoward??

**Comment by thomasengels** [comment] 2022-09-15 15:31
Someone else can take it

**Comment by ethanotran** [comment] 2022-09-15 17:04
I tried to build the back-end server, in Git Bash using both ./gradlew serverRun & and ./gradlew.bat serverRun &. The results are the same: I never got to "BUILD SUCCESSFUL". Instead, the console outputs:  
 <===========--> 85% EXECUTING [45m 48s]
The time in the brackets keep incrementing, even if I leave the console overnight. The time gets updated but it never gets past 85%. Can you give me some pointers to move forward?

**Comment by domlimm** [comment] 2022-09-15 17:35
@ethanotran hello, this is the intended behavior. Could refer to #11889.

**Comment by ethanotran** [comment] 2022-09-15 19:53
I'm trying to fix this issue. I would like to first replicate the issue, I believe I need instructor privilege in order to create a course.  Since I'm not an instructor, what can I do to gain sufficient privilege for issue replication?

**Comment by fsgmhoward** [comment] 2022-09-16 01:29
@LokeshSingh1102 Sure. Please go ahead.

**Comment by ShubhraSuman** [comment] 2022-10-06 18:07
Can you assign it to me?

**Comment by tusharrajpoot** [comment] 2022-10-08 19:28
@fsgmhoward can i work with this issue?

**Comment by KillerEnigma** [comment] 2022-10-15 05:49
I would like to work on this issue @fsgmhoward

**Comment by ypinhsuan** [comment] 2022-10-16 07:47
Hi @ShubhraSuman there is no open PR for this issue, would you like to work on it?

**Comment by ShubhraSuman** [comment] 2022-10-16 07:54
Sure @ypinhsuan

**Comment by Haoting-Chen** [comment] 2022-10-18 00:34
@fsgmhoward may I work on this issue? We are doing a group assignment at uni that has to work on an issue from open-source software.

**Comment by Haoting-Chen** [comment] 2022-10-18 02:33
This is a simple and quick issue and can be solved by adding a single line of code.

**Comment by fsgmhoward** [comment] 2022-10-18 05:19
Hi @Haoting-Chen , the person taking this issue previously has not given up. Please seek other issues to work on. Thank you so much.

**Comment by Haoting-Chen** [comment] 2022-10-18 05:32
@ShubhraSuman Sorry for bothering you. I am currently working on a group assignment at uni that we have to solve as many issues as we can for Teammates. The assignment is due next week. If you haven't started yet, would you like to hand over this issue to me?  I have figured out how to do it and can start immediately.

**Comment by ShubhraSuman** [comment] 2022-10-18 05:42
okay u can take it.

**Comment by Haoting-Chen** [comment] 2022-10-18 05:45
@ShubhraSuman Thank you so much for giving me the issue. @fsgmhoward Could you please assign the issue to me?

**Comment by Haoting-Chen** [comment] 2022-10-18 14:01
Hi, I have completed this issue and submitted a PR https://github.com/TEAMMATES/teammates/pull/11974

**Closed** 2022-10-29 09:52 UTC
Labels: p.Low, good first issue
