### ISSUE TITLE
Student submitting responses: ambiguous error message

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10946] opened 2021-02-03 03:46 UTC
Reported by a user:

![image](https://user-images.githubusercontent.com/1673303/106695326-5026d280-6615-11eb-8a38-b3f8491f9fa3.png)

Perhaps remove the ambiguity and/or give more guidance to the user?

**Comment by wkurniawan07** [comment] 2021-02-03 03:48
This is old version before the submission confirmation got removed (notice the missing confirmation button).

**Comment by damithc** [comment] 2021-02-03 03:52
> This is old version before the submission confirmation got removed (notice the missing download confirmation button).

I thought it's odd too. So, a stale cache problem? But the session in question is very recent. 

![image](https://user-images.githubusercontent.com/1673303/106695725-26ba7680-6616-11eb-8472-cdb82886f69b.png)

**Comment by wkurniawan07** [comment] 2021-02-03 03:54
Front-end cache doesn't store anything from DB

**Comment by wkurniawan07** [comment] 2021-02-04 05:18
Closing as this is not a valid issue

**Comment by damithc** [comment] 2021-02-11 06:11
I received several more reports of this problem. Is there a way to reduce the incidence? e.g., setting some sort of cache expiry window? Or it's not in our control at all?

**Comment by rrtheonlyone** [comment] 2021-02-12 14:18
> I received several more reports of this problem. Is there a way to reduce the incidence? e.g., setting some sort of cache expiry window? Or it's not in our control at all?

Right now - we have set an expiration for our static files as follows:

https://github.com/TEAMMATES/teammates/blob/5621286df24b2780ae7f4966fdbd3269822ec033/src/main/webapp/WEB-INF/appengine-web.template.xml#L20-L26

The above specifies the length of time a static file served by this handler should be cached by web proxies and browsers. 

> After a file is transmitted with a given expiration time, there is generally no way to clear it out of web-proxy caches, even if the user clears their own browser cache. Re-deploying a new version of the app will not reset any caches. Therefore, if you ever plan to modify a static file, it should have a short (less than one hour) expiration time. In most cases, the default 10-minute expiration time is appropriate.

The above is taken from the [docs here](https://cloud.google.com/appengine/docs/standard/python/how-requests-are-handled#static_cache_expiration)

@damithc we can adjust the above expiration time to be shorter. However, it looks like there is no guarantee that all the web-proxy caches will be cleared. A stackoverflow answer suggests this [method to update the version](https://stackoverflow.com/a/53033568/13750147)

**Comment by damithc** [comment] 2021-02-13 05:40
Thanks for the investigation @rrtheonlyone 

> @damithc we can adjust the above expiration time to be shorter. However, it looks like there is no guarantee that all the web-proxy caches will be cleared. A stackoverflow answer suggests this [method to update the version](https://stackoverflow.com/a/53033568/13750147). Might be worth a try.

![image](https://user-images.githubusercontent.com/1673303/107842742-72cc9e80-6e00-11eb-90e7-1cd8dd2493f1.png)

I'm a bit scared to go ahead with this on the live server. It doesn't say the rule applies to static files only. Can one of you try on a staging server first?

**Comment by damithc** [comment] 2021-02-13 05:41
> Right now - we have set an expiration for our static files as follows:
> 
> https://github.com/TEAMMATES/teammates/blob/5621286df24b2780ae7f4966fdbd3269822ec033/src/main/webapp/WEB-INF/appengine-web.template.xml#L20-L26
> 
> The above specifies the length of time a static file served by this handler should be cached by web proxies and browsers.
> 
> > After a file is transmitted with a given expiration time, there is generally no way to clear it out of web-proxy caches, even if the user clears their own browser cache. Re-deploying a new version of the app will not reset any caches. Therefore, if you ever plan to modify a static file, it should have a short (less than one hour) expiration time. In most cases, the default 10-minute expiration time is appropriate.
> 
> The above is taken from the [docs here](https://cloud.google.com/appengine/docs/standard/python/how-requests-are-handled#static_cache_expiration)

Shall we set this to a shorter time?

**Comment by rrtheonlyone** [comment] 2021-02-13 05:55
@damithc Okay shall we do `1d` for the expiration of all files? 

> I'm a bit scared to go ahead with this on the live server. It doesn't say the rule applies to static files only. Can one of you try on a staging server first?

I have a staging server setup recently - let me try the above and see what happens

**Comment by wkurniawan07** [comment] 2021-02-13 06:03
> Shall we set this to a shorter time?

That file is not version-controlled. Can just redeploy with modified value. But only changing the value of `index.html` can have any effect here. The CSS/JS files are hashed so they're as good as non-existent unless called by the outdated `index.html`.

**Comment by rrtheonlyone** [comment] 2021-02-13 06:15
> But only changing the value of index.html can have any effect here. 

Oh yes, your right - guess then it is already at a reasonable value of `1d` expiration

**Comment by wkurniawan07** [comment] 2021-05-16 12:52
Closing as the issue as described is not reproducible. Stale cache is an entirely different issue.

**Closed by wkurniawan07** 2021-05-16 12:52 UTC
Labels: s.ToDiscuss
