### ISSUE TITLE
Memory out of error after V7 deployed

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10640] opened 2020-08-24 05:31 UTC
Received this error at each of the hourly automated tasks, twice. We occasionally receive this error triggered by different parts of the code e.g., when a user tries to load the report of a big course. But immediately after V7 release and from an automated action is slightly more worrying. Might not be related to V7 though. 
I have rolled back to V6. If the same happens again, most likely not related to V7. 

>Error Message: teammates.common.util.Logger severe: OutOfMemoryError caught by CronJobServlet:
java.lang.OutOfMemoryError: GC overhead limit exceeded
at java.util.ArrayList.iterator(ArrayList.java:841)
at com.googlecode.objectify.impl.translate.ClassPopulator.load(ClassPopulator.java:115)
at com.googlecode.objectify.impl.translate.ClassPopulator.load(ClassPopulator.java:111)
at com.googlecode.objectify.impl.translate.ClassTranslator.loadSafe(ClassTranslator.java:122)
at com.googlecode.objectify.impl.translate.ClassTranslator.loadSafe(ClassTranslator.java:21)
at com.googlecode.objectify.impl.translate.NullSafeTranslator.load(NullSafeTranslator.java:17)
at com.googlecode.objectify.impl.EntityMetadata.load(EntityMetadata.java:74)
at com.googlecode.objectify.impl.LoadEngine.load(LoadEngine.java:185)
at com.googlecode.objectify.impl.LoadEngine$1.nowUncached(LoadEngine.java:141)
at com.googlecode.objectify.impl.LoadEngine$1.nowUncached(LoadEngine.java:127)
at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
at com.googlecode.objectify.impl.Round$1.nowUncached(Round.java:71)
at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
at com.googlecode.objectify.LoadResult.now(LoadResult.java:25)
at teammates.storage.api.CoursesDb.getCourseEntity(CoursesDb.java:142)
at teammates.storage.api.CoursesDb.getCourse(CoursesDb.java:33)
at teammates.logic.core.CoursesLogic.getCourse(CoursesLogic.java:119)
at teammates.logic.core.FeedbackSessionsLogic.getFeedbackSessionsWhichNeedAutomatedPublishedEmailsToBeSent(FeedbackSessionsLogic.java:180)
at teammates.logic.api.Logic.getFeedbackSessionsWhichNeedAutomatedPublishedEmailsToBeSent(Logic.java:1444)
at teammates.ui.automated.FeedbackSessionPublishedRemindersAction.execute(FeedbackSessionPublishedRemindersAction.java:15)
at teammates.ui.automated.AutomatedServlet.executeTask(AutomatedServlet.java:42)
at teammates.ui.automated.CronJobServlet.doGet(CronJobServlet.java:17)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)

>Error Message: teammates.common.util.Logger severe: OutOfMemoryError caught by CronJobServlet:
java.lang.OutOfMemoryError: GC overhead limit exceeded
at com.googlecode.objectify.impl.LoaderImpl.createLoadEngine(LoaderImpl.java:235)
at com.googlecode.objectify.impl.LoaderImpl.key(LoaderImpl.java:113)
at com.googlecode.objectify.impl.LoadTypeImpl.id(LoadTypeImpl.java:96)
at teammates.storage.api.CoursesDb.getCourseEntity(CoursesDb.java:142)
at teammates.storage.api.CoursesDb.getCourse(CoursesDb.java:33)
at teammates.logic.core.CoursesLogic.getCourse(CoursesLogic.java:119)
at teammates.logic.core.FeedbackSessionsLogic.getFeedbackSessionsClosingWithinTimeLimit(FeedbackSessionsLogic.java:511)
at teammates.logic.api.Logic.getFeedbackSessionsClosingWithinTimeLimit(Logic.java:1435)
at teammates.ui.automated.FeedbackSessionClosingRemindersAction.execute(FeedbackSessionClosingRemindersAction.java:19)
at teammates.ui.automated.AutomatedServlet.executeTask(AutomatedServlet.java:42)
at teammates.ui.automated.CronJobServlet.doGet(CronJobServlet.java:17)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:119)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:187)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)

**Comment by wkurniawan07** [comment] 2020-08-24 06:17
Duplicate of #9936

**Closed by wkurniawan07** 2020-08-24 06:17 UTC
Labels: p.Urgent
