### ISSUE TITLE
Set character limit on feedback configuration

### ISSUE THREAD

**Issue by CaduRoriz** [TEAMMATES/teammates#12459] opened 2023-05-30 19:40 UTC
Inside feedback editing functionality, in the test setup description it doesn't have a character limit what could causes a lot of problems 
![image](https://github.com/TEAMMATES/teammates/assets/77363222/b4809bfe-7b70-4f15-b291-83ddfe1cf07e)

**Comment by samuelfangjw** [comment] 2023-05-30 19:43
@CaduRoriz Could you elaborate on this, what problems exactly?

**Comment by wkurniawan07** [comment] 2023-05-31 03:18
Duplicate of #12455

**Closed by wkurniawan07** 2023-05-31 03:18 UTC
Labels: s.NeedsInfo
