### ISSUE TITLE
Student: submit responses: fix rubric questions overflowing the question box

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8542] opened 2018-02-26 06:56 UTC
v6.3.0
![image](https://user-images.githubusercontent.com/1673303/36656829-fe947052-1b04-11e8-96b9-391c0a97a82f.png)

**Comment by Shashwat-Garg** [comment] 2018-02-26 13:13
I could not reproduce using the updated code of github. Or is it to be reproduced some other way ?

**Comment by damithc** [comment] 2018-02-26 14:26
> I could not reproduce using the updated code of github. Or is it to be reproduced some other way ?

I guess it depends on the question contents. When contents have long words, they add up to push the content out of the box.
![image](https://user-images.githubusercontent.com/1673303/36675438-e5c3543c-1b43-11e8-91a3-f51bc90bd284.png)

**Comment by tshradheya** [comment] 2018-02-26 15:35
I used `word-break: break-word;` and it fixed in the following manner (it doesn't look good though :P )

![image](https://user-images.githubusercontent.com/12574756/36679119-67c67668-1b4d-11e8-974d-e01509fb5971.png)


Is there some more elegant way? Making it scrollable will make it look even worse imo

**Comment by damithc** [comment] 2018-02-27 01:19
Rubric questions need to be given plenty of horizontal space. I wish there is a way to use some this empty space to show the question.
![image](https://user-images.githubusercontent.com/1673303/36705250-1c8aed4e-1b9f-11e8-95f1-41dca689e4ee.png)

**Comment by craaaa** [comment] 2018-02-27 10:02
We could push the rubric down to a different row from the evaluee/recipient, like this:
![image](https://user-images.githubusercontent.com/12183503/36722167-d92f94ca-1be7-11e8-81c4-133952f05885.png)
(ignore the lack of word-wrap!)

But if we do this, then the style of rubric questions will be pretty different from other questions (e.g. the evaluee/recipient header looks a bit out of place in the screenshot above) so not sure if this is something we want to pursue.

**Comment by sukanta-27** [comment] 2018-02-27 10:34
@craaaa IMO using the space prof. @damithc suggested in https://github.com/TEAMMATES/teammates/issues/8542#issuecomment-368712030 will not solve the problem completely. As we can see in this above screenshot that the table still overflows the question box, not to mention if someone wants to add one more column the scenario will be same as before (with less appealing UI and a lot of refactoring for rubric question). 

SO I think at some point we will have to add scrolling feature to stop the overflowing problem (https://github.com/TEAMMATES/teammates/issues/8542#issuecomment-368572530 ), which will be a lot simpler and consistent with the rest of the UI.

**Comment by craaaa** [comment] 2018-02-27 13:55
@sukanta-27 Yes, there's definitely a need for some form of wrapping or scrolling here to solve the primary problem. Was just thinking that making better use of the horizontal space would prevent the table from spilling over in more cases, so we would need either wrap/scroll in fewer cases. Both solutions work but are much less satisfying than having the entire table well-displayed :)

(FWIW I prefer the word-wrap; the horizontal scroll reduces visibility of some of the options which I think should be avoided if possible, particularly since respondents will have to scroll back and forth to compare between options)

**Comment by damithc** [comment] 2018-02-27 15:28
> We could push the rubric down to a different row from the evaluee/recipient, like this:

I think we should have some indentation so that the question a bit more indented than the name. 

And yes, we need some wrap/scroll solution as well.

**Comment by wkurniawan07** [comment] 2020-08-16 10:26
Fixed in V7

**Closed by wkurniawan07** 2020-08-16 10:26 UTC
Labels: a-UIX, f-Questions, p.Low
