### ISSUE TITLE
Show an appropriate view while the data is loading

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10359] opened 2020-07-18 18:17 UTC
I think we are working on this already, but I'll create an issue here in case we need to discuss further. Currently, we show an incorrect view while the data is being loaded e.g., show 'no courses to view' while courses are being loaded.

Showing a spinner seems like the natural alternative.

**Comment by wkurniawan07** [comment] 2020-07-18 18:23
Duplicate of #9356

**Closed by wkurniawan07** 2020-07-18 18:23 UTC
Labels: p.High
