### ISSUE TITLE
Admin create accounts: make all sample students unregistered

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11039] opened 2021-03-17 10:00 UTC
Feature in concern: admin creating new instructor accounts

Today, I tried to create 35 new instructors in one go, which resulted in about 5 of them failing. The error given below:

>Error Message: teammates.common.util.Logger severe: ConcurrentModificationException caught by WebApiServlet:
java.util.ConcurrentModificationException: too much contention on these datastore entities. please try again. entity group key: (app=s~teammatesv4, Account, "alice.b.tmms.sampleData")
at com.google.appengine.api.datastore.DatastoreApiHelper.translateError(DatastoreApiHelper.java:52)
at com.google.appengine.api.datastore.DatastoreApiHelper$1.convertException(DatastoreApiHelper.java:127)
at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:97)
at com.google.appengine.api.datastore.Batcher$ReorderingMultiFuture.get(Batcher.java:115)
at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:89)
at com.googlecode.objectify.impl.ResultAdapter.now(ResultAdapter.java:34)
at com.googlecode.objectify.util.ResultWrapper.translate(ResultWrapper.java:22)
at com.googlecode.objectify.util.ResultWrapper.translate(ResultWrapper.java:10)
at com.googlecode.objectify.util.ResultTranslator.nowUncached(ResultTranslator.java:21)
at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
at teammates.storage.api.EntitiesDb.putEntities(EntitiesDb.java:139)
at teammates.storage.api.AccountsDb.putEntities(AccountsDb.java:20)
at teammates.logic.core.DataBundleLogic.persistDataBundle(DataBundleLogic.java:100)
at teammates.logic.api.Logic.persistDataBundle(Logic.java:1338)
at teammates.ui.webapi.CreateAccountAction.importDemoData(CreateAccountAction.java:77)
at teammates.ui.webapi.CreateAccountAction.execute(CreateAccountAction.java:37)
at teammates.ui.webapi.CreateAccountAction.execute(CreateAccountAction.java:26)
at teammates.ui.webapi.WebApiServlet.invokeServlet(WebApiServlet.java:93)
at teammates.ui.webapi.WebApiServlet.doPost(WebApiServlet.java:47)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)

Now that I know this, I will use this feature for smaller batches in future. I've created batches of 5-10 before, without such a problem. Larger batch sizes are rare anyway.

However, it got me thinking. Perhaps it is better to send these requests sequentially rather than in parallel (if it doesn't require a complicated change). The operation itself is not time sensitive and we don't want to spin up new instances just to support this occasional operation. IIRC, creating a new server instance incurs a non-trivial cost.

**Comment by moziliar** [comment] 2021-03-17 10:15
For sure. Should we examine all the existing parallel client operations and evaluate if they are necessary and whether they will cause race conditions like this?

**Comment by damithc** [comment] 2021-03-17 10:48
A related question: how much work is to control the number of parallel requests? Is it as simple as setting a variable somewhere only or needs rewriting some parts entirely?

**Comment by moziliar** [comment] 2021-03-17 10:52
In this particular case, preliminary discovery shows that it is due to a loop firing async instructor create event in quick succession. Rough thought about tackling it would be to just construct another `createInstructorService` which takes in array of instructors and sequentialize the account creation with single callback `concat`, the one we've been using for result pagination.

**Comment by moziliar** [comment] 2021-03-25 08:45
>A related question: how much work is to control the number of parallel requests? Is it as simple as setting a variable somewhere only or needs rewriting some parts entirely?

Actually in response to this: I suppose we could add a "threadpool" emulator framework to achieve frontend async call throttling. Typescript itself does not really have multithreading concept and is event queue based concurrent, so we have to construct new functions to control number of sync/async api calls.

**Comment by damithc** [comment] 2021-03-25 08:58
> Actually in response to this: I suppose we could add a "threadpool" emulator framework to achieve frontend async call throttling. Typescript itself does not really have multithreading concept and is event queue based concurrent, so we have to construct new functions to control number of sync/async api calls.

Sounds complicated. Is it simpler than it sounds? If not, is there a simpler solution even if not very sophisticated.

**Comment by moziliar** [comment] 2021-03-25 09:01
>Sounds complicated. Is it simpler than it sounds? If not, is there a simpler solution even if not very sophisticated.
Sorry not very well versed in Angular at this point.
Is the expectation a magic knob that could throttle the maximum concurrent api calls from the client page at any given time for any given function using `rxjs`?
What I can think of at **function level** is to convert the observable to promises and just let native async/await handle the synchronization.

**Comment by damithc** [comment] 2021-03-25 09:20
> Perhaps it is better to send these requests sequentially rather than in parallel (if it doesn't require a complicated change).

This was my initial request :-) Is there a simple way to do it?

**Comment by moziliar** [comment] 2021-03-25 09:22
I've opened a [PR](https://github.com/TEAMMATES/teammates/pull/11063) that simply wrap the observable in promise for synchronization. The changes are contained within admin home page.

**Comment by damithc** [comment] 2021-03-25 09:34
> I've opened a [PR](https://github.com/TEAMMATES/teammates/pull/11063) that simply wrap the observable in promise for synchronization. The changes are contained within admin home page.

Nice!

**Comment by wkurniawan07** [comment] 2021-04-12 01:41
Apologies for jumping in late. The real root cause is not the batch size (although the large batch size does help to flesh it out). The real root cause is we are using the exact same google ID for students in sample courses. This is a very harmful design decision: if someone masquerades as e.g. `alice.b.tmms.sampleData` in the production server, we can guarantee the system to be overloaded immediately as this google ID is attached to thousands and thousands of courses.

I don't believe we have any reason to attach any google ID (and fictitious ones, for that matter) for sample courses.

**Comment by damithc** [comment] 2021-04-12 02:17
> I don't believe we have any reason to attach any google ID (and fictitious ones, for that matter) for sample courses.

Let's make the students in the sample course 'unregistered' and see if it helps.

**Comment by wkurniawan07** [comment] 2021-08-06 14:21
Fixed in #11322

**Closed by wkurniawan07** 2021-08-06 14:21 UTC
Labels: p.Medium, a-Performance
