### ISSUE TITLE
page menu in the instructor help page is not working 

### ISSUE THREAD

**Issue by arya177** [TEAMMATES/teammates#12233] opened 2023-03-22 01:12 UTC
V8.24.0

**Problem**  The given links are not taking the user to the mentioned section and 'back to top' link is also not sending the user to the top of the page.

![image](https://user-images.githubusercontent.com/75832766/226718964-70aad599-2f02-482a-bd79-9c0655cb5666.png)
![image](https://user-images.githubusercontent.com/75832766/226719105-159348d0-5469-4425-b2be-cb05362c54a2.png)

**Comment by weiquu** [comment] 2023-03-22 02:28
Hi @arya177, thanks for submitting the issue. However, note that this is a duplicate of #12222 which is already being worked on, so I'll go ahead and close this issue.

**Closed by weiquu** 2023-03-22 02:28 UTC
