### ISSUE TITLE
Student session submission: Rank(recipients) question allow giver to give same rank to multiple options violated

### ISSUE THREAD

**Issue by t-cheepeng** [TEAMMATES/teammates#10578] opened 2020-08-12 11:29 UTC
- **Environment**: V7.0.2 Production

**Steps to reproduce**
1. Make a rank(recipients) question and uncheck `Allow response giver to give the same rank to multiple options`
2. Answer the question giving the same rank to multiple options. Backend accepts the submissions
![image](https://user-images.githubusercontent.com/28994607/90009908-82442100-dcd1-11ea-8121-b3b3db04f676.png)

**Expected behaviour**
Error in submission with error message in modal

**Actual behaviour**
Accepted submission

**Comment by ccyccyccy** [comment] 2020-08-12 11:34
Looks like duplicate of https://github.com/TEAMMATES/teammates/issues/10397?

**Comment by wkurniawan07** [comment] 2020-08-12 11:45
This is a known limitation for rank (recipients).

**Comment by wkurniawan07** [comment] 2020-08-12 13:01
Duplicate of #10397

**Closed by wkurniawan07** 2020-08-12 13:01 UTC
Labels: p.Medium
