### ISSUE TITLE
IntelliJ cannot run failed tests

### ISSUE THREAD

**Issue by gthd** [TEAMMATES/teammates#8740] opened 2018-03-31 09:56 UTC
When I try to run the failed tests in IntelliJ I get the following error:
![issue_running_failed_tests](https://user-images.githubusercontent.com/15031826/38162023-849844ca-34e2-11e8-9c5b-1dd6dee8ba47.PNG)

Has anyone encountered the same problem before and if yes how to solve it ?

**Comment by LuLechuan** [comment] 2018-03-31 14:25
@gthd Hi, just to make sure you have done the following:
1. Go to test.property and specify the directory to your browser
2. Run `npm install` in your terminal as there is a recent update on the dependencies, followed by `npm run build`
3. Run the appengine.
I have not encountered the same issue as you but just to check that the above are not the cause to the issue

**Comment by gthd** [comment] 2018-03-31 14:33
Hi @LuLechuan I checked all three points but the problem still persists.

**Comment by bqnguyen94** [comment] 2018-03-31 21:22
Just curious, if you go the directory using system explorer do you see the file `testng-failed.xml`?

**Comment by whipermr5** [comment] 2018-04-01 05:03
That run config is only for rerunning failed tests that were originally launched from the command line, e.g. `./gradlew ciTests`. IntelliJ already has a built-in function for rerunning failed tests that were launched from within the IDE.

**Comment by LiHaoTan** [comment] 2018-04-01 05:17
I guess for consistency we might want to allow IntelliJ to generate `testng-failed.xml` as well.

@gthd if you want to do this you can go to the run configurations -> Listeners -> Use default reporters.

If anyone is interested in improving this, maybe can refer to https://github.com/TEAMMATES/teammates/pull/7791/commits/5e6fd5ef284418dffe9de92fa67db65bbc37a650

**Comment by gthd** [comment] 2018-04-01 08:15
@bqnguyen94 There is no testing-output folder for some reason
![directory](https://user-images.githubusercontent.com/15031826/38171226-f1cf6850-359d-11e8-8d69-9f597b3da903.PNG)

**Comment by tshradheya** [comment] 2018-05-23 09:07
@LiHaoTan Why was the value of `DEFAULT_REPORTERS` changed to `false` after this commit 5e6fd5e ?

I am thinking of making it `true` so that it becomes stnadardized for IntelliJ

**Comment by LiHaoTan** [comment] 2018-05-24 01:32
@tshradheya actually that's because that commit wasn't merged to master (part of a dropped PR).

Do you want to also link the run config JDK to the project? That way we don't have to change the JDK version in the run config when we change versions.

**Comment by tshradheya** [comment] 2018-05-24 02:05
@LiHaoTan Okay. I have addressed the changes in #8845

**Closed** 2020-08-16 10:38 UTC
Labels: a-Build, a-Testing
