### ISSUE TITLE
Instructor: edit 'Distribute points' questions: make status message span both label and input

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#7899] opened 2017-08-03 04:38 UTC
In the `student feedback edit page`  under the `Distribute points (among recipients)` question, currently, the status message spans only the _input field_.

**Current Behaviour:**
![Sample Image](https://user-images.githubusercontent.com/9383897/28909990-7adf8512-7848-11e7-89d2-fc18270fb0c9.png)

**Expected:**
status message should span both _input label_ and _input field_.

**Comment by whipermr5** [comment] 2017-08-03 04:41
Duplicate of #7876; already fixed in #7879.

**Comment by amarlearning** [comment] 2017-08-03 04:51
I think my `master` branch is not updated 😅

**Comment by amarlearning** [comment] 2017-08-03 07:07
@whipermr5 Just synchronized my `master` branch with the `upstream/master` branch but the message remains unaligned. 

_[screenshot]_
![screenshot from 2017-08-03 12-34-48](https://user-images.githubusercontent.com/9383897/28909937-3758b836-7848-11e7-988a-41fe64600c0e.png)

It should be something like this _[screenshot]_
![screenshot from 2017-08-03 12-36-36](https://user-images.githubusercontent.com/9383897/28909990-7adf8512-7848-11e7-89d2-fc18270fb0c9.png)

**Comment by whipermr5** [comment] 2017-08-03 15:01
@amarlearning I prefer the current behaviour - `above recipients` refers to the `To: ` and the names too, not just the input boxes.

**Comment by amarlearning** [comment] 2017-08-03 15:29
The screenshots that I posted in [this](https://github.com/TEAMMATES/teammates/issues/7899#issuecomment-319887062) comment are from the current behaviour. Either it should be `above recipient` or `input box` but can't both.

**Comment by whipermr5** [comment] 2017-08-03 15:33
I feel the message should span both elements - "distribute 500 points" is related to the input boxes, while "above recipients" is related to the names. It also looks better when it spans both (though I acknowledge that this is subjective).

**Comment by damithc** [comment] 2017-08-03 23:37
Spanning both elements seems ok to me too.

**Comment by amarlearning** [comment] 2017-08-15 14:05
> Spanning both elements seems ok to me too.

@whipermr5 Shouldn't this be an issue then?

**Comment by whipermr5** [comment] 2017-08-15 17:14
It already spans both.

**Comment by amarlearning** [comment] 2017-08-15 17:17
Not in this case

![Sample Image](https://user-images.githubusercontent.com/9383897/28909990-7adf8512-7848-11e7-89d2-fc18270fb0c9.png)

**Comment by whipermr5** [comment] 2017-08-16 10:11
Is that screenshot the current behaviour on master? How do I reproduce it?

**Comment by amarlearning** [comment] 2017-08-16 16:26
> Is that screenshot the current behavior on master?

Yes!

> How do I reproduce it?

Look for any `Distribute points (among recipients) question` in the `Student feedback edit page`

**Comment by whipermr5** [comment] 2017-08-16 16:57
@amarlearning Could you update the issue description?

**Comment by joanneong** [comment] 2017-12-19 07:41
I'll try working on this.

**Comment by joanneong** [comment] 2017-12-20 16:31
While working on this issue, I realised that rank questions have this issue as well:
<img width="674" alt="screen shot 2017-12-21 at 12 29 39 am" src="https://user-images.githubusercontent.com/24493463/34217281-189d33a2-e5e6-11e7-810a-304b55b27b01.png">

Should I raise this as a separate issue, or should I deal with this too along with the constant sum questions? The problems are similar in nature, but the form templates for rank questions and constant sum questions are separate so I'm not too sure.

**Comment by damithc** [comment] 2017-12-21 01:28
> Should I raise this as a separate issue, or should I deal with this too along with the constant sum questions?

Can fix in the same PR.

**Closed** 2018-01-27 06:40 UTC
Labels: a-UIX, d.Contributors, f-Questions, p.Low
