### ISSUE TITLE
Failure of tests  in InstructorCommentsPageUiTest

### ISSUE THREAD

**Issue by tarun14110** [TEAMMATES/teammates#4952] opened 2016-03-09 14:05 UTC
```
org.junit.ComparisonFailure:
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at teammates.test.driver.HtmlHelper.assertSameHtml(HtmlHelper.java:81)
	at teammates.test.driver.HtmlHelper.assertSameHtml(HtmlHelper.java:49)
	at teammates.test.pageobjects.AppPage.verifyHtml(AppPage.java:751)
	at teammates.test.pageobjects.AppPage.verifyHtmlPart(AppPage.java:800)
	at teammates.test.pageobjects.AppPage.verifyHtmlMainContent(AppPage.java:813)
	at teammates.test.cases.ui.browsertests.InstructorCommentsPageUiTest.testActions(InstructorCommentsPageUiTest.java:201)
	at teammates.test.cases.ui.browsertests.InstructorCommentsPageUiTest.allTests(InstructorCommentsPageUiTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

```

**Comment by damithc** [comment] 2016-03-09 14:24
It passed for me when I tested V5.71 on dev server today.

**Comment by wkurniawan07** [comment] 2016-03-09 17:21
@tarun14110 I could not replicate this. Does this happen consistently in your machine?

**Comment by tarun14110** [comment] 2016-03-10 07:19
@wkurniawan07 It was so consistent yesterday, But it is passing today, not able to find the specific reason. I think browser running at background for this test causes failure, as suggested by you in #4949. Or may be some other reason.

**Comment by wkurniawan07** [comment] 2016-03-10 08:51
I highly doubt it. Running in background never causes problem for this test for me. For #4949 I've known for some time that it's caused by running in background due to some JS issue.

**Comment by tarun14110** [comment] 2016-03-10 09:09
May be some other issue. Its running fine now, tried many times. I think we can close this issue.

**Comment by junhaoyap** [comment] 2016-03-10 20:04
Closing as mentioned

**Closed by junhaoyap** 2016-03-10 20:04 UTC
