### ISSUE TITLE
Instructor view student list: incorrect state shown very briefly

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10788] opened 2020-10-15 02:15 UTC
v7.3.1

When an instructor views the student list of a course, this is what happens:
1. spinners appear for a while, as expected
1. a warning message appears for a fraction of a second (presumably, the one about the course not having any students? I wasn't able to read it)
1. student list is loaded

While not a big problem, is it possible to avoid 2?

Let me know if cannot reproduce. I can record a gif.

A similar thing happens when an instructor loads the 'add session' page, this time with some error messages.
![image](https://user-images.githubusercontent.com/1673303/96068594-f74cf600-0ece-11eb-8afa-03c3793219a8.png)

Not sure if both are caused by a similar reason or they are different things.

**Comment by madanalogy** [comment] 2020-10-16 03:44
I can't seem to reproduce either errors, might have to do with scalability (i.e. loading a lot of sessions / students). 

For the first portion it might be that because the `InstructorStudentListPageComponent` is instantiated with `isLoadingCourses = false` though the value is set to `true` on init.

Second portion likely has to do with the `tm-session-edit-form` expanding before `loadCandidatesCourse()` is done in the `InstructorSessionsPageComponent`.

**Comment by damithc** [comment] 2020-10-16 05:15
Perhaps boolean flags are inadequate as there are three states involved i.e., unknown/pending, success, failure ?

**Comment by jianhandev** [comment] 2020-12-11 12:57
> Second portion likely has to do with the `tm-session-edit-form` expanding before `loadCandidatesCourse()` is done in the `InstructorSessionsPageComponent`.

Based on the code, the red error message will appear when the length of the `courseCandidates` array is 0. 

Since the `courseCandidates` array is by default initialized to an empty array, the error message will appear for a split second before `loadCandidatesCourse()` fetches the actual data from the server.

I believe this can be fixed by introducing a boolean flag (as mentioned by @damithc) that gets updated once data fetching from the server is complete.

**Comment by jianhandev** [comment] 2020-12-12 05:03
I've tried to fix the above two issues separately in two of my PRs (#10872 and #10871)

**Closed** 2020-12-25 01:59 UTC
Labels: a-UIX, c.Bug, help wanted, p.Low, t-Angular
