### ISSUE TITLE
stuck on 85% and got 404 error when setting up backend

### ISSUE THREAD

**Issue by hanzili** [TEAMMATES/teammates#11889] opened 2022-06-30 16:20 UTC
- **Commit SHA:** ade11587167a06863f403e7a0b23b8d8bef9ac67
- **Operating System:** Windows11
- **JDK Version:** 11.0.15.1
- **Node.js Version:** v16.15.1
- **Firefox / Chrome Version (if applicable):** Version 103.0.5060.66

**What I was trying to do / What I need help with**
Hello, I am following the development guidelines and trying to manage the backend server.

When executing `gradlew serverRun`, the progress bar stuck on 85%, and when I try to access `http://localhost:8080/`, I got a 404 error.
<img width="403" alt="Screenshot 2022-06-30 121334" src="https://user-images.githubusercontent.com/96609857/176726865-0437a417-57bd-4e31-beec-7e2c7861618a.png">
<img width="329" alt="Screenshot 2022-06-30 121524" src="https://user-images.githubusercontent.com/96609857/176727121-bf8607ed-f842-4c67-a1a0-92e40304f7ad.png">

PID 12496 corresponds to the backend server, it is in the state of LISTENING. I am not sure if that is as expected.

<img width="447" alt="Screenshot 2022-06-30 171040" src="https://user-images.githubusercontent.com/96609857/176779033-7962568c-f2d7-4296-80b4-f494a3863eb3.png">

**Attempts to resolve the problem**
I have finished all the steps in setting up the development environment.
I have tried to run the local datastore server(using solr or docker) and full-text search service(using quickstart script) locally or directly using the docker, but neither of them works. 
Also, I tried to run the backend server while the frontend server is running or not, but the problem is still there.

**Comment by ErnestCuong** [comment] 2022-06-30 18:33
Apparently, the 85% progress is the intended behavior. [Issue 11638](https://github.com/TEAMMATES/teammates/issues/11638) helped me resolve the problem.

So basically, you need 2 cmd windows, one running frontend and one running backend. Here are my steps but since I am new here I am not sure if this is the correct way of starting the dev server:
- `./gradlew generateTypes` / `gradlew.bat generateTypes` then `npm run start` in terminal 1
- `./gradlew runDatastoreEmulator` / `gradlew.bat runDatastoreEmulator` then `./gradlew serverRun &` / `gradlew.bat serverRun &` in terminal 2
- Login with this email `app_admin@gmail.com`. Quit and access the dev server again if it says you don't have permission but don't log out.

**Comment by hanzili** [comment] 2022-06-30 21:05
> Apparently, the 85% progress is the intended behavior. [Issue 11638](https://github.com/TEAMMATES/teammates/issues/11638) helped me resolve the problem.
> 
> So basically, you need 2 cmd windows, one running frontend and one running backend. Here are my steps but since I am new here I am not sure if this is the correct way of starting the dev server:
> 
> * `./gradlew generateTypes` / `gradlew.bat generateTypes` then `npm run start` in terminal 1
> * `./gradlew runDatastoreEmulator` / `gradlew.bat runDatastoreEmulator` then `./gradlew serverRun &` / `gradlew.bat serverRun &` in terminal 2
> * Login with this email `app_admin@gmail.com`. Quit and access the dev server again if it says you don't have permission but don't log out.

Thanks for your reply! What you said is actually what I have done exactly, but I am not able to access `localhost:8080`, as it returns a 404 error. 

In that case, I am not able to log in with `app_admin@gmail.com` through the backend.

I tried to log in with `app_admin@gmail.com` from `http://localhost:4200/web/front/home`, but the page just refreshes and nothing else happens.
<img width="960" alt="Screenshot 2022-06-30 170326" src="https://user-images.githubusercontent.com/96609857/176777980-b9071bf9-f11c-41d0-af46-27f02e184b4a.png">

**Comment by zhaojj2209** [comment] 2022-07-02 06:59
> I tried to log in with `app_admin@gmail.com` from `http://localhost:4200/web/front/home`, but the page just refreshes and nothing else happens.

@hanzili Please refer to the following snippet in the [Development Guidelines](https://teammates.github.io/teammates/development.html#logging-in-to-a-teammates-instance) for instructions on how to log in as administrator:

> Go to any administrator page, e.g `/web/admin/home`. You may be prompted to log in. You will be granted access only if your account has admin permission as defined in `build.properties`.

**Comment by sivayogasubramanian** [comment] 2022-07-02 11:15
>  and when I try to access http://localhost:8080/, I got a 404 error.

`http://localhost:8080` only works when you build the frontend first. Try `npm run build` first then go there again.

**Comment by zhaojj2209** [comment] 2022-07-30 06:04
Closing as queries have been addressed.

**Closed by zhaojj2209** 2022-07-30 06:04 UTC
