### ISSUE TITLE
NPE while adjusting submissions

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4520] opened 2015-10-23 10:05 UTC
teammates.logic.automated.FeedbackSubmissionAdjustmentAction execute: Error encountered while adjusting feedback session responses of Cup of tea in course : JV_GROUPS_OF_2 : null
TEAMMATESLOG|||feedbackSubmissionAdjustmentWorker|||Servlet Action Failure|||true|||Unknown|||Unknown|||Unknown|||Unknown|||<span class="text-danger">Servlet Action failure in feedbackSubmissionAdjustmentWorker<br>class java.lang.NullPointerException: 
java.lang.NullPointerException
	at teammates.logic.core.FeedbackResponsesLogic.updateFeedbackResponseForChangingSection(FeedbackResponsesLogic.java:597)
	at teammates.logic.core.StudentsLogic.adjustFeedbackResponseForEnrollments(StudentsLogic.java:645)
	at teammates.logic.automated.FeedbackSubmissionAdjustmentAction.execute(FeedbackSubmissionAdjustmentAction.java:83)
	at teammates.logic.automated.FeedbackSubmissionAdjustmentWorkerServlet.doGet(FeedbackSubmissionAdjustmentWorkerServlet.java:12)
	at teammates.logic.automated.WorkerServlet.doPost(WorkerServlet.java:31)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:147)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:457)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
	at java.lang.Thread.run(Thread.java:745)
<br>{courseid::JV_GROUPS_OF_2, enrollmentdetails::[
  {
    "updateStatus": "MODIFIED",
    "course": "JV_GROUPS_OF_2",
    "email": "abc@hotmail.com",
    "oldTeam": "Team Alpha",
    "newTeam": "Alpha team on Friday",
    "oldSection": "Tut Group 1",
    "newSection": "Class 101"
  },
  {
    "updateStatus": "NEW",
    "course": "JV_GROUPS_OF_2",
    "email": "def@port.ac.uk",
    "newTeam": "Alpha team on Friday",
    "newSection": "Class 101"
  },
  {
    "updateStatus": "MODIFIED",
    "course": "JV_GROUPS_OF_2",
    "email": "abc@gmail.com",
    "oldTeam": "Beta people",
    "newTeam": "Beta team on Friday",
    "oldSection": "Tut Group 1",
    "newSection": "Class 101"
  },
  {
    "updateStatus": "MODIFIED",
    "course": "JV_GROUPS_OF_2",
    "email": "xyz@live.co.uk",
    "oldTeam": "Beta people",
    "newTeam": "Beta team on Friday",
    "oldSection": "Tut Group 1",
    "newSection": "Class 101"
  }
], fsname::Cup of tea}</span>|||/feedbackSubmissionAdjustmentWorker|||Unknown20151023172627818

**Comment by wkurniawan07** [comment] 2016-02-17 16:50
Duplicate of #4769 (or rather the other way around), closing this one as it's easier to navigate to the more current one.

**Closed by wkurniawan07** 2016-02-17 16:50 UTC
Labels: c.Bug, f-Submissions, p.High
