### ISSUE TITLE
Notifications box overlaps with the page menu in the instructor help page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12010] opened 2022-12-22 18:15 UTC
V8.19.2, production

Problem: see screenshot below
![image](https://user-images.githubusercontent.com/1673303/209199513-84e5a932-801b-4b59-8a04-791a49f35278.png)

**Comment by evank21** [comment] 2022-12-27 22:35
How can i be assigned this issue?

**Comment by ziqing26** [comment] 2022-12-29 09:30
Hi @evank21 feel free to take this!

**Comment by JoshPaulWalsh** [comment] 2023-01-03 21:06
Hey @evank21, are you still working on this? If not I'd like to solve it.

**Comment by PVenkatArvind** [comment] 2023-01-12 14:38
Greetings!! 
I am looking to gain insight about the same and is the solution padding  ?? 
I'm curious on how to
<img width="769" alt="Team" src="https://user-images.githubusercontent.com/79320301/212095224-97cac3ce-2399-4f0b-8336-044765a081c0.png">
 fix it

**Comment by PVenkatArvind** [comment] 2023-01-12 14:42
Greetings!!
can you please provide an insight regarding on why I'm  unable to see the same as provided in the issue  and does padding solve the issue  ??
I'm curious on how to fix it , I don't see the same as the issue 
This is what is displayed 
<img width="769" alt="Team" src="https://user-images.githubusercontent.com/79320301/212095607-e2b5b935-e2bf-4636-acbf-05e67f06da29.png">

**Comment by zhaojj2209** [comment] 2023-01-14 06:01
> Greetings!! can you please provide an insight regarding on why I'm unable to see the same as provided in the issue and does padding solve the issue ?? I'm curious on how to fix it , I don't see the same as the issue This is what is displayed

Notifications are only displayed to registered users. The issue is present when accessing the help page from the instructor home page when logged in (`/web/instructor/help` instead of `/web/front/help/instructor`).

**Comment by PVenkatArvind** [comment] 2023-01-14 06:30
Thanks a lot @zhaojj2209

**Comment by Palakkgoyal** [comment] 2023-01-22 17:15
I want to contribute to this. Have you completed?

**Comment by JoshPaulWalsh** [comment] 2023-01-22 23:02
> I want to contribute to this. Have you completed?

I got busy so you can finish it!

**Comment by Palakkgoyal** [comment] 2023-01-24 09:44
@damithc Do you like it know or any other change you would suggest.
![Screenshot (368)](https://user-images.githubusercontent.com/116902573/214259338-57de6ccc-b84b-4990-b791-c7416461cfd9.png)

**Comment by damithc** [comment] 2023-01-24 09:48
@Palakkgoyal the screenshot looks fine.

**Comment by Palakkgoyal** [comment] 2023-01-24 09:49
@damithc At some point the navigation menu got somewhat messed up according to me. Would you like to change it?
![Screenshot (369)](https://user-images.githubusercontent.com/116902573/214260086-20d52841-bf8c-4ba7-b931-5bc9b79e775d.png)
After 940px of width the page menu got disappear. Should I add this after 940px, if you want otherwise I will not change that.

**Comment by damithc** [comment] 2023-01-24 09:56
> @damithc At some point the navigation menu got somewhat messed up according to me. Would you like to change it?
> ![Screenshot (369)](https://user-images.githubusercontent.com/116902573/214260086-20d52841-bf8c-4ba7-b931-5bc9b79e775d.png)
> After 940px of width the page menu got disappear. Should I add this after 940px, if you want otherwise I will not change that.

@Palakkgoyal Is this a problem introduced by your fix for the other problem? In that case you need to fix it as well. But if not, submit it as a separate issue.

**Comment by Palakkgoyal** [comment] 2023-01-24 10:35
No, its not generated by me.

**Comment by sumit970** [comment] 2023-02-15 20:12
> V8.19.2, production
> 
> Problem: see screenshot below
> ![image](https://user-images.githubusercontent.com/1673303/209199513-84e5a932-801b-4b59-8a04-791a49f35278.png)
> 

Hey pleasure assign this issue to me

**Comment by Palakkgoyal** [comment] 2023-03-16 13:27
https://teammatesv4.appspot.com/web/front/home

**Comment by BikcromBiswas** [comment] 2023-03-16 16:16
> https://teammatesv4.appspot.com/web/front/home

Thanks palak

**Comment by BikcromBiswas** [comment] 2023-03-16 16:21
I am not getting the issue is this issue is solved can anyone help me i am a newbie in open source

**Comment by samuelfangjw** [comment] 2023-03-16 16:36
> I am not getting the issue is this issue is solved can anyone help me i am a newbie in open source

Hi @BikcromBiswas, while we welcome your contribution, we do not have the resources to guide every contributor personally. The [developer docs](https://teammates.github.io/teammates/) as well as the issue description should be more than enough to get started. If you have any specific questions, please post a help request in the discussions page.

**Comment by Palakkgoyal** [comment] 2023-03-17 13:58
@BikcromBiswas I checked that the issue is solved. But don't lose heart, go to the website check if you can add any extra functionality into it and make the site look even better. Create a new issue on that and work on it.

**Comment by samuelfangjw** [comment] 2023-03-17 15:10
This issue is still unresolved, all first time contributors are welcome to start work on this.

**Comment by noreddinelam** [comment] 2023-03-18 22:03
@samuelfangjw i am new here and i want to give it try.

**Comment by techMedMau** [comment] 2023-05-13 22:10
Hi, does this issue been fixed? May I work on this one?

**Comment by domlimm** [comment] 2023-05-14 01:59
@techMedMau Feel free to submit a PR for this issue 👍🏻

**Closed** 2023-05-24 13:33 UTC
Labels: a-UIX, p.Low, good first issue
