### ISSUE TITLE
Instructor: view results: instructor should be able to see responses given to him even if he is also a student

### ISSUE THREAD

**Issue by chowyb** [TEAMMATES/teammates#5770] opened 2016-06-30 04:13 UTC
When an instructor is also registered as a student under the same email, if the instructor does not have permissions to view responses for the section that his student account is under, he will not be able to see responses that have been directed to him as an instructor.

A way to replicate this bug is to add a new instructor as an admin, so that the sample course and feedback sessions are created. Then, login as the new instructor and deny yourself access to view sessions for Tutorial Group 2 (via "Custom" instructor settings). One can then check that for "Session with different question types", no responses can be seen for Question 3, although both responses were directed at the instructor.

As the instructor/student case is unlikely to occur in practice however, this may not be a priority to fix.

The method in question is `FeedbackSessionsLogic.isResponseVisibleForUser()`.

**Comment by damithc** [comment] 2016-06-30 04:39
Kudos for detecting the bug :+1:

**Comment by madanalogy** [comment] 2020-01-21 03:48
Hello I would like to work on this thank you.

**Comment by xpdavid** [comment] 2020-01-21 03:49
@madanalogy Note that the result page is not migrated yet in V7.

**Comment by wkurniawan07** [comment] 2020-09-20 07:59
Closing as the diagnosis of the problem is wrong. This has nothing to do with instructor also being a student. If the instructor has no permission to view a section's responses, then that rule must be respected regardless of who the responses are meant for.
The linked issue has also been fixed.

**Closed by wkurniawan07** 2020-09-20 07:59 UTC
Labels: a-AccessControl, p.Medium
