### ISSUE TITLE
Observer cannot view session results

### ISSUE THREAD

**Issue by niqiukun** [TEAMMATES/teammates#10613] opened 2020-08-16 06:03 UTC
To view session results, the instructor needs "Sessions: Submit Responses and Add Comments" permission, which should not be the case. As a result, observer cannot view session results. They will be prompted that "You are not authorized to access this resource" upon entering session results page. The result csv can be properly downloaded.

**Comment by madanalogy** [comment] 2020-08-17 03:45
I think this is because the session results page allows users to moderate responses and add comments to student responses. Resolving this would require refactoring the results page to load those options based on user privileges.

I don't think the priority should be high, maybe medium at best, since they can still access session results (via csv).

**Comment by niqiukun** [comment] 2020-08-17 03:55
> I think this is because the session results page allows users to moderate responses and add comments to student responses. Resolving this would require refactoring the results page to load those options based on user privileges.

Front-end side, we can disable the buttons if the don't have the permission? Actually even if there is no front-end check, the back-end should reject users' attempt to add comments/moderations. Right now it seems that it's a back-end bug because the session results cannot be displayed at all.

> I don't think the priority should be high, maybe medium at best, since they can still access session results (via csv).

Personally I didn't expect that the csv can be downloaded normally until I intentionally tried the feature. Users can hardly notice it unless they have the intent to download csv.

**Comment by madanalogy** [comment] 2020-08-17 04:29
> Right now it seems that it's a back-end bug because the session results cannot be displayed at all.

This shouldn't be the case, but I get what you mean regarding the impression it gives.

**Comment by niqiukun** [comment] 2020-08-17 05:44
> > Right now it seems that it's a back-end bug because the session results cannot be displayed at all.
> 
> This shouldn't be the case, but I get what you mean regarding the impression it gives.

When logged in as observer, session endpoint (`/session`) with intent `INSTRUCTOR_RESULT` returns response 403. This must be a backend issue?

**Comment by madanalogy** [comment] 2020-08-17 06:28
> When logged in as observer, session endpoint (/session) with intent INSTRUCTOR_RESULT returns response 403. This must be a backend issue? You can see the error printed in console.

This is because calling `GET` on the `/session` endpoint with `INSTRUCTOR_RESULT` intent checks whether the user has the `INSTRUCTOR_PERMISSION_SUBMIT_SESSION_IN_SECTIONS` permission:

https://github.com/TEAMMATES/teammates/blob/09a4bfec1884d4a099fecb422fcce4ec6879d9ce/src/main/java/teammates/ui/webapi/action/GetFeedbackSessionAction.java#L38-L42

I'm not exactly sure why it was designed this way, maybe it's to do with the actions an instructor can take in the session results page? Either way, while I do agree that `INSTRUCTOR_PERMISSION_VIEW_SESSION_IN_SECTIONS` might be a more appropriate privilege requirement, we should investigate the impact of this less restrictive permission first.

Maybe one of the project mentors can help shed some light on this design choice? @xpdavid @wkurniawan07

**Comment by madanalogy** [comment] 2020-08-17 06:42
>I'm not exactly sure why it was designed this way

One reason I can think of is that the preset `Observer` role was never intended to have access to session results. This would then mean that access to sessions results csv becomes a problem.

**Comment by madanalogy** [comment] 2020-08-17 10:42
@niqiukun It seems you were right, the backend is misconfigured as it is applying a more restrictive permission scope than necessary. If anyone intends to work on this, see https://github.com/TEAMMATES/teammates/issues/10613#issuecomment-674686711

**Closed** 2020-09-07 02:59 UTC
Labels: a-AccessControl, p.High
