### ISSUE TITLE
CONTRIBUTING.md links to the old contributor orientation guide

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/teammates#5539] opened 2016-06-03 11:20 UTC
The one used now is in the `devdocs/` folder.

**Comment by damithc** [comment] 2016-06-04 03:42
Let's fix this soon. Removing `firstTimers` label because this is not a low priority issue.

**Comment by damithc** [comment] 2016-07-09 12:10
@wkurniawan07 this should be closed, right?

**Comment by chowyb** [comment] 2016-07-09 14:10
@damithc the merged PR referencing this issue is on the contributor's own fork, and not on our repository. The issue is still not fixed yet.

**Comment by damithc** [comment] 2016-07-09 14:53
I see. It's a high priority issue. Can submit a quick fix?

**Closed** 2016-07-10 04:08 UTC
Labels: a-DevOps, m.Aspect, p.High
