### ISSUE TITLE
Instructor viewing activity logs: server error

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11497] opened 2021-12-09 14:59 UTC
A user reported this error while using the unreleased `https://teammatesv4.appspot.com/web/instructor/logs` feature

![image](https://user-images.githubusercontent.com/1673303/145419334-9c4a7a22-35aa-46ca-a731-5280e40e9159.png)

I was able to replicate it myself.

The course has only 12 students. But the user has over 100 active courses.

This is the likely related error I found in the log for the matching period:
>RejectedExecutionException caught by WebApiServlet: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4567e0e0[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@39dbf1f4[Wrapped task = io.grpc.internal.SerializingExecutor@6f0f74ce]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@5a72bfe8[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 9]

**Comment by damithc** [comment] 2021-12-18 04:12
Another case: 208 students, 3 students per team, 3 questions, 1 session. Wasn't able to load audit logs of one student after several tries. The instructor has only 3 courses.

Log message:
>RejectedExecutionException caught by WebApiServlet: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@65c8bfab[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@461eff27[Wrapped task = io.grpc.internal.SerializingExecutor@60fd0b9]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1cbe78b9[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 9]

**Comment by halfwhole** [comment] 2022-02-26 17:30
To follow up on this, do any users continue to face this issue? Are there also recent examples of these server errors that we can look at (maybe in the maintainer logs) to figure out what went wrong?

**Comment by damithc** [comment] 2022-02-26 18:51
> To follow up on this, do any users continue to face this issue? Are there also recent examples of these server errors that we can look at (maybe in the maintainer logs) to figure out what went wrong?

The feature is not visible to users. These errors were reported the few times I gave the link to a few users. I stopped giving the link to users after that. I don't think we have the logs for those cases anymore.

I can reproduce the error by searching for a student in CS2103 course (278 students) for a 30 day period. So, I suspect it is a problem of scale. But I don't know if it is affected by the number of log entries related to the course or it is also affected by the _total_ number of log entries in the system for that period (i.e., including those created by other courses).

**Comment by halfwhole** [comment] 2022-02-27 06:57
Can reproduce this occasionally on both production and staging, with dummy courses and a 30 day search period, so it's unlikely to be related to the size of the course/session, nor the total number of log entries in the course/session/system.

Further details: source location is pinpointed to line 210 of `GoogleCloudLoggingService`, i.e. `entries.iterateAll()`. Can investigate into this further.

**Comment by t-cheepeng** [comment] 2022-03-09 09:21
Also managed to reproduce with one course and about 60 matching logs over 30 days.

@halfwhole 
In `GoogleCloudLoggingService`, line 345 - 349, there is a `logging.close()` method call. Once I removed those lines, the server errors were no longer present. Could you help to comment out those lines and re-run the code on staging as a double check (make sure that it's not a fluke on my side)? 

I think the issue arises when the number of audit logs fetched go past a page size and when doing `entries.iterateAll()`, it lazily fetches the next page which then gets rejected as the logging service was closed prematurely. The remaining methods in this class likely did not face the issue as the number was small enough to fit into a page or there was a specification of the page size.

**Comment by wkurniawan07** [comment] 2022-03-10 01:15
On a general note, you almost always never want to skip closing resources. At the very least, it's going to cause memory/handle leaks, and on the other extreme it can be abused for DoS or fork bomb attack.

**Comment by halfwhole** [comment] 2022-04-09 14:39
Am unable to reproduce this error on my staging server this week (the behaviour is frustratingly indeterministic), but the above sounds right to me. Will try a solution that performs the iterate all before calling `logging.close()` and see if that will address the issue

**Closed** 2022-04-10 15:53 UTC
Labels: s.ToInvestigate

**Comment by wkurniawan07** [comment] 2022-04-11 16:35
@damithc any reoccurrences here?

**Comment by damithc** [comment] 2022-04-11 17:46
> @damithc any reoccurrences here?

No reports from users, but then, I haven't told any users about this feature since we ran into this error.

I tried the feature just now. No error  5/5 times I tried. That's good news. Other info:
A search for 7 days took about 1.5-2 minutes.
A search for 30 days took about 3-4 minutes.
