### ISSUE TITLE
instructorFeedbackResponseCommentsLoad empty div has empty style attribute

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/teammates#3982] opened 2015-07-15 08:28 UTC
Self explanatory, just remove it and fix the test cases

**Comment by belyabl9** [comment] 2016-03-02 17:59
Hi,

Could you assign to me this issue as my [FirstTimers] ?

Thanks in advance

**Comment by kanghj** [comment] 2016-03-03 08:57
@belyabl9, you don't need to be assigned to work on this, just submit a pull request when you are ready, or if you want further discussion.

**Comment by belyabl9** [comment] 2016-03-03 11:11
Thanks for the explatation. And one more question:
The issue is opened on 15 Jul 2015, so could somebody approve that is is still actual ?
As I see, mentioned <div> is not empty. Should I remove the whole element or just empty "style" attribute ?

**Comment by kanghj** [comment] 2016-03-04 01:18
@belyabl9, I believe just removing the empty 'style' attribute is enough for this issue.

**Closed** 2016-03-07 10:22 UTC
Labels: a-DevOps, d.FirstTimers, f-Comments, p.Low
