### ISSUE TITLE
Dev docs: correct the link to airbnb JavaScript Style Guide

### ISSUE THREAD

**Issue by AnaghHegde** [TEAMMATES/teammates#6343] opened 2017-01-13 07:36 UTC
The [docs](https://docs.google.com/document/d/1gZ6WG6HBTJYHAtVkz9kzi_SUuzfXqzO-SvFnLuag2xM/pub?embedded=true) which contains information about the JavaScript coding standard  has a link to airbnb website and its no longer valid.  

When i did a little search for the airbnb Javascript Style Guide, in their github page it says ES5 deprecated.   
![screenshot 47](https://cloud.githubusercontent.com/assets/12005551/21921753/78d31466-d990-11e6-8a31-c3e5afe11d38.png)

But when i opened the link it works fine. The [link](https://github.com/airbnb/javascript/blob/master/README.md) to their page and link to the deprecated [ES5](https://github.com/airbnb/javascript/tree/es5-deprecated/es5) page.

**Comment by damithc** [comment] 2017-01-13 08:46
May be we can use https://github.com/airbnb/javascript as the JS standard? The alternative is to use https://google.github.io/styleguide/javascriptguide.xml

@junhaoyap @wkurniawan07

**Comment by wkurniawan07** [comment] 2017-01-13 08:52
The first one won't work; it's tailored for ES6.

The ES5 guide was marked by them as "deprecated" because Airbnb doesn't write ES5 anymore (I wonder when we could follow suit...), but is still a good reference for ES5-based developers. The Google one is also a good reference. No preference from me on which one out of these two should be used.

**Comment by li-kai** [comment] 2017-01-16 07:35
Is there any interest in migrating to ES6? I can set the transpilation for es6 to es5. The benefits would be cleaner code (especially `let` and `const`), up to date airbnb's eslint settings and minification of js scripts for use in production.

**Comment by wkurniawan07** [comment] 2017-01-17 08:20
If you ask me, I'm all for ES6 instead of ES5 :p

The reason why we don't is (1) lack of browser support, especially older browsers, particularly when we look at our target users (spoken like a true product manager!), and (2) we do not have automated JS task runner yet. If we can introduce build tools such as grunt/gulp/other Node task helpers to automate stuffs such as transpilation, minification, source map generator, etc., then we definitely should go down the ES6 path.

Long answer short: yes, there is an interest (at least from me).

**Comment by li-kai** [comment] 2017-01-17 08:47
Issue 1 is addressable, we can write in es6 then transpile back to the lowest version of IE that we support (IE 9). Addressing issue 1 would meaning solving 2 too. I'm well versed in this area 😄

**Comment by junhaoyap** [comment] 2017-01-17 10:10
Agreed, we can use Babel for transpilation, minification is not hard and if we are doing that, we might as well start introducing Node and package managers and that gives us a few benefits:

1. ```let``` and ```const``` is block scoped and that allows bridging easily from other languages, ```const``` is also immutable unlike our current convention

2. We can remove all our polyfills, Babel takes care of polyfills whenever necessary

There are more and these are just the more obvious benefits and it will basically help to prune our JavaScript code base along with making it more obvious / maintainable and helper functions that comes with ES6 that makes more sense than vanilla JavaScript

**Comment by damithc** [comment] 2017-01-17 11:17
1. How extensive will be the changes to existing code? If changes are needed, can it be incremental? Increasing JS code coverage is one of the pending tasks not done yet. Need to consider the risks of refactoring not-covered code.
2. What changes are needed to the workflow. e.g. do devs need to run some additional tasks after they modify JS files?

**Comment by wkurniawan07** [comment] 2017-01-17 11:25
ES6 are by design more testable, so it goes hand-in-hand with that issue of increasing coverage. I pretty much welcome a change to the ENTIRE code base (which I actually intended to do but have not found the time yet, given there are so many things to clean up in the Java side), but of course has to be incremental.

[Drupal has done a similar upgrade before](https://www.drupal.org/node/2809281).

**Comment by li-kai** [comment] 2017-01-17 11:31
1. Refactoring can go hand-in-hand. My external project - webpack, is also doing the same thing. Write more tests for those with low coverage, then refactor to es6.

2. There will be additional changes to the work flow. It will require building the js files, but these can integrated to the gradle builds.

I'm working on a PR for this build step.

**Comment by damithc** [comment] 2017-01-17 11:39
> Refactoring can go hand-in-hand. My external project - webpack, is also doing the same thing. Write more tests for those with low coverage, then refactor to es6.

It's less risky if the refactoring can be done incrementally, as opposed to a massive change to the entire code base at once. To confirm, we can switch to ES6 with little/no changes to existing code, and then migrate code in piece-meal fashion? If yes, do you think you can finish the entire migration within this semester? It's not necessary to do so; I'm just trying to gauge the effort required.

> There will be additional changes to the work flow. It will require building the js files, but these can integrated to the gradle builds.

ATM devs don't use gradle for local testing. After this migration, they have to? Or can they skip the additional step for local testing (provided their browser supports ES6)?

**Comment by li-kai** [comment] 2017-01-17 11:55
> To confirm, we can switch to ES6 with little/no changes to existing code, and then migrate code in piece-meal fashion?

Yes, ES6 code is backwards compatible with ES5. Writing in ES5 is still acceptable, but provides less rigidity and safety as compared to ES6.

> If yes, do you think you can finish the entire migration within this semester? It's not necessary to do so; I'm just trying to gauge the effort required.

In addition to the tests, I would say it is possible within this semester but this would mean not working on other issues.

> ATM devs don't use gradle for local testing. After this migration, they have to? Or can they skip the additional step for local testing (provided their browser supports ES6)?

If no changes were made to the javascript files, then no, they would not have to build before testing. Building is also not necessary for development provided their browser supports ES6, which as of this moment, all modern browsers support at least 90% of ES6 features.

**Comment by damithc** [comment] 2017-01-17 12:06
Based on what I've heard so far, I have no objections in principle. I'll leave the final decision to @wkurniawan07 as we need to consider other restructurings that is going on (we don't want to change too many things at the same time) and the priority of manpower needs which he is more familiar with. (@wkurniawan07 On a related note, we should not stockpile too many changes in one release, especially if we end up releasing all of it in the middle of the peak period)

> Accounting for the tests, I would say it is possible within this semester but this would mean not working on other issues.

Once you have done enough examples for others to follow, you can package some of the remaining work as standalone issues that can be left for others to do under your oversight.

**Comment by wkurniawan07** [comment] 2017-01-18 07:20
@li-kai if you can find at least 2 more interested people from the CS3282 group, that would be sufficient. One thing for sure, I will lend my help as well; I've been wanting to do this, time constraint being my only opponent.

**Comment by paradite** [comment] 2017-01-24 15:00
I think migrating to ES6 would be an interesting and suitable task for CS3282.

**Comment by chowyb** [comment] 2017-05-26 07:13
Note that as the document being referred to in this issue is on Google Docs, this cannot be fixed by submitting a GitHub PR. Instead, a committer should be able to edit the file on Google Drive directly.

Due to the migration of JS files to ES6, it should now be possible to use the link to their ES6 guide: https://github.com/airbnb/javascript/blob/master/README.md.

**Comment by damithc** [comment] 2017-05-26 07:23
Updated the GoogleDoc.

**Comment by wkurniawan07** [comment] 2017-06-16 10:05
No longer relevant.

**Closed by wkurniawan07** 2017-06-16 10:05 UTC
Labels: a-CodeQuality, a-Docs, p.Medium, t-JS
