### ISSUE TITLE
"Countries and regions" instead of "countries" in the home page.

### ISSUE THREAD

**Issue by puzrat** [TEAMMATES/teammates#7099] opened 2017-04-11 14:50 UTC
### The old issue was #7093 . 
@thenaesh I wasn't making and will not make any joke on this. What you did (closing it without any comments or commits) are considered as a serious insult. Github is a great open source community. What you do here is reading the enhancement description not my id and photo.

Just in case you are not aware of the **One China Policy** , it is stated clearly in the *Preamble* of the **CONSTITUTION OF CHINA**: ["Taiwan is part of the sacred territory of the People’s Republic of China."](http://www.npc.gov.cn/englishnpc/Constitution/2007-11/15/content_1372962.htm)

**Comment by thenaesh** [comment] 2017-04-11 14:58
The internal politics of a specific country have no place in an open, international community like TEAMMATES. Any further issue of this nature opened will lead to this account being banned.

**Comment by null09264** [comment] 2017-04-11 15:15
@thenaesh This is non-sense. May I ask does your international community include China? May I ask does an international community need to follow the laws and regulations? **One China Policy** have to be admitted before PRC establishes diplomatic relations with any countries, which includes India and Singapore. Apparently, it is not the internal politics you have referred.

I think the project mentor Prof @damithc need an acknowledgement on this. And I would like @thenaesh to apologise formally here in the discussion threads of this issue and #7093 .

P.S. I'm posting using my main account now. The issue was intended to make TEAMMATE more comprehensive in terms of its expressions. All I would expect was a two-word fix and I never wanted to raise a political argument here. Surprisingly, the way how the team member responded was extremely rude.

**Comment by damithc** [comment] 2017-04-11 16:10
The countries in the home page is based on the countries declared by users. We'll look into rephrasing it so as to avoid any controversy.

**Comment by wkurniawan07** [comment] 2017-04-11 18:15
@null09264

Hi Jinghan,

Firstly, I'd like to apologize that this situation had to happen. Allow me to give some clarifications.

> May I ask does your international community include China?

We'd like to include as many as we can. We do have contributors coming from China and we are forever indebted to their contributions.

> May I ask does an international community need to follow the laws and regulations? One China Policy have to be admitted before PRC establishes diplomatic relations with any countries, which includes India and Singapore.

I fail to see the relevance of this. We are not political entities in any way and I do not see how "One China Policy" can be brought into the picture here. Our number one goal is to serve our users, regardless of their origin -- if a user says that s/he is from Taiwan (or any place), we will be obliged to follow.

> All I would expect was a two-word fix and I never wanted to raise a political argument here.

Any fix added to the project needs justification. "Countries" work perfectly fine and is well-understood even if some of the entries are "states", "special administrative regions", or whatever terms one can come up with. The only field in which those terms differ and matter is the field of politics, which the TEAMMATES community would like to refrain from at all costs.

> I wasn't making and will not make any joke on this.

> I'm posting using my main account now.

> Justification: N/A

I am sorry to say this, but the fact that you created a throwaway account just to raise the issue makes your credentials questionable. It does not help that your issue was not backed with a proper justification -- "since Taiwan and Macau are among the list" does not tell why it needs to be "countries or regions". Had you given a proper justification, even as simple as `Some parties may not be pleased that some of the entries are listed as "countries"`, on top of using a proper account, we would be glad to consider your request.

I did concede that closing your issue without giving reasons was not the right thing to do, and for that I apologize. However, please do realize that by making your credentials questionable, you will not be treated seriously either. I believe that you would agree to that rule if you have been in Internet forums for long enough, and especially if you have to moderate one.

---

Back to the issue proper: I have no strong preference on either direction (rephrase or no rephrase).

**Comment by null09264** [comment] 2017-04-11 18:57
Hi Wilson,

Thanks for the long explanation. Honestly speaking, I wasn't too serious about this in the beginning. I was browsing through the page and came to this glitch accidentally. What I wanted to do is just to simply make a reminder for you guys. I didn't make a request to remove Taiwan and Macau from the list, but twist your expressions to make it more appropriate. I wasn't upset until this gentleman @thenaesh closed my issue silently. By the way, I think you @thenaesh should stand out and say something instead of hiding yourself behind and just thumbing up.

For the issue itself, I believe the way I expressed the problem is already clear enough. Anyone in Asia and Pacific should at least hear about this thing. Furthermore, you have Chinese team members and I have full confidence that they understand what I said without any extra justification. The fact is, did @thenaesh respect and ask them before closing the issue?

In the end, we are all CS students, and we should all know what Github issue tracker is for. We use them to track issues, not the contributors. A valid issue will NEVER become invalid even if it is posted by a credential questionable, throwaway account. In the end, why you want to have my credentials?

**Comment by thenaesh** [comment] 2017-04-11 19:57
@null09264 I was trying to just let the more senior team members handle this, but since you insist...

The reason why I closed the issue immediately was that:
1. It was dealing with a politically-charged issue that the TEAMMATES team does not wish to have anything to do with.
1. It was posted by a throwaway account with an extremely dubious account name.
1. It had "Justification: N/A".

It's the combination of all three (which made the post look like a troll), not any one of them in particular.

Had you posted this with your actual account and had a more compelling justification, I would have given it some airtime. I agree in principle with the need for privacy, and that the issue tracker is for tracking issues and not contributors. If someone came with a throwaway account and opened a normal issue or made a normal contribution, we would have gladly and gratefully accepted it. But this is very different.

The issue you posted is extremely politically-charged. What if someone from Taiwan happened to chance upon that issue and got outraged? The entire community will have to deal with the fallout from the ensuing flamewar while you happily remained anonymous. I'm sure you've heard of certain online communities that go around trolling others and causing serious trouble. We don't want those here. Naturally, when you post with a throwaway account (especially with that kind of username), one would assume that this is a troll out to cause trouble. Like @wkurniawan07 said, don't expect to be taken seriously if you appear to be a troll. We don't have time/manpower to deal with such nonsense, or to engage in guesswork to determine whether or not it's a troll. The path of least resistance in such cases is to simply close the issue.

So I think I've justified why I closed the issue the first time round without comment.

We are a truly international community. We have core team members from Sri Lanka, China, India, Indonesia and many other places. We have contributors from all over the world with a wide range of political views. We may even have contributors with wildly-conflicting views, possibly even from countries presently at war with each other. The point is that none of this should matter, and TEAMMATES (like many other open-source projects) should be a neutral ground for everyone.

But for this to happen, we need cooperation from the community as well, to **not** use TEAMMATES as a ground to further their own political agenda. What you did was post an issue and an aggressively-worded follow-up issue that could have caused a serious rift in the community, which is actually grounds for a ban. While I understand and respect your right to have an opinion, this is not the place to air them. This is an open-source project, not the United Nations or any other diplomatic entity. Whatever conflicts nations/states/regions/whatever may have is absolutely not our problem.

I hope I have made my point clear.

**Comment by null09264** [comment] 2017-04-11 20:55
Yes, your point is very clear that you never felt sorry for the impolite and disrespectful actions you have taken.

First, it is not relevant to politics AT ALL. Did I ask you to remove Taiwan from the list? What I purposed was just add two word "or regions" in the texts. I don't see how a Taiwanese would get outraged due to the expression "countries or regions". By the way, there's also Macau. Is there any difficulties for you to understand Macau is not a country? **You don't have manpower to add in two words and fix the issue, but it seems you do have the manpower to type such a long long text to argue with me.** 

Second, as you mentioned, TEAMMATES should be a neutral ground for everyone. This is exactly the reason why I post the issue. The phrase "countries and regions" would eliminate the controversy completely, I don't see why you think it's non-sense. What you have did has just made it extremely insulting to every Chinese in the community. Is this the definition of NEUTRAL by yourself? A salute to the United Airlines for the re-definition of ["re-accommodate"](http://www.urbandictionary.com/define.php?term=re-accommodate)?

Third, I would admit that using President Xi's portrait as avatar might seem funny and less formal but that doesn't give you any excuse to close the issue without actually checking it. I don't think there is any other problem with #7093. The description message was already informative enough to understand, the location in the site was stated clearly and the solution purposed was well-established without any bias. Any extra justification will solely increase the cognitive load of readers. If you are confused, I bet the reason is with yourself. Again if you have raised the issue to your the internal chatting channel of TEAMMATES, I'm sure you can make everything clear in seconds, including how you should respond, with much less efforts than thinking of the words to defend yourself.

Fourth, I'd like to express my appreciation again for Wilson's explanation and Prof. Damith's reopening the issue. I never meant to introduce any troubles to this awesome project. What I purposed is just a two-word fix. Current situations are completely resulted from a series inappropriate and unacceptable actions.

**Comment by damithc** [comment] 2017-04-12 02:51
Let's not waste time discussing this anymore. It is unlikely we will gain anything from discussing this further, especially in this forum. The issue will remain open but locked until we get around to doing something about it. If any readers of this thread (TEAMMATES members or others) have further input, please email us (to the TEAMMATES contact address).

**Comment by whipermr5** [comment] 2017-09-30 19:02
Closed in #8063.

**Closed by whipermr5** 2017-09-30 19:02 UTC
Labels: p.Low
