### ISSUE TITLE
Instructor view session results (course-wide): Add separate button to download results by question

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12283] opened 2023-03-28 08:09 UTC
Currently, when instructors are viewing course-wide session results (grouped by question), they can download the question results by clicking the question number, as shown by the given tooltip:
<img width="220" alt="Screenshot 2023-03-28 at 15 44 24" src="https://user-images.githubusercontent.com/54243224/228170060-1774f175-bffe-4da3-aebb-f287fe948621.png">

This is not ideal as the instructors would not know how to download results per question until they hover over this specific button. The tooltip is also currently unable to be captured by screen readers.

Adding a separate button for downloading results by question would fix all of the above issues.

**Comment by I-sultan0** [comment] 2023-04-01 20:49
Hi, @zhaojj2209 I am new to Open Source. Can you assign this issue to me

**Comment by domlimm** [comment] 2023-04-02 02:09
@I-sultan0 Hello, as per our [development guidelines](https://teammates.github.io/teammates/process.html#step-1-pick-an-issue-to-fix), we do not assign issues to contributors. Nevertheless, feel free to open up a PR to fix this issue!

**Comment by Conleth5** [comment] 2023-04-10 16:33
Hello, I've seen that this issue is still open and I would love to work on it. A PR should be coming soon!

**Comment by Conleth5** [comment] 2023-04-10 18:27
How do I get my local host to be able to log in as an instructor account so I can see this error?

**Comment by domlimm** [comment] 2023-04-11 04:06
@I-sultan0 pinging you again to check if you're working on this issue.

@Conleth5 hey, please refer to [TEAMMATES documentation](https://teammates.github.io/teammates/index.html) for more details on it.

**Comment by I-sultan0** [comment] 2023-04-11 21:23
Sorry for the delay. @Conleth5 you can go ahead to solve this issue.

**Comment by Conleth5** [comment] 2023-04-12 20:56
Is there a specific way or location where you would like the button to be?

**Comment by Conleth5** [comment] 2023-04-12 21:11
For example, does this look good?

![Screenshot 2023-04-12 170717](https://user-images.githubusercontent.com/73842589/231586026-2768ee63-1cc9-4676-9747-f172554c29b6.png)

**Comment by zhaojj2209** [comment] 2023-04-13 02:58
How about we use an icon button and have the "Download Question Results" text appear on hover? For the icon, we can use the same one in the download session results button below:
<img width="232" alt="Screenshot 2023-04-13 at 10 57 08" src="https://user-images.githubusercontent.com/54243224/231636535-d6084a75-cbe0-49f7-b8e4-fc60f5c897a2.png">

**Comment by Conleth5** [comment] 2023-04-13 20:53
How does this look? The Download Question Results only appears because I was hovering over it.

![image](https://user-images.githubusercontent.com/73842589/231880342-023901e8-63b4-4591-bd59-688757f05208.png)

**Comment by domlimm** [comment] 2023-04-15 02:56
@Conleth5 Hey Conleth, I think this looks good. But is it possible to make it similar to what @zhaojj2209 has proposed? I.e., The icon being similar to what we see above.

**Comment by Conleth5** [comment] 2023-04-16 14:37
Does this match what you are looking for?
![image](https://user-images.githubusercontent.com/73842589/232320424-13505c59-c0d7-4f77-bf97-0646cc005c07.png)

**Comment by samuelfangjw** [comment] 2023-04-16 17:22
Hi, going to do a bit of course correction here.

Let's follow existing design language in the rest of the application. For example, 

<img width="733" alt="Screenshot 2023-04-17 at 12 56 48 AM" src="https://user-images.githubusercontent.com/60355570/232328160-c20d497e-30b7-4bd1-882f-db42119a8452.png">

<img width="971" alt="Screenshot 2023-04-17 at 1 00 27 AM" src="https://user-images.githubusercontent.com/60355570/232328330-ff3baf34-fb01-45e0-b0bb-b26b23e3284f.png">

A simple button with text on the right hand side of the panel is fine. As for icons, not required in this case. Not consistent with current design + cost of screen real estate likely outweighs any potential benefit, given that this is a button for a secondary action.

**Comment by Conleth5** [comment] 2023-04-16 19:39
This seems to be the best I can do. Because it is in a span of which I cannot define the width, I am not able to lock the position of the download results button to the right side. 
![image](https://user-images.githubusercontent.com/73842589/232337886-034c116e-c8e1-491f-b747-62940c93c878.png)

**Comment by weiquu** [comment] 2023-04-18 05:37
Hi @Conleth5, it's a bit hard for me to understand what you mean (not too sure why there's a span involved along with the button). Would it be possible for you to open a draft PR with the current solution that you have so that we can take a closer look?

**Comment by Conleth5** [comment] 2023-04-18 17:26
I created the draft pull request. Please feel free to take a look!

**Comment by nhncha** [comment] 2023-06-15 20:05
Is this still active? I would like to work on it.

**Comment by domlimm** [comment] 2023-06-16 02:07
@nhncha Feel free to submit a PR for this.

**Comment by NyndoND** [comment] 2023-07-02 19:09
Hi, I can solve this issue?

**Comment by NyndoND** [comment] 2023-07-03 13:36
I "finished" the solution, but I have issues when a make a test for component, I want to check if the component I created really exist, but I am not able to get the component id. I tried to replicate what is done in other tests, but the "fixture.debugElement.query(By.css('.btn')).nativeElement" always returns null, as if there was no component with that class

**Comment by weiquu** [comment] 2023-07-03 14:10
Hi @NyndoND, could you open a draft PR so that we can take a look? It's a bit hard to understand right now.

**Comment by NyndoND** [comment] 2023-07-03 16:11
I created a draft, the lines commented, are previous attempts to try to identify if the component really exists, I know that it is visible when I run the dev server, but I would like it to be visible for the tests too
https://github.com/TEAMMATES/teammates/pull/12505

**Comment by NyndoND** [comment] 2023-07-03 20:55
I developed this component using the TDD technique, first I created the tests, ran them and got the errors. Then started the loop of:
- add code
- run tests
- Until all the tests I created passed,
 However visually I already reached the goal, the problem is the test that I am not able to implement correctly, if anyone can help me how to test this component i would be very grateful

**Comment by NyndoND** [comment] 2023-07-12 10:54
I created a pull request, if something is wrong, please let me know, thanks in advance for your attention  https://github.com/TEAMMATES/teammates/pull/12505

**Comment by sunshinemoua** [comment] 2023-07-26 20:36
Hi, I would like to work on this issue. Please let me know if someone is already actively working on it. Thanks!

**Comment by weiquu** [comment] 2023-07-27 08:51
Hi @sunshinemoua, feel free to submit a PR for this issue

**Closed** 2023-09-29 20:28 UTC
Labels: a-UIX, p.Low, good first issue
