### ISSUE TITLE
ConstSumRecipient question: missing submission validation

### ISSUE THREAD

**Issue by jtankw3** [TEAMMATES/teammates#10618] opened 2020-08-16 09:54 UTC
- **Environment**: `V7.0.0`

**Steps to reproduce**
Try to submit invalid constsum recipient question

**Additional info**
Able to submit when have not used all points
![constsum-recipient](https://user-images.githubusercontent.com/31800234/90331663-dc522880-dfe8-11ea-9c58-1f9656f9a08d.PNG)

Able to submit when extra points are given
![constsum-recipient-over](https://user-images.githubusercontent.com/31800234/90331740-77e39900-dfe9-11ea-9bff-0a55de64f3a9.PNG)

Able to submit with equal distribution even when uneven distribution is set
![other-option-same](https://user-images.githubusercontent.com/31800234/90331744-83cf5b00-dfe9-11ea-8883-db1d425d3046.PNG)

**Comment by wkurniawan07** [comment] 2020-08-16 10:00
Const sum recipient has this limitation due to the current lack of question-wide validation. Duplicate of #10397.

**Closed by wkurniawan07** 2020-08-16 10:00 UTC
Labels: p.Medium
