### ISSUE TITLE
Problems when there are no active courses

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/teammates#2847] opened 2015-01-07 08:21 UTC
1) InstructorHomePage is empty
If an instructor has no courses or archives all his courses, there is no indication/message of what he should see, and no prompt to create a course.

2) InstructorCoursesPage table is empty
The table should not show up.

![image](https://cloud.githubusercontent.com/assets/3910365/5642681/d207c6d2-9688-11e4-8a40-e7aa2e00fad7.png)

![image](https://cloud.githubusercontent.com/assets/3910365/5642698/21859fd6-9689-11e4-9c7d-9f189e7f0c22.png)

**Comment by damithc** [comment] 2015-01-07 08:37
I prefer empty table to 'hide table'. Empty table indicates that 'if you
had courses, they would show up here in this table'.
A guy who has archived all courses is not a newbie. So he/she should know
how to create courses.  Still, it may be good to give additional help in
such a case. Perhaps mention 'To access archived courses (if any), click on
the "courses" tab'?

**Comment by thyageshm** [comment] 2015-01-20 12:37
shall I take this one? Also, shall I add an additional condition for the message being shown:

If no courses at all : welcome new user message
else if no active course : view your archived courses at Courses Page
else : normal view of the courses

**Comment by damithc** [comment] 2015-01-20 12:45
Sure Thyagesh.

**Comment by damithc** [comment] 2015-01-20 12:47
If it is not difficult to do, we can leave it for contributors though. You can be the mentor. What do you think?

**Comment by thyageshm** [comment] 2015-01-20 12:50
ok :-)

**Comment by vamshi-s** [comment] 2015-03-12 04:10
@thyageshm  can i look into this issue ?

**Comment by vamshi-s** [comment] 2015-03-12 05:27
@thyageshm Please can you look into these two Images . 

Please suggest me ,for any further Modifications.

![afteraddingcourse](https://cloud.githubusercontent.com/assets/11355301/6612659/75644720-c8a6-11e4-9de4-dc5ca63f4a12.png)
![no_courses](https://cloud.githubusercontent.com/assets/11355301/6612660/756863aa-c8a6-11e4-8381-9c6b1f3e2446.png)

**Comment by vamshi-s** [comment] 2015-03-12 05:36
@thyageshm 

I have made modifications in  the InstructorCourses.Jsp Page, 
Initialized a boolean variable to false.
If the courses are present, and if its the first course, it check for the boolean variable value, if its false, it adds the table headings, else skips that part.

Please find the attached screenshot , for more information
![code_modifi](https://cloud.githubusercontent.com/assets/11355301/6612714/81721b36-c8a7-11e4-92dd-f3bc02bf3239.png)

When the idx value is still -1, used this code to highlight No Records Found Message
![sign](https://cloud.githubusercontent.com/assets/11355301/6612726/ae65a73e-c8a7-11e4-9834-c07815478ad6.png)

If my approach is wrong, please let me know.

**Comment by thyageshm** [comment] 2015-03-12 15:00
Hi! I believe the prof's suggestion of having an empty table sounds more appealing. What do you think about keeping the empty table, and providing the "You have no active courses. To create a course use the form above." message inside the table? This way the user has an idea of what to expect when he does have active courses and at the same time gets enough information to start off.

Please also look at the Home Page

**Comment by vamshi-s** [comment] 2015-03-13 00:44
I have made few modifications, please check these images out.

When the Instructor has no course's 
![initial](https://cloud.githubusercontent.com/assets/11355301/6631176/e89cff38-c947-11e4-8174-1daa1b54d843.png)

After Adding a course
![afteraddingcourse](https://cloud.githubusercontent.com/assets/11355301/6631178/f192b394-c947-11e4-8566-deae5ee007ca.png)

when the instructor has already archived few courses and dont have any active courses, then i will show that table with the message.
![afterarchiving](https://cloud.githubusercontent.com/assets/11355301/6631186/0b10ffe2-c948-11e4-9d7a-cd6f67c37e8e.png)

is this fine for instructorCourse Page ?

**Comment by damithc** [comment] 2015-03-13 03:01
Can we show the empty table even when there are no courses?

**Comment by vamshi-s** [comment] 2015-03-13 04:14
@damithc

**Comment by damithc** [comment] 2015-03-13 04:18
Yes, looks fine. :+1:

**Comment by vamshi-s** [comment] 2015-03-13 06:38
@thyageshm  I have added an extra  check in this branch, when there are no active courses.
i.e data.courses.size()==0

if (logic.isNewInstructor(account.googleId) || data.courses.size()==0 ) {
            statusToUser.add(StatusMessages.HINT_FOR_NEW_INSTRUCTOR);
  }

please find the output of the screenshots.

![insthome](https://cloud.githubusercontent.com/assets/11355301/6634142/83eb6048-c979-11e4-84bb-09979b8f6dbe.png)
![archivecourses](https://cloud.githubusercontent.com/assets/11355301/6634144/84cd0200-c979-11e4-8bd6-1149e4cbac35.png)

let me know, if adding that condition is an issue. will figure out other ways :)

**Comment by thyageshm** [comment] 2015-03-13 12:11
Hey, please try to add a different condition cos, no active courses does
not mean the instructor is new. Try different messages for the two
categories.
>
>

-- 
Regards,
Thyagesh Manikandan

**Comment by vamshi-s** [comment] 2015-03-13 15:05
Added  code,
 if(logic.isNewInstructor(account.googleId)==false && data.courses.size()==0 )
        {
            statusToUser.add("You have no courses created. <a href='/page/instructorCoursesPage'>Please create a course. </a>");
        }
![0](https://cloud.githubusercontent.com/assets/11355301/6640906/68751b00-c9c0-11e4-8801-cbe622ce4891.png)

**Comment by vamshi-s** [comment] 2015-03-13 15:09
Added this branch in the instructorhomepageaction.java file

 if(logic.isNewInstructor(account.googleId)==false && data.courses.size()==0 )
        {
            statusToUser.add("You have no courses created. <a href='/page/instructorCoursesPage'>Please create a course. </a>");
        }

is this fyn now ? @thyageshm 
![0](https://cloud.githubusercontent.com/assets/11355301/6640986/0c20c9d4-c9c1-11e4-94cb-5ee2bef96bd2.png)

**Comment by damithc** [comment] 2015-03-13 15:57
This is better: You do not seem to have any courses. Click here to create a
course.

**Comment by vamshi-s** [comment] 2015-03-13 16:49
Since there is an Add course Button on this Home Page, How about displaying this message , instead of earlier one.

![01](https://cloud.githubusercontent.com/assets/11355301/6642979/f308ba5c-c9ce-11e4-8558-c954a26812ce.png)

**Comment by damithc** [comment] 2015-03-14 01:01
... click on the 'Add New Course' button to ...

**Comment by vamshi-s** [comment] 2015-03-14 01:36
![0001](https://cloud.githubusercontent.com/assets/11355301/6649735/8422151c-ca18-11e4-8ca7-4854762b6e8b.png)

if this looks fine, shall i proceed with pull request ?

**Comment by thyageshm** [comment] 2015-03-14 04:59
remember to fix the tests AND add new tests to cover the new branches that you have added. Both in the Actions Test and the Browser Ui Tests

**Comment by vamshi-s** [comment] 2015-03-14 18:35
@thyageshm  :+1:

**Comment by vamshi-s** [comment] 2015-03-21 20:48
@thyageshm  

The Following files has been modified to pass the UI tests .

1. 
/teammates/src/test/resources/pages/instructorCoursesNoCourse.html
You can find the changes in the image,

![instructoractivecourse](https://cloud.githubusercontent.com/assets/11355301/6766683/4bc69ffc-d036-11e4-9e03-88f51e6bdf3e.png)

2.
/teammates/src/test/resources/pages/instructorHomeCourseDeleteSuccessful.html
You can find the changes in the image,
![homecoursedeltesuccesfull](https://cloud.githubusercontent.com/assets/11355301/6766688/731e2c0a-d036-11e4-8d20-25edee30e27e.png)

This changes has been made because i had modified InstructorCourses.Jsp Page.

Before Writing tests for the change in the InstructorHomePageAction, I would like to share you my analysis on this.

Since i have added brach, which sets the status message only if the instructor has previously created and delted/archived the course atleast once and currently he has no active courses.

To write a test for this, I need an instructor account who has no course at present and has already created and deleted/archived the courses. So that i can verify the status message. Please can you provide me this.? or any other alternative. ? 

one of the alternative i tried was, Please check the code in the image. 

![test111](https://cloud.githubusercontent.com/assets/11355301/6766762/79871a40-d039-11e4-8057-659025e31a82.png)

the problem was, it was always treating the user as the "new user".

Any changes please let me know.

**Comment by dingliheng** [comment] 2017-04-03 19:58
So is this issue still available? It seems that the problem has been solved. In fact, I found out that most of the open issues labeled with "d.Contributor" are already solved by someone. So can I still choose these open issues to work on? Thanks!

**Comment by damithc** [comment] 2017-04-04 07:48
@dingliheng 

> So is this issue still available? It seems that the problem has been solved.

You can help us confirm if the issue is solved. e.g. you can test your dev server to test it out. Archive all courses of a instructor and see what shows up in the home page (you can post a screenshot here).

**Comment by tarun14110** [comment] 2017-04-10 07:03
It seems problem is solved. Is this what we want ?

![screenshot from 2017-04-10 12 27 02](https://cloud.githubusercontent.com/assets/12219700/24849389/21216a2c-1de9-11e7-99e5-177d39b7ff8a.png)
![screenshot from 2017-04-10 12 27 32](https://cloud.githubusercontent.com/assets/12219700/24849390/212626b6-1de9-11e7-8350-ceff0f3b1c45.png)

**Comment by damithc** [comment] 2017-04-10 09:29
Yes @tarun14110 seems to be solved. closing.

**Closed by damithc** 2017-04-10 09:29 UTC
Labels: a-UIX, c.Enhancement, d.Contributors, f-Courses, p.Low
