### ISSUE TITLE
Constant sum questions: empty sub-response to a specific option/recipient should be considered as a 0

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/teammates#4019] opened 2015-07-24 03:50 UTC
For example, if Student A needs to distribute 100 points to 2 recipients, and he/she assigns 100 to a recipient, and leaves the other empty. The empty sub-response should be considered as a 0. Otherwise, the statistics does not account for the empty response and shows an inaccurate average.

**Comment by yj-soh** [comment] 2015-09-21 07:18
This appears to be impossible server-side without specifically adding a check for constant sum question in `FeedbackSubmissionEditSaveAction`. Thought about handling it when generating the statistics too, but it lacks the information about who are the possible recipient.

Should I just handle it client-side by setting a default value of 0 on submit?

**Comment by kanghj** [comment] 2015-09-21 17:08
Our favourite <code>FeedbackSessionsResultsBundle</code> should have the necessary information on getting the possible recipients, and it's passed into the question stats method. See if it's possible to handle it when generating the statistics?

**Comment by yj-soh** [comment] 2015-09-21 21:04
It's possible, I guess.

![2015-09-22_05-01-37](https://cloud.githubusercontent.com/assets/8586080/10004958/0cdc8b48-60e7-11e5-9448-4206a4ab9821.png)

It results in this situation with them represented as null below and 0 above, though.
I suppose that should be a new issue?

**Comment by kanghj** [comment] 2015-09-22 01:58
Ok sure, maybe we can display the missing responses in the statistics table as 'N/A' or something, but treat them as 0 during calculation. Or just omit them from Points Received entirely and consider them only during calculation of Average Points. Could be done in a different issue, I guess.

**Comment by tshradheya** [comment] 2018-02-22 14:03
While investigating this issue, I am unable to reproduce this problem. A 0 is already considered as a response when all the points are given to one of the options and the other is left empty.

Even while viewing statistics, I can see `0` instead of `No Response`.

Is there something more that needs to be done for this issue? If not, then we can close this

**Comment by damithc** [comment] 2018-02-23 02:28
I think this is a duplicate of #7875

**Closed by damithc** 2018-02-23 02:28 UTC
Labels: f-Results, p.Medium
