### ISSUE TITLE
Instructor sessions page: unusual delay in activating modal buttons

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#10348] opened 2020-07-18 16:13 UTC
It took about 10 seconds to get the cancel button into active mode. During that period, nothing happens when you hover over the button.
![image](https://user-images.githubusercontent.com/1673303/87856871-9ad04e00-c954-11ea-9b42-37900f532b16.png)

EDIT: applies to both buttons, not just the cancel button.

**Comment by damithc** [comment] 2020-07-18 16:22
I couldn't replicate this in UAT staging server but happens when I try the page against the production server. Could be a performance issue (I have about 50 sessions in that page.

**Comment by damithc** [comment] 2020-07-18 17:28
Similar problem observed in the session results page. Seems like modals get slowed down when the page has a lot of contents.

**Comment by madanalogy** [comment] 2020-07-23 07:58
This appears to be largely because the `SessionsTableRowModel` needs to be manually updated with `InstructorPrivilege`, which is a separate http request per session. Resolving this might require a new API endpoint to retrieve all privileges at once or implementing lazy loading / pagination.

> Similar problem observed in the session results page. Seems like modals get slowed down when the page has a lot of contents.

This one I'm less sure about but likely due to each question requiring a separate http request to load.

This isn't a modal problem but rather the modal requiring that the respective models be updated which depends on the speed of http requests. Consideration should be given for how to optimise performance at scale for anyone choosing to take this on

**Comment by damithc** [comment] 2020-07-23 09:08
A workaround is to show a spinner until the model is updating. Would that work?

**Comment by xpdavid** [comment] 2020-07-24 01:46
Technically the spinner should be shown while fetching privilege. @t-cheepeng Is it possible?

**Comment by xpdavid** [comment] 2020-07-24 01:48
@madanalogy 

> This one I'm less sure about but likely due to each question requiring a separate http request to load.

Yes it is but not when the page is loaded. So the cause should not be the same.

**Comment by t-cheepeng** [comment] 2020-07-24 03:43
> Is it possible?

Yup, it is possible. We can add a variable to the `SessionsTableRowModel` for loading of privileges and set it accordingly

**Comment by damithc** [comment] 2020-08-02 16:47
This problem is quite noticeable in the results page, even when the class size is small. We can't go live until this is fixed.

**Comment by wkurniawan07** [comment] 2020-08-03 11:30
I won't deny that this is a problem that needs fixing, but is this really a blocker? The only modal in the results page is the comments.

**Comment by damithc** [comment] 2020-08-03 16:18
> I won't deny that this is a problem that needs fixing, but is this really a blocker? The only modal in the results page is the comments.

True. It would be good to have some kind of solution (or minimally, a good understanding of the problem and a possible solution) before going live.

**Comment by damithc** [comment] 2020-08-03 17:48
Tried with Edge (instead of Chrome)
![modal](https://user-images.githubusercontent.com/1673303/89211521-8a76cf00-d5f4-11ea-9808-67a5ac163ada.gif)

**Comment by damithc** [comment] 2020-08-03 17:54
BTW, noticed that _after_ closing the modal, it takes about 5 seconds for the parent page to get active again i.e., buttons on the page are non-responsive for about 5 seconds.

**Comment by wkurniawan07** [comment] 2020-08-06 16:00
Update:
Not reproducible by most testers. Something in @damithc's local environment is causing these unusual delays. Will keep the `s.ToInvestigate` flag indefinitely (until the cause is found).

**Comment by wkurniawan07** [comment] 2021-05-16 12:30
Closing as there is no clear reproduction scenario

**Closed by wkurniawan07** 2021-05-16 12:30 UTC
Labels: p.Medium, s.ToInvestigate
