### ISSUE TITLE
instructorStudentComment: Give more informative status messages

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#1426] opened 2014-05-02 12:10 UTC
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on January 04, 2014 11:26:04_

Instead of generic messages, be more informative. e.g. The comment was deleted, also give an extract of the comment "The comment "blah blah" was deleted".

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1427_

**Comment by ruchirsharma1993** [comment] 2015-03-12 12:30
Hello
Can i be assigned this issue ? 
Thanks

**Comment by kanghj** [comment] 2015-03-12 12:42
Hello @ruchirsharma1993, go ahead and work on it. From this point on, you can look for further issues and create pull-requests for them and they will be taken into account, but we may not be able to review them(or assign to you) during this period.

**Comment by ruchirsharma1993** [comment] 2015-03-12 12:50
Ok sir, Starting Issue.

**Comment by samsontmr** [comment] 2017-01-15 09:29
w.r.t. #6358 
Does anyone have an idea why this is happening?
> java.lang.AssertionError: expected:<New comment 'this is a comment' has been added> but was:<New comment '
> this is a comment
> ' has been added>

I've tried using a .trim() on the comment before passing it into String.format() but this is still happening.

**Comment by whipermr5** [comment] 2017-01-19 07:35
@samsontmr I found the cause and wrote a comment on the PR (https://github.com/TEAMMATES/teammates/pull/6358#issuecomment-273700465)

**Closed** 2017-01-22 12:37 UTC
Labels: c.Enhancement, d.Contributors, f-Comments, p.Low
