### ISSUE TITLE
Feedback path options not enabled after cancel adding team contribution question

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#5716] opened 2016-06-23 08:44 UTC
At feedback session edit page, if an instructor adds a new team contribution (which has only one available feedback path), cancels adding the question, and subsequently adds another question of a different type, the other feedback paths are still disabled.

**Comment by chowyb** [comment] 2016-06-23 08:54
Duplicate of #5709, but since you have a PR open for this I guess we should close the other one then

**Closed** 2016-06-24 07:27 UTC
Labels: c.Bug, f-Submissions, p.High
