### ISSUE TITLE
AdminHome: Fix table overflow after instructor is added

### ISSUE THREAD

**Issue by AlexM9200** [TEAMMATES/teammates#8014] opened 2017-08-31 17:26 UTC
When you add a new instructor, the link overflows outside the table as shown below.

![bug](https://user-images.githubusercontent.com/21268058/29936295-940dff22-8e79-11e7-9837-3d828ca2eae7.PNG)

The GUI would be improved if the link stayed within the table.

**Comment by AlexM9200** [comment] 2017-08-31 23:51
I fixed this issue but for some reason my commits from a different pull request got included in this pull request. Anyone know what I did wrong? Will try and figure it out in the mean time

**Comment by LiHaoTan** [comment] 2017-09-01 04:33
@AlexM9200 did you `branch` out from `master`? Otherwise, as you would have guessed, that's probably why commits from another branch ended up in your new branch.

Anyway, this issue is a duplicate of #6900. Maybe next time you can try doing a search before opening an issue, though it is understandable sometimes a search may fail to catch duplicate due to different keywords/structure in a similar issue.

**Comment by LiHaoTan** [comment] 2017-09-01 04:34
Duplicate of #6900

**Comment by AlexM9200** [comment] 2017-09-01 10:45
I figured out where I went wront, thanks. My apologies for the duplicate. II did a quick search but didn't find #6900. I'm surprised it still hasn't been fixed yet.

**Closed** 2017-09-01 14:59 UTC
