### ISSUE TITLE
Instructor deleting all students: use batching if the class size is large

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11088] opened 2021-04-05 13:27 UTC
![image](https://user-images.githubusercontent.com/1673303/113578361-45101300-9655-11eb-9850-a2a9b6c3a3a5.png)

This operation can fail if the class size is large (I couldn't find the relevant issue in the issue tracker though. Did we fix it?).

If it is still not fixed, we can consider front-end batching as a possible solution, given the page already has a list of students. But this might need a new API end-point for deleting multiple students in one go.

**Comment by wkurniawan07** [comment] 2021-04-05 13:28
Duplicate of #8011

**Closed by wkurniawan07** 2021-04-05 13:28 UTC
Labels: s.ToDiscuss
