### ISSUE TITLE
Standardize use of Assumption.assertNotNull()

### ISSUE THREAD

**Issue by YongJieYongJie** [TEAMMATES/teammates#5532] opened 2016-06-03 06:49 UTC
Currently, `Assumption.assertNotNull()` is called using different constant strings like `ERROR_NULL_PARAMETER`, `DBLEVEL_NULL_INPUT` or magic strings like `"Non-null value expected"`.

All these strings are equally uninformative and are just variations of `"Null parameter supplied\n"`.

Related issue:
Enhance null check for post parameters to cater for cache expiry #2972

**Comment by AnaghHegde** [comment] 2017-04-17 13:39
@damithc So what exactly has to be standardized in this issue?. 

>All these strings are equally uninformative and are just variations of "Null parameter supplied\n".

Does this mean's the output of the AssertNotNull() method has to be standardised to something common?.

**Comment by damithc** [comment] 2017-04-18 14:21
Looks like the issue is not clearly defined. Closing.

**Closed by damithc** 2017-04-18 14:21 UTC
Labels: a-CodeQuality, d.Contributors, p.Low
