### ISSUE TITLE
Remove HTML in Java code by replacing current templating mechanism

### ISSUE THREAD

**Issue by VamsiSangam** [TEAMMATES/teammates#7487] opened 2017-06-09 08:27 UTC
The current template mechanism can only "fill" values but cannot perform operations like looping, if-else condition branching, etc. We need to replace this mechanism altogether with a more maintainable solution. Currently two proposed solutions are -

- [FreeMarker](http://freemarker.org/), [example](http://www.vogella.com/tutorials/FreeMarker/article.html)
- [Apache Velocity](http://velocity.apache.org/), [example](http://www.javaworld.com/article/2075966/core-java/start-up-the-velocity-template-engine.html)

Upon some study, I found FreeMarker to be highly favorable than Apache Velocity, some main reasons are -

- in both cases, line breaks in the template files must be escaped where neccessary. FreeMarker provides an easy solution to this by `compress` tags, but Apache Velocity doesn't seem to provide a similar facility (we need to rely on String operations).
- FreeMarker has a reliable Eclipse plugin in Eclipse marketplace which enables syntax highlighting and auto-complete features for editing FreeMarker templates. IntelliJ has out-of-the-box support for FreeMarker. Apache Velocity has several plugins for Eclipse but none of them seem to stand out.
- FreeMarker's scripting markup seemed more favorable as it has opening and closing tags (`<#list>`  `</#list>`), which is more readable than Apache Velocity's markup (`#foreach()`  `#end`).
- In terms of printing variables, FreeMarker's markup seemed more useful as it also allows us to do some quick math, eg. `${index + 1}`, but Velocity's markup for printing a variable doesn't support it (`$index`).
- More information can be found [here](https://github.com/TEAMMATES/teammates/pull/7439#issuecomment-307024037).

**Scope of this issue**

Two solutions are suggested. But other solutions are also welcome. Scope of this issue is to finalize a solution and integrate it to TEAMMATES by replacing the existing "HTML in Java" template mechanism with the finalized solution.

**Comment by damithc** [comment] 2017-06-12 05:03
While I'm open exploring this avenue, keep in mind that bringing in a new framework should be considered carefully because it adds to the learning curve and possibly performance. We already have jsp and jstl which also sort of like 'templates'. We should also explore if either one of them can be used instead of a new framework.

**Comment by damithc** [comment] 2018-02-24 11:45
Let's put this on hold for now.

**Comment by wkurniawan07** [comment] 2020-08-16 10:47
Duplicate of #6515.

**Closed by wkurniawan07** 2020-08-16 10:47 UTC
Labels: a-CodeQuality, c.Epic, p.Medium
