### ISSUE TITLE
Uninformative error message for incorrectly typed date input

### ISSUE THREAD

**Issue by halfwhole** [TEAMMATES/teammates#11236] opened 2021-06-28 16:53 UTC
Issue is common to date pickers in both `/web/instructor/logs/` and `/web/instructor/sessions/edit/` (audit logs and edit feedback session)

Type in an incorrect date in the date picker, and the following error message will show up:

<img width="1237" alt="Screenshot 2021-06-29 at 12 43 54 AM" src="https://user-images.githubusercontent.com/41856541/123673503-1f209600-d873-11eb-8e43-9e7d6833f52d.png">

(Edit: the error message is now different, see https://github.com/TEAMMATES/teammates/issues/11236#issuecomment-929362945! Also see https://github.com/TEAMMATES/teammates/issues/11236#issuecomment-930758270 for session/response visible timestamp)

Unlikely to happen because users are expected to pick the date using the calendar, but it still might be good to give an error message that's more informative

**Comment by emily876** [comment] 2021-07-07 08:10
I want to resolve it .Can you assign me this issue.

**Comment by halfwhole** [comment] 2021-07-09 15:39
@emily876 Sure, please go ahead

**Comment by A-GHOSH-dev** [comment] 2021-08-21 07:34
I would like to work on this issue.

**Comment by halfwhole** [comment] 2021-08-21 13:41
@A-GHOSH-dev please go ahead, no worries

**Comment by msaini0r** [comment] 2021-09-25 12:02
@halfwhole can you help in solving this issue. I have just started working in open source.

**Comment by halfwhole** [comment] 2021-09-25 16:08
Hi @msaini0r, if you'd like to contribute to resolving this issue, please do follow the guidelines at our [developer docs](https://github.com/TEAMMATES/teammates/blob/master/docs/README.md), especially how to set up the environment, the development guideline, and the contributing process/workflow. Thanks!

**Comment by Ln11211** [comment] 2021-09-27 17:13
hello,
I am Ln and I think I understand this issue as I have done something previously too when I was learning Java, is this issue closed or is someone still working on it ?, can I please work on it ?
thank you.

**Comment by Ln11211** [comment] 2021-09-27 17:50
Hello, can someone point the location of the file ?, is it in web/apps/pages-instructor ?

**Comment by msaini0r** [comment] 2021-09-27 18:23
I hope so..because I have myself tried to solve the issue in
web/apps/page-instructor. But i am not sure about it. Try asking halfwhole.

**Comment by Ln11211** [comment] 2021-09-28 15:55
well, @msaini0r did you have any good start ?, well I have also searched all date picker files and I haven't had any success..., maybe @halfwhole will know...

**Comment by Ln11211** [comment] 2021-09-28 15:55
@halfwhole, can you please help me with locating the file ?

**Comment by jianhandev** [comment] 2021-09-28 15:58
@halfwhole trying to reproduce that error, but I'm getting an error message of `End timestamp should be more than zero` instead when an invalid date is entered. 
<img width="1439" alt="Screenshot 2021-09-28 at 11 53 42 PM" src="https://user-images.githubusercontent.com/59337195/135122271-37c39a46-0087-4990-b4ed-724ae3c5d9a3.png">

**Comment by Ln11211** [comment] 2021-09-28 16:10
@jianhandev , can you please tell me how to reproduce this error ? I just want to learn

**Comment by Ln11211** [comment] 2021-09-28 16:20
what html file is that ?

**Comment by daongochieu2810** [comment] 2021-09-29 16:12
@Ln11211 To navigate around the codebase for this issue, I suggest you use  the search feature of your IDE e.g if you are using IntelliJ, you can use Ctrl + Shift + F, and search for `End timestamp should be more than zero` (the error message shown above) and see what is displaying the message. For the html page itself, you can see the text on the page, and search it as well. Let me know if it works for you

**Comment by Ln11211** [comment] 2021-09-30 03:33
@daongochieu2810,Yessssss it works!!!, thank you so much, all these days I have been searching for the file rather than searching for the message itself, well, I was wondering how can I reproduce this issue locally ?

**Comment by Ln11211** [comment] 2021-09-30 03:41
well, 0NAN is the error of invalid dates, I guess someone changed the text to "Start timestamp should be more than zero", well what if we change it to "Start timestamp should be more than zero and less than thirty one at the most !, please enter a valid date" .....

**Comment by damithc** [comment] 2021-09-30 03:54
> @halfwhole trying to reproduce that error, but I'm getting an error message of `End timestamp should be more than zero` instead when an invalid date is entered.
> <img alt="Screenshot 2021-09-28 at 11 53 42 PM" width="1439" src="https://user-images.githubusercontent.com/59337195/135122271-37c39a46-0087-4990-b4ed-724ae3c5d9a3.png">

In the production server, I get this error when I enter 33 as the date for the 'make response visible':
![image](https://user-images.githubusercontent.com/1673303/135384354-a1a1017c-3aca-47a7-a536-8574b56cf269.png)

**Comment by AmrMaghraby** [comment] 2021-12-15 20:31
Hi Devs,
Is this task still valid to work on it, or someone else is working on it?

**Comment by KaungthuKhant** [comment] 2022-01-01 21:38
Hi @ypinhsuan 
Is someone working on this issue?
If not, can you assign it to me?

**Comment by jianhandev** [comment] 2022-01-03 01:11
@KaungthuKhant you may work on this PR.

**Comment by KaungthuKhant** [comment] 2022-01-05 17:43
I am having this issue when I try to crate main config files. 
I used ./gradlew createConfigs  in my terminal but it is showing me the error below. 
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain

I am using a MAC. 
I saw gradle-wrapper.properties inside the wrapper folder which is inside gradle folder but it is not gradle.properties so I am not sure if they are the same file.

**Comment by ziqing26** [comment] 2022-01-14 15:13
> Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
> Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain

When you look in `gradle/wrapper` do you see `gradle-wrapper.jar` as well? This [post](https://stackoverflow.com/questions/57881202/how-to-resolve-java-lang-classnotfoundexception-org-gradle-wrapper-gradlewrappe) might be relevant for you when I searched your error messages

**Comment by ben-mathu** [comment] 2022-02-23 17:09
Anyone working on this issue?

**Comment by hhdqirui** [comment] 2022-02-24 23:08
Hi @ben-mathu, there is already an open PR for this issue. You can find another issue to work on. Thank you for your interest!

**Closed** 2022-04-17 14:42 UTC
Labels: p.Low, good first issue
