### ISSUE TITLE
Student Enroll Page: Refresh the existing student panel after enrollment.

### ISSUE THREAD

**Issue by Adoby7** [TEAMMATES/teammates#9663] opened 2019-04-11 13:14 UTC
- **Environment**: master at commit 7c075cfbedbdb1ec54e7aaf412ca4a0d1b93df34

**Description of feature/enhancement**
Currently the `existing students` panel is not updated after enrolling new students. Users need to quit and re-enter the enroll page to see the latest version of existing students.

This improvement can be done along with some consolidation in #9595 

**Justification**
Instructors can get all enrolled students without quitting the page.

**Comment by tanhengyeow** [comment] 2019-04-18 08:56
Related to this https://github.com/TEAMMATES/teammates/pull/9340#issuecomment-455873486

**Comment by Priyanka04-R** [comment] 2019-12-23 08:45
is this still open . if its still open i can work on that

**Comment by studentPavel** [comment] 2020-10-06 22:34
Is it still open? Could you assigne it to me?

**Comment by mayralgr** [comment] 2020-11-26 16:05
@Adoby7 is this still open to work with? or was it close with #9689 https://github.com/TEAMMATES/teammates/issues/9689 ?

**Comment by mayralgr** [comment] 2020-11-26 19:17
@madanalogy is this still an issue? or was it close with #9689

**Comment by madanalogy** [comment] 2020-11-28 09:25
> @madanalogy is this still an issue? or was it close with #9689

It was not fixed by that PR but appears to have been fixed based on manual testing on the production site at v7.5.0. Feel free to comment if you believe the issue is still valid

**Closed by madanalogy** 2020-11-28 09:25 UTC
Labels: c.Feature, good first issue
