### ISSUE TITLE
TimeHelper: migrate to Java 8's `java.time`

### ISSUE THREAD

**Issue by tran-tien-dat** [TEAMMATES/teammates#8362] opened 2018-01-26 14:04 UTC
The app is currently using the old `Date` and `Calendar` classes from `java.util` which is no longer recommended. As we have moved to Java 8, we should use the new specialized classes in `java.time` instead. It should also be easier to implement Daylight Saving Time (DST) with these new classes. From reading the source code as well as [discussions](https://github.com/TEAMMATES/teammates/issues/8094) on the issue tracker, @darrenwee and I have identified a few things that we would want to do regarding how our app handles time:

1. Refactor `TimeHelper` so that it uses the new `java.time` classes instead. Also have to modify all usage of these functions as the signature is changed.
2. Migrate the current timezone which is sometimes `double` and sometimes `String` to the `java.time`'s `ZoneId` and/or `ZoneOffset`. This would require migrating the database
3. Migrate timestamp fields in the database to UTC instead of Admin's time. This also requires migrating database. Some work on this has been done in [this PR](https://github.com/TEAMMATES/teammates/issues/8094)
4. Implement Daylight Saving Time.

For now, @darrenwee and I are working on point number 1, which will not require any modifications to the database. Here are some points that we have discussed:
- Keep using `double` for timezone in the interface, but convert it to Java's `ZoneOffset` using a private method for internal logic.
- Change the current `java.util.Date` type to `java.time.ZonedDateTime`. `java.util.Calendar` should also be converted to using `java.time.ZonedDataTime`
- For each method in `TimeHelper`, we will create a pull request to refactor that method as well as wherever the method is called.  If the data is further used by a method that we have not refactored, we will convert it back to the old `java.util.Date` temporarily until further PR refactor the method. -> Well the purpose of this is to try to keep each PR short and easier to review, but it also means we will done a lot of unnecessary conversion until everything has been migrated to Java 8's time API

@whipermr5 and @wkurniawan07 , what do you think of our approach?

**Comment by whipermr5** [comment] 2018-01-28 15:06
Sounds good!

For point 3, I think you meant local time instead of "Admin's time". I have an update about that: https://github.com/TEAMMATES/teammates/pull/8094#issuecomment-361069398

Converting `double` to `ZoneOffset` is a good workaround for the time being before we migrate the database. 👍

**Comment by darrenwee** [comment] 2018-01-29 13:24
Hmm, after seeing the link from @whipermr5 in #8094 I think we should probably store date-time as an `java.time.Instant` instead of `ZonedDateTime`? (i.e. both `Date` and `Calendar` should be changed to `Instant`)

If we use `ZonedDateTime`, we need to provide a `ZoneId` (if not, it is inferred based on the system time) where DST rules may change, like the example raised in #8094, and cause issues down the road. `Instant` has no concept of timezone and uses UTC only without observing DST. @tran-tien-dat

**Comment by tran-tien-dat** [comment] 2018-01-29 14:23
Agree 👍.

**Comment by tran-tien-dat** [comment] 2018-02-01 04:14
After working on this for sometimes, we realize that:

1. Many functions inside `TimeHelper` does not have a concept of timezone. For these, we should use `LocalDateTime`
2. It is very hard to make changes to only 1 method's signature and still keep the rest intact (i.e. compiling without errors). So we are thinking of just changing everything to `java.time` first and then worry about changing the data type of where the methods are used later.

**Comment by tran-tien-dat** [comment] 2018-02-01 13:01
After working on this for sometimes, we realize that:

1. Many functions inside `TimeHelper` does not have a concept of timezone. For these, we should use `LocalDateTime`
2. It is very hard to make changes to only 1 method's signature and still keep the rest intact (i.e. compiling without errors). So we are thinking of just changing everything to `java.time` first and then worry about changing the data type of where the methods are used later.

**Comment by whipermr5** [comment] 2018-02-07 05:49
Actually, this can be marked as a duplicate of #6300.

**Comment by darrenwee** [comment] 2018-02-08 04:39
Let's close #6300 since we are documenting the migration in this issue?

**Comment by darrenwee** [comment] 2018-02-08 05:01
@tran-tien-dat and I will mark methods as `@Deprecated` inside `TimeHelper.java` for now and replace the internal logic. We will preserve the old method's name and return type, but change the parameters as necessary (e.g. `Date` to `Instant`, etc). Then we migrate the old method's logic to use the updated method internally, i.e. the old method becomes a wrapper for the updated method. This ensures backwards compatibility as we progressively update.

Example:
```java
@Deprecated
public static boolean isWithinPastHour(Date time1, Date time2); // this is the old method's signature
// this method will call the replacement below and do the necessary type casting

// this is the replacement
public static boolean isWithinPastHour(Instant time1, Instant time2);
```

**Closed** 2018-03-11 08:05 UTC
Labels: a-CodeQuality, a-Storage, a-UIX, e.16, f-Sessions, f-Submissions
