### ISSUE TITLE
Instructor: home page: remind particular students: update all sorting icons when a column is sorted

### ISSUE THREAD

**Issue by shubham49** [TEAMMATES/teammates#7448] opened 2017-06-05 10:30 UTC
When we select 'remind particular students' on instructor home page, a list of students gets populated through ajax request. When we try to sort the columns by selecting on headers, then previously sorted column icon doesn't reset.

![issue](https://cloud.githubusercontent.com/assets/10528953/26780583/0ffc7494-4a08-11e7-95dd-175f1186ba2a.gif)

**Comment by shubham49** [comment] 2017-06-05 10:50
Same is the case with this

![home_issue](https://cloud.githubusercontent.com/assets/10528953/26781186/daf32ee8-4a0a-11e7-95f1-e9a609998d71.gif)

Should I make another issue for this?

**Comment by damithc** [comment] 2017-06-05 10:53
Indeed, this feature seems to be broken in multiple places. Must be a recent regression. Although it's not critical to the correctness of operations, it's an eyesore. Elevating priority.

**Comment by shubham49** [comment] 2017-06-05 10:55
![issue](https://cloud.githubusercontent.com/assets/10528953/26781326/86aa6eea-4a0b-11e7-93f1-4ec8a1fc84f6.gif)

Here also!

**Comment by wkurniawan07** [comment] 2017-06-05 11:01
@damithc I beg to differ, because the sorting function is never designed to reset all the other arrows to begin with.

**Comment by shubham49** [comment] 2017-06-05 11:08
@wkurniawan07  I think sorting function is working fine for positive cases.
Like here
![positive_case](https://cloud.githubusercontent.com/assets/10528953/26781663/5f6dee04-4a0d-11e7-943f-1c9e73be726b.gif)

**Comment by damithc** [comment] 2017-06-05 11:28
> @damithc I beg to differ, because the sorting function is never designed to reset all the other arrows to begin with.

That's possible (I can't remember it one way or the other). Ideally, it should reset? Otherwise we can't say which way the table is sorted.

**Comment by thenaesh** [comment] 2017-06-14 06:09
Fixed by #7476.

**Closed by thenaesh** 2017-06-14 06:09 UTC
Labels: d.Contributors, f-Email, f-Sessions, p.High
