### ISSUE TITLE
Error encountered while adjusting feedback session responses

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4549] opened 2015-11-02 02:14 UTC
Got a few of these in severe log.

1. Error Type: ERROR
Error Message: teammates.logic.automated.FeedbackSubmissionAdjustmentAction execute: Error encountered while adjusting feedback session responses of Peer Eval - Project #1 in course : EGR186-Fall2015 : null TEAMMATESLOG|||feedbackSubmissionAdjustmentWorker|||Servlet Action Failure|||true|||Unknown|||Unknown|||Unknown|||Unknown|||Servlet Action failure in feedbackSubmissionAdjustmentWorker
class java.lang.NullPointerException: java.lang.NullPointerException at teammates.logic.core.FeedbackResponsesLogic.updateFeedbackResponseForChangingSection(FeedbackResponsesLogic.java:600) at teammates.logic.core.StudentsLogic.adjustFeedbackResponseForEnrollments(StudentsLogic.java:645) at teammates.logic.automated.FeedbackSubmissionAdjustmentAction.execute(FeedbackSubmissionAdjustmentAction.java:83) at teammates.logic.automated.FeedbackSubmissionAdjustmentWorkerServlet.doGet(FeedbackSubmissionAdjustmentWorkerServlet.java:12) at teammates.logic.automated.WorkerServlet.doPost(WorkerServlet.java:31) at javax.servlet.http.HttpServlet.service(HttpServlet.java:637) at javax.servlet.http.HttpServlet.service(HttpServlet.java:717) at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166) at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43) at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157) at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388) at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216) at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182) at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765) at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418) at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260) at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) at org.mortbay.jetty.Server.handle(Server.java:326) at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923) at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78) at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:148) at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:465) at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437) at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444) at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:234) at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308) at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300) at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441) at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235) at java.lang.Thread.run(Thread.java:745)
{courseid::EGR186-Fall2015, enrollmentdetails::[ { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "bcw94@email.replaced.com", "oldTeam": "Proj1_SecH_Team4", "newTeam": "P#2_SecH_T1", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "mrf265@email.replaced.com", "oldTeam": "Proj1_SecH_Team2", "newTeam": "P#2_SecH_T1", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "msj74@email.replaced.com", "oldTeam": "Proj1_SecH_Team5", "newTeam": "P#2_SecH_T1", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "knt69@email.replaced.com", "oldTeam": "Proj1_SecH_Team1", "newTeam": "P#2_SecH_T1", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "seh356@email.replaced.com", "oldTeam": "Proj1_SecH_Team1", "newTeam": "P#2_SecH_T2", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "trm268@email.replaced.com", "oldTeam": "Proj1_SecH_Team2", "newTeam": "P#2_SecH_T2", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "kjw296@email.replaced.com", "oldTeam": "Proj1_SecH_Team5", "newTeam": "P#2_SecH_T2", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "kgp32@email.replaced.com", "oldTeam": "Proj1_SecH_Team3", "newTeam": "P#2_SecH_T2", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "lsg52@email.replaced.com", "oldTeam": "Proj1_SecH_Team4", "newTeam": "P#2_SecH_T3", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "alc574@email.replaced.com", "oldTeam": "Proj1_SecH_Team5", "newTeam": "P#2_SecH_T3", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "gpm28@email.replaced.com", "oldTeam": "Proj1_SecH_Team2", "newTeam": "P#2_SecH_T3", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "tqp5@email.replaced.com", "oldTeam": "Proj1_SecH_Team6", "newTeam": "P#2_SecH_T3", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "rdh242@email.replaced.com", "oldTeam": "Proj1_SecH_Team4", "newTeam": "P#2_SecH_T4", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "rps62@email.replaced.com", "oldTeam": "Proj1_SecH_Team2", "newTeam": "P#2_SecH_T4", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "eip6@email.replaced.com", "oldTeam": "Proj1_SecH_Team6", "newTeam": "P#2_SecH_T4", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "sps99@email.replaced.com", "oldTeam": "Proj1_SecH_Team3", "newTeam": "P#2_SecH_T4", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "rr829@email.replaced.com", "oldTeam": "Proj1_SecH_Team4", "newTeam": "P#2_SecH_T5", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "cmt348@email.replaced.com", "oldTeam": "Proj1_SecH_Team1", "newTeam": "P#2_SecH_T5", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED",

2. Error Type: ERROR
Error Message: "course": "EGR186-Fall2015", "email": "jas978@email.replaced.com", "oldTeam": "Proj1_SecH_Team3", "newTeam": "P#2_SecH_T5", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "bds267@email.replaced.com", "oldTeam": "Proj1_SecH_Team6", "newTeam": "P#2_SecH_T5", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "tvm33@email.replaced.com", "oldTeam": "Proj1_SecH_Team3", "newTeam": "P#2_SecH_T6", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "jb3329@email.replaced.com", "oldTeam": "Proj1_SecH_Team1", "newTeam": "P#2_SecH_T6", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "ber82@email.replaced.com", "oldTeam": "Proj1_SecH_Team6", "newTeam": "P#2_SecH_T6", "oldSection": "H", "newSection": "None" }, { "updateStatus": "MODIFIED", "course": "EGR186-Fall2015", "email": "agc89@email.replaced.com", "oldTeam": "Proj1_SecH_Team5", "newTeam": "P#2_SecH_T6", "oldSection": "H", "newSection": "None" } ], fsname::Peer Eval - Project #1}|||/feedbackSubmissionAdjustmentWorker|||Unknown20151102083623948

**Comment by wkurniawan07** [comment] 2016-02-17 16:51
Again, duplicate of #4769 (or rather the other way around), closing this one as it's easier to navigate to the more current one.

**Closed by wkurniawan07** 2016-02-17 16:51 UTC
Labels: f-Submissions, p.High
