### ISSUE TITLE
Users map: fix full map on iPhone browser

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#5243] opened 2016-04-22 13:26 UTC
Most parts of the user map doesn't seem to load on an iPhone browswer

**Comment by Gisonrg** [comment] 2016-04-26 17:40
My iPhone can view the users map normally, tested on both Safari and Chrome on iOS 9.3.1

**Comment by damithc** [comment] 2016-04-27 01:17
This is what I see (Safari, using latest version of iOS):
![image](https://cloud.githubusercontent.com/assets/1673303/14838913/d1c9e168-0c58-11e6-99f8-ebf88078d7bc.png)

**Comment by Gisonrg** [comment] 2016-04-27 06:13
Looks like the json data is not loaded in the screen as it didn't even show the total number of institutions and countries.

**Comment by damithc** [comment] 2017-05-19 10:51
Now I can see the map, but only part of the map is shown.

**Comment by wkurniawan07** [comment] 2020-09-19 13:17
Closing as (1) the reproduction step/condition is not well-defined and (2) the usermap implementation has been changed in V7.

**Closed by wkurniawan07** 2020-09-19 13:17 UTC
Labels: a-UIX, s.ToInvestigate
