### ISSUE TITLE
Student viewing results: show an explanation when there is nothing to see

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11414] opened 2021-09-12 03:15 UTC
Scenario: a student is viewing results but there is nothing for the student to see (e.g., no one has submitted responses  -- this can happen if the session is opened and published at the same time, or due to an instructor mistake)

![image](https://user-images.githubusercontent.com/1673303/132970587-4e999496-74fa-4356-b805-406c7f14a23c.png)

Suggested: show an explanatory message rather than an empty space

Reason: otherwise students think there is something wrong with the results link and email us

**Comment by Jellybeano** [comment] 2021-09-12 08:36
hi could i try working on this?

**Comment by halfwhole** [comment] 2021-09-12 14:56
@Jellybeano sure please go ahead!

**Comment by jianhandev** [comment] 2021-09-22 02:53
Closing this issue as it seems to be a duplicate of #11169.

**Closed by jianhandev** 2021-09-22 02:53 UTC
Labels: p.Low
