### ISSUE TITLE
Search page: Remove unnecessary panel

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11150] opened 2021-05-24 16:06 UTC
![image](https://user-images.githubusercontent.com/1673303/119374774-926f3f00-bcec-11eb-876e-065e5e41e7b2.png)

Suggested changes:
* Rephrase as `You can search for students (by name or email) from all your courses here.`
* Give an example at the end `e.g., "John Doe"`
* Remove this outer panel as all results are students anyway.

**Comment by RhnSharma** [comment] 2021-05-25 04:35
I would like to take this one.

**Comment by moziliar** [comment] 2021-05-25 04:40
@RhnSharma thanks for your interest. Please go ahead!

**Comment by sakibmahmud** [comment] 2021-06-04 01:33
Is the issue still open? I would like to work on this.

**Comment by moziliar** [comment] 2021-06-04 01:38
@sakibmahmud hi, thank you for your interest in contributing to the project!
The issue is currently handled by another contributor. Maybe you can look for another good-first-issue in the meantime?

**Comment by ipsitagoel** [comment] 2021-09-02 19:25
Is this issue available to work upon?

**Comment by hhdqirui** [comment] 2021-09-03 18:32
@ipsitagoel hi, thank you for your interest. This issue is currently available. Feel free to work on this issue.

**Comment by Ronald-patrick** [comment] 2021-09-10 05:40
I would like to work on this issue. Its already assigned, or else you can assign it to me.

**Comment by hhdqirui** [comment] 2021-09-11 02:59
@ipsitagoel hi are you currently working on this issue? If not then we will let others who are interested to work on it.

**Comment by rudheer** [comment] 2021-11-11 10:20
i can work on this issue, pl assign me if no one are currently working on it.

**Comment by Jaswanth19-596** [comment] 2022-02-21 02:19
I would like to work on this..... Is this issue still open

**Comment by daongochieu2810** [comment] 2022-02-21 16:11
@Jaswanth19-596 @rudheer it seems like @Moneill22 is still working on this issue

**Comment by Jaswanth19-596** [comment] 2022-02-22 02:44
Can I work parallely or should I wait till you assaign it to me .

**Comment by moziliar** [comment] 2022-02-23 05:44
@Jaswanth19-596 there is another contributor working on this issue. Please find another issue to work on in the mean time

**Closed** 2022-04-09 04:07 UTC
Labels: a-UIX, good first issue, p.VeryLow
