### ISSUE TITLE
Page layout messed up

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#4437] opened 2015-10-06 09:00 UTC
One user reports seeing messed up page layouts. Not sure what's the cause is though.

![image](https://cloud.githubusercontent.com/assets/1673303/10304281/c657db4e-6c4b-11e5-88da-f327ed236e86.png)

**Comment by damithc** [comment] 2015-10-06 12:48
May be fails to get full source of the page? If the js file is not loaded, it could end up sending invalid values to the server, triggering assertion failures.

**Comment by wkurniawan07** [comment] 2015-10-06 17:14
This looks like `bootstrap.css` failed to load. It's just a one-off accident, I hope?

**Comment by junhaoyap** [comment] 2015-10-06 17:17
Agree with @wkurniawan07, perhaps caused by a css load timeout due to slow internet, similar to us sometimes seeing messed up page layouts like this on Facebook or Google when our internet connection is very poor, don't think it's something that is worth digging into?

**Comment by LowWeiLin** [comment] 2015-10-21 12:14
I just got this on the live server.

![image](https://cloud.githubusercontent.com/assets/3910365/10636163/505bc108-7830-11e5-9818-612193d6ba7f.png)

**Comment by kanghj** [comment] 2015-10-21 12:19
Getting it too

**Comment by damithc** [comment] 2015-10-21 12:23
I got that earlier. Sometimes you keep getting it until you switch browser. It eventually goes away though.

**Comment by damithc** [comment] 2015-10-21 12:25
Actually, I'm getting it right now in chrome but not in FF :-p It was the same case earlier.

**Comment by wkurniawan07** [comment] 2015-10-21 12:45
[This](http://www.lucidica.com/help/err_quic_protocol_error/) looks like what's going on. I haven't got it myself so I can't verify.

**Comment by wkurniawan07** [comment] 2016-04-12 08:30
This is a general Chrome bug not related to our code, so closing.

**Closed by wkurniawan07** 2016-04-12 08:30 UTC
Labels: a-FaultTolerance, m.Aspect, p.Medium
