### ISSUE TITLE
Admin logs page: Extension of query start/end time is not reflected in search range

### ISSUE THREAD

**Issue by zhaojj2209** [TEAMMATES/teammates#12293] opened 2023-03-28 09:10 UTC
Currently, clicking the extend start/end time buttons causes the query time range to be changed, but the change is not reflected in the user input. In the below example, the start time was extended by 20 minutes to 13:42, but the user input remains at 14:02.
<img width="1238" alt="Screenshot 2023-03-28 at 17 06 25" src="https://user-images.githubusercontent.com/54243224/228187087-44b9a7c0-d6a9-4901-af82-a1609f9964f4.png">

Suggestion: After clicking the extend start/end time buttons, the user input date range should also be changed accordingly.

**Comment by gordonscottkolb** [comment] 2023-03-29 02:29
Hello! I am new to open source programming, but I have successfully set up the development environment and I am excited to get started! I would love to try this as my first issue. What are the steps to reproduce this issue on the development site? I looked on the site but am not sure how to get to the page pictured in the screenshot above. Thanks!

**Comment by weiquu** [comment] 2023-03-29 03:02
Hi @gordonscottkolb, after opening the Teammates website, click on `Login` -> `Instructor Login`, then enter the email as `app_admin`:
<img width="348" alt="log in" src="https://user-images.githubusercontent.com/48304907/228415579-e90f8e51-4e14-46fa-8125-c8db22edbd87.png">


After logging in, click on `app_admin` then `To admin pages` on the top right:
<img width="806" alt="to admin pages" src="https://user-images.githubusercontent.com/48304907/228415693-3d130abc-017b-4d89-90c3-65cc0bbf3b74.png">


Then, click on `Logs` in the navbar above, and you should be brought to the page pictured in the issue:
<img width="1173" alt="logs" src="https://user-images.githubusercontent.com/48304907/228415760-6d0c382e-439b-4804-9bf7-60ec60878663.png">


Do let me know if you need any other help!

**Comment by domlimm** [comment] 2023-03-31 03:03
@gordonscottkolb Hey gordon, have you made an attempt to fix this issue?

**Comment by gordonscottkolb** [comment] 2023-03-31 05:14
@domlimm Yes I have. I am on US eastern time and will try to open a pull request in the morning or by the afternoon tomorrow. Thank you!

**Comment by domlimm** [comment] 2023-03-31 05:31
@gordonscottkolb No hurry at all gordon. Looking forward to your fix! 😄

**Comment by zhaojj2209** [comment] 2023-03-31 06:14
@gordonscottkolb Someone else has already submitted a PR for this issue. Perhaps you may want to work on another issue instead?
Alternatively, you may continue to open a PR for this issue, but do take note that there is a chance that the PR may not be merged.

**Comment by Khalid6468** [comment] 2023-03-31 06:53
@gordonscottkolb Sorry for working on the issue after you had already started to work on it. I will be closing my PR. Please do continue to work on it.

**Comment by gordonscottkolb** [comment] 2023-03-31 13:49
@Khalid6468 Thank you, I appreciate it. @zhaojj2209 if there is no rush, I may need a couple more days as I am quite busy today, if that is okay. (I did pick this issue because it was tagged as a good first issue with low priority) Thank you!

**Closed** 2023-04-13 06:04 UTC
Labels: good first issue, c.Bug, p.VeryLow
