### ISSUE TITLE
Student view profile: preserve proportions of the profile image

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#11147] opened 2021-05-24 14:30 UTC
Context: a student is viewing the profile photo

Current:
![image](https://user-images.githubusercontent.com/1673303/119362285-1e7a6a00-bcdf-11eb-81fd-34ca8a7c4542.png)

Problem: the image is squashed into a fixed size and with. We can't assume the image to have a specific width:height ratio because no such requirement is mention or enforced at the when uploading the image.

Suggestion: Fix only the width (or height), preserving proportions of the image

**Comment by smanpreet96** [comment] 2021-06-01 02:08
Hi, can I contribute towards resolving this one?

**Comment by moziliar** [comment] 2021-06-01 02:14
@smanpreet96 sure! You can give it a go!

**Comment by smanpreet96** [comment] 2021-06-01 02:19
Thank you!

**Comment by smanpreet96** [comment] 2021-06-02 04:50
Hi, I am unable to run the backend server locally due to discrepancy in the g-cloud version of the project and my local machine (Well from the error logs seems like that's the issue). Is there a way to login to a student profile without masquerading  through admin view?

**Comment by aileenpalafox** [comment] 2021-06-11 21:11
Hi, is @smanpreet96 still working on this issue or can I give it a try?

**Comment by smanpreet96** [comment] 2021-06-11 21:32
Hi @aileenpalafox actually I didn't even get a chance to work on it because I was not able to run the backend server. I dropped my previous comment and while waiting for a response I totally forgot to ask again. So if you have the servers running you can work on it. However I would still like some assistance with this server thing so that I can take up some other issue later on.

**Comment by aileenpalafox** [comment] 2021-06-11 21:39
Thanks for the quickly response, I'm sorry to hear that. I hadn't try to run the server but I let you know if I can!

**Comment by moziliar** [comment] 2021-06-12 00:08
Hey folks! Sorry for not getting back! Can you guys send me a screenshot of the error when you attempted to start the backend server? @aileenpalafox @smanpreet96

**Comment by lyeyixian** [comment] 2021-06-12 16:41
@smanpreet96 Hi, I don't know if this is your issue, but for me I ran `gradlew.bat runDatastoreEmulator` before running `gradlew.bat serverRun` and it works fine.

**Comment by smanpreet96** [comment] 2021-06-13 00:59
Okay let me try and see if this works @lyeyixian

**Comment by aileenpalafox** [comment] 2021-06-19 03:17
Hello, again
@smanpreet96 I was able to run the server just fine, are you still having troubles or were you able to run it?
Also, should I work on the issue or are you already working on it?

**Comment by smanpreet96** [comment] 2021-06-19 06:09
Hey @aileenpalafox you can work on this issue. I got my hands full with office projects, so I don't think I will get a chance to take up anything until next month.

**Comment by aileenpalafox** [comment] 2021-06-20 19:42
@damithc @moziliar I'm having trouble uploading the photo in the dev server, it says is uploaded but the image doesn't update. I've been reading the docs but I'm not sure what to do.

**Comment by aileenpalafox** [comment] 2021-06-23 18:21
Hello, @moziliar I'm going to drop off this issue for now, in case anyone else is interested they can give it a go. :)

**Comment by Hamidou0** [comment] 2021-08-10 02:17
Hi, I'll try resolving this, still open? @moziliar

**Comment by moziliar** [comment] 2021-08-12 00:52
@Hamidou0 thank you for your help! If you need any help for your fix, do voice out.

**Comment by A-GHOSH-dev** [comment] 2021-08-21 07:38
Can I contribute in this ? Please let me know

**Comment by Hamidou0** [comment] 2021-08-21 23:08
@A-GHOSH-dev hello, Im getting caught up with work if you can go for it

**Comment by itishrishikesh** [comment] 2021-10-21 18:08
Hi,

I was trying to look into this issue - but I am getting the following error log on my local machine when I try to upload a profile picture:

![image](https://user-images.githubusercontent.com/24785679/138332528-9862c241-5f8a-46f3-8e14-762b24a870da.png)

Apologies! if it's not the correct thread to ask this question, also if the issue is available I would like to work on it.

**Comment by drblaui** [comment] 2021-11-15 11:58
I would like to give this a try!

**Closed** 2022-01-02 00:22 UTC
Labels: p.Low, good first issue
