### ISSUE TITLE
Instructor Homepage: "Add New Course" and "Sort By" loose responsiveness at Mobile Widths

### ISSUE THREAD

**Issue by pollysobeck** [TEAMMATES/teammates#9740] opened 2019-06-02 20:50 UTC
At mobile and smaller screen widths, the "Add New Course" button and Sort By text overlap, making both unreadable and the "Add New Course" button unusable where there is overlap.

**Environment**: Live Server V6.16.2

**Steps to reproduce**
- On a phone or at browser widths smaller than 530px wide, log in as instructor
- Navigate to Home page
- Observe overlap of "Add New Course" button and "Sort By" text

**Expected behaviour**
"Add New Course" and "Sort By" buttons should stack vertically at xs screen widths

**Actual behaviour**
"Add New Course" and "Sort By" buttons overlap at xs screen widths

**Additional info**
Observed Behavior in Chrome 74

![image](https://user-images.githubusercontent.com/26610793/58767150-3d085900-853c-11e9-8b64-b80b6f15e499.png)

**Comment by husar** [comment] 2019-10-10 13:07
Hello, i would like to work on this issue if it is still open. Please assign it on me.

**Comment by husar** [comment] 2019-10-10 13:38
Can you give me access as instructor?

**Comment by damithc** [comment] 2019-10-11 00:47
@xpdavid is this issue relevant to V7?

**Comment by xpdavid** [comment] 2019-10-11 01:54
![image](https://user-images.githubusercontent.com/13977235/66618782-5c209280-eb8f-11e9-8467-e538edf354d4.png)

Looks like yes but with a different glitch.

**Comment by madanalogy** [comment] 2019-12-11 08:38
The issue was caused by static height declaration which forced contents into a smaller row height than contained contents at extra-small sizes. Since the static height is not absolutely necessary at larger screen sizes (bootstrap auto-adjusts), I have suggested removing it altogether in my referenced PR.

**Closed** 2019-12-11 18:39 UTC
Labels: a-UIX, c.Bug, d.FirstTimers, v7-resolved
