### ISSUE TITLE
InstructorFeedbackResultsPageScalabilityTest: tests data should not be removed and refreshed for each test case

### ISSUE THREAD

**Issue by samsontmr** [TEAMMATES/teammates#7171] opened 2017-04-19 03:38 UTC
In `InstructorFeedbackResultsPageScalabilityTest`, the entire set of test data is currently refreshed for each test case. Since the content of the test data does not need to be unique for each test case (we only need to increase the amount of data), we should explore adding test data for each subsequent test case instead of replacing the entire dataset.

This is important because the scalability tests are meant to be run on the live/staging server, and write operations are not free there.

**Comment by sujeet14108** [comment] 2017-04-19 06:36
@samsontmr Are we talking about calling  `    @BeforeMethod  
   public void refreshTestData()` before every test?

**Comment by samsontmr** [comment] 2017-04-19 08:03
That's right. Ideally it should "top up" the data to the amount required for the next test case or remove excess data.

**Comment by Malkone** [comment] 2017-05-08 10:01
Hi, the issue is interesting, I would like to try solving it. 
Can you please help to understand the task correctly: method ```refreshTestData(String filename)``` loads ```DataBundle``` from JSON file, which is created in class ```InstructorFeedbackResultsPageDataGenerator```. We have 6 such files (with 10 or 20 students with 1, 5 and 10 questions for each of two options) and for each such new ```Student```objects are generated. So we got 3 * 10 + 3 * 20 = 90 randomly generated students for test.
Should I change this and generate only 20 rendom students, and then use 10 of them for the first 3 tests and 20 of them for the rest ?

**Comment by samsontmr** [comment] 2017-05-08 12:24
Yes, that sounds about right. However, take note of the transition from 10 students+10 questions to 20 students+1 question.

**Comment by Malkone** [comment] 2017-05-08 16:18
Thanks, I'll be careful with that transition! 
One more question for better understanding the goal. You wrote that "write operations are not free" on live/staging server - which operations specificly are chargeable? I mean, which result is beeter:
- writing less files with testing data?
- or quantity of file does not matter and only their sum volume in bytes matter?
- or even creating multiple objects within JVM increases expenses?
This understanding is important for defining the most optimal way of making changes.

**Comment by samsontmr** [comment] 2017-05-10 06:13
I believe it should be `quantity of file does not matter and only their sum volume in bytes matter?`

@whipermr5 can confirm?

**Comment by whipermr5** [comment] 2017-05-10 07:15
It should be number of calls to the datastore.

**Comment by whipermr5** [comment] 2017-05-27 08:01
> we should explore adding test data for each subsequent test case instead of replacing the entire dataset.

Apologies I didn't flag this out earlier, but this does not reduce the number of write operations. The test is about adding x amount of test data (with increasing values of x) and measuring the time taken, right? Adding x amount of test data will always incur x amount of Datastore writes.

**Comment by damithc** [comment] 2017-05-27 08:15
From the name of the test, I assume this is supposed to measure the scalability of reading response objects, not writing them. Therefore, objects can be written once and read every time the test is run.

**Comment by samsontmr** [comment] 2017-05-27 15:01
> From the name of the test, I assume this is supposed to measure the scalability of reading response objects, not writing them. Therefore, objects can be written once and read every time the test is run.

Yes, that is the idea.

**Comment by Malkone** [comment] 2017-05-27 20:11
Thanks, I'll try to update my pull request correspondingly.

**Comment by damithc** [comment] 2018-02-02 05:29
@wkurniawan07 do we still have the scalability tests in concern? if not, we can close this issue.

**Comment by wkurniawan07** [comment] 2018-02-02 11:42
This is the script written by @samsontmr roughly a year ago, not the outdated ones I deleted in #8369.

**Comment by damithc** [comment] 2018-05-15 00:10
I don't think this will be used in near future. Putting on hold.

**Closed by damithc** 2018-05-15 00:10 UTC
Labels: a-Performance, a-Scalability, a-Testing, d.Contributors, p.Medium, s.OnHold, t-GAE
