### ISSUE TITLE
Add support for daylight saving time

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#84] opened 2014-05-02 08:13 UTC
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on June 30, 2011 16:11:15_

Does time zone support work correctly when day light saving is involved?

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=85_

**Comment by damithc** [comment] 2016-02-06 12:03
@ashrayjain assigning to you, as discussed.

**Comment by ashrayjain** [comment] 2016-02-15 10:04
@damithc Hey prof, it turns out we have two more fields (`session visible from` and `responses visible from`), apart from `session start` and `session end`. Our discussed solution of adding 2 new columns in the db for `session start offset` and `session end offset` will not be enough for this. We could solve this problem in the following 3 ways:

1. We could simply add 2 more columns for the new fields. However, if we ever need to add any more date related info to the Session object, we will need to add new columns for DST as well.

2. We could store the timezone ID string (like `Asia/Singapore` or `Australia/Adelaide`) in our db and remove all other offset related columns (like `timeZone`, `timeZoneDouble` as well as all the dst offset columns). Then we will need to update all code that uses the timeZone fields to use Java's standard library and apply this timezone ID (which includes DST info) when retrieving timestamps from the db.

3. We could do away with storing timezone info separately and change all date fields in our db to have the correct timezone (eg. `SGT`) as part of the timestamp as opposed to the current value (`UTC`).

An important consideration would be on how we will handle transitioning for existing sessions. What do you think?

**Comment by damithc** [comment] 2016-02-15 10:34
It has to be 2 or 3. What is the common wisdom on handling timezones and DST? Any articles on this?

**Comment by ashrayjain** [comment] 2016-02-15 13:02
There are a lot of different opinions on StackOverflow about this, and a lot of times they are for specific cases. The best article that I think we should follow is this one.
https://www.w3.org/TR/timezone/#guidelinessummary

On the same article, these sections are also of interest:
https://www.w3.org/TR/timezone/#guidelinesfuturerecurring
https://www.w3.org/TR/timezone/#negotiating

The general overview is that, especially when dates in the future are involved, storing the timezone ID is the best way. Other things can be used as fallbacks but timezone IDs should be used if available.

**Comment by damithc** [comment] 2016-02-15 14:11
I'm ok with storing timezone ID. We also need to discuss where to store it. For example, may be we should store in in the Course object rather than the Session object? Explore these further and we can discuss on Wednesday.

**Comment by damithc** [comment] 2016-02-15 14:11
You also need to figure out how to save DST lookup table and how to keep it updated.

**Comment by ashrayjain** [comment] 2016-02-15 14:51
Since we will be using the standard library for Java for DST conversions, we will need to update the standard library's data. The common method for updating this data is outlined here.
http://www.oracle.com/technetwork/java/javase/tzupdater-readme-136440.html

However, I will need to look into how it would work with GAE.

**Comment by ashrayjain** [comment] 2016-02-15 19:27
With GAE, the standard library is locked in and out of our control. [This](http://stackoverflow.com/a/18340343) is the only issue about this I could find.

Google does seem to update its timezone data but not very frequently as it turns out. I tested the standard library on a GAE test app using known timezone/dst updates from the past year (eg. North Korea's timezone update from August 2015). From what I tested, updates until June last year are in. I would guess that Google follows a yearly update cycle for this. So the question is, if this frequency is ok for us?

The other alternative is to use an external library instead of the standard library so that we can update the data as we please. The most popular alternative seems to be [Joda Time](http://www.joda.org/joda-time/).

**Comment by damithc** [comment] 2016-02-16 00:48
Yes, I'm ok to use an external library as Java built-in date library is known to be weak. Is Joda time updated more regularly?

**Comment by ashrayjain** [comment] 2016-02-16 00:54
Yup sir. Joda seems to follow the updates to the database pretty closely.
Their latest version already includes the first updates for 2016 released
in late January. So should I go ahead with it?

**Comment by damithc** [comment] 2016-02-16 01:15
Yes, go ahead with Joda.

**Comment by ashrayjain** [comment] 2016-02-17 14:39
@damithc Since we are adding timezone info to courses, I wanted to clarify some semantics. It looks like once a course is created, we don't allow the instructor to change the Course ID or Course Name (am i right?). As we will be adding the timezone option there, do we also disallow timezone updates after the course has been created? Is there any use case for timezone updates after course creation?

Note: We will still allow the user to change the detected value on the course create page, BEFORE the course is created.

**Comment by ashrayjain** [comment] 2016-02-21 08:50
@damithc bump.

**Comment by damithc** [comment] 2016-02-21 10:03
No reason not to allow it right?
The other two fields should be allowed to change too. It's just that we didn't find time to do it.

**Comment by ashrayjain** [comment] 2016-02-21 10:06
Hmm. I don't see any reason to disallow changing course name and timezone. But maybe ID is more sensitive to change? @thyageshm your thoughts?

In any case, I think it will be better to add this functionality as a separate issue rather than with this one?

**Comment by damithc** [comment] 2016-02-21 10:18
Yes, editability of each field can be separate issues. Yes, editing course ID is the trickiest and may never be allowed.

**Comment by thyageshm** [comment] 2016-02-23 06:56
sir, I believe if we change the courseid, we would have to change it in every student/instructor in that course. We should consider if that is an acceptable overhead

**Comment by thyageshm** [comment] 2016-03-13 06:25
@ashrayjain if this is being fixed by another pr, specify it in that pr. 
If not, reminder to work on this. It has slipped a release

**Comment by whipermr5** [comment] 2017-07-18 13:53
From what I understand, we have to:
- Migrate `FeedbackSession` `timeZone` field from `double` to string containing time zone ID.
  - We can use the `Etc/GMT-X` time zones to maintain expected behaviour, as these time zones do not have DST. It is up to instructors to change the time zone to their correct local time zone if they want to enable DST.
- Migrate time fields within `FeedbackSession` such that timestamps refer to the actual time in UTC rather than local time.
- Update all views of the time fields to interpret the timestamps as actual time in UTC, and pretty print them in the time zone specified by the `timeZone` field using a date library that handles DST.

Is there anything I'm missing?

**Comment by damithc** [comment] 2017-07-18 13:57
@wkurniawan07 can weigh in. He was the last person to handle this hot potato 😝

**Comment by wkurniawan07** [comment] 2017-07-18 14:06
The plan was to ditch timezone fields in feedback sessions completely and relying fully on the one in course, which already is in Olson timezone ID. The timezone field in the courses was actually added for this purpose.
I tried and met many roadblocks along the way, and realized one part of the puzzle is #6300, although evidently I did not manage to find the time to actually work on it 😛
After cleaning up all the APIs, the last part of the puzzle should be removing the timezone fields completely from the feedback session and relying on the course's.

For the reason that it has not been actually tried out, I cannot give a 100%-guarantee that the previous plan would _actually_ work, although it sounds plausible on paper. Migrating the timezone field in feedback session would also work, but will require another migration process. Since I was not actually involved in the discussion as for why use timezone in course vs use timezone in sessions, I'd open this topic back to square one again.

**Comment by whipermr5** [comment] 2017-07-18 14:14
Well I guess since our users have gotten used to a session time zone, we shouldn't remove it immediately. We can first migrate the session time zone field, announce support for DST, then deprecate the use of a session specific time zone before finally removing it once we're sure no one uses it anymore?

**Comment by damithc** [comment] 2017-07-18 14:24
From what I remember, we planned to show the time zone in the session (but readonly) even if it is stored in the course. That way, users will not notice a big difference UI-wise.

**Comment by wkurniawan07** [comment] 2017-07-19 17:12
@whipermr5 I forgot to link this issue as well: #5928

**Comment by whipermr5** [comment] 2018-02-07 05:45
Linking to this issue which contains some discussion: #8362

**Comment by whipermr5** [comment] 2018-03-19 03:37
As discussed with @tran-tien-dat, we should not worry about local date times that are ambiguous or non-existent but leave it to the library to resolve. The [javadoc for ](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDateTime.html#atZone-java.time.ZoneId-) explains clearly how these are resolved.

However I think we should still show a message to the user if the local date time they input is ambiguous or non-existent, stating clearly which time we resolved it to and, in the ambiguous case, allow a way to select the later offset time.

**Comment by whipermr5** [comment] 2018-03-19 19:58
Sneak peek:
<img width="769" alt="screen shot 2018-03-20 at 3 55 57 am" src="https://user-images.githubusercontent.com/6811428/37618937-c1af70c0-2bf2-11e8-8562-4df175e1e97c.png">

**Closed** 2018-04-01 11:13 UTC
Labels: d.Committers, e.16, f-Sessions, f-Submissions, p.Medium
