### ISSUE TITLE
CollapseAnim causing elements to be cut off

### ISSUE THREAD

**Issue by jtankw3** [TEAMMATES/teammates#10305] opened 2020-07-12 13:55 UTC
Children elements of elements with CollapseAnim attached are cut off when they overflow.

- **Environment**: `master` branch at commit a5f15f9f634d1b988b3f6f50a85959365da48b1b

**Steps to reproduce**
Interact with elements that exceeds height of parent element (eg. feedback edit page visibility date picker)

**Expected behaviour**
Dropdown/tooltip should be visible even if they overflow

**Actual behaviour**
The elements are cut off

**Additional info**
Example, date picker is not completely visible
![datepicker](https://user-images.githubusercontent.com/31800234/87248094-0d8b8600-c48a-11ea-9255-9e274f1fa38f.PNG)

**Comment by wkurniawan07** [comment] 2020-07-12 14:03
I don't think it's caused by `collapseAnim` (I might be wrong). It is true that there are many instances of this behaviour in dropdowns, but in most cases, it can be resolved by setting `container="body"`. Haven't tried datepicker but it should be the same.

**Comment by jtankw3** [comment] 2020-07-12 15:36
Hi, I tried using the container="body" at first but I realized it is affecting all the containers with `collapseAnim`. Thus I think it is better to change `collapseAnim` as we may miss out adding container="body" to certain elements such as tooltips which are harder to notice.

**Closed** 2020-07-13 06:07 UTC
Labels: a-UIX, c.Bug, d.Contributors
