### ISSUE TITLE
Cannot download results of session due to 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#12544] opened 2023-08-04 10:44 UTC
V8.28.1
A user reported that downloading results fails silently.

Upon checking, I found that the download action causes this error to appear in the Browser console.

![image](https://github.com/TEAMMATES/teammates/assets/1673303/a9c23f05-531f-44f9-b632-f3969b0deea8)

Seems to be related to a particular question. Trying to view the results of that question results in the above error as well. In addition, the results show up without some stats tables, as shown below:
![image](https://github.com/TEAMMATES/teammates/assets/1673303/cc214b4b-56b5-4e92-b2b6-c6766f9950d9)

The missing tables appear if I tick this checkbox.
![image](https://github.com/TEAMMATES/teammates/assets/1673303/96ac672c-464d-46d5-9afe-3dbbcf606c18)

The question itself is a follows:
![image](https://github.com/TEAMMATES/teammates/assets/1673303/a6d3a4a1-b835-469d-97a4-09cf9e1c54a3)

The user has 6 courses with similar sessions. One can be downloaded without a problem but all other 5 has this problem.

Let me know if you need more information.

**Comment by samuelfangjw** [comment] 2023-08-04 11:11
Root cause is weight given to NEITE option is null/undefined instead of a number. Likely causing issues when calculating per recipient stats.

**Comment by samuelfangjw** [comment] 2023-08-04 11:21
https://github.com/TEAMMATES/teammates/blob/5bc54fc63c6f8f37e8f26d46d5217555ab65f7d8/src/web/app/components/question-types/question-statistics/question-statistics-calculation/rubric-question-statistics-calculation.ts#L126

More specifically, `subAnswer` here is `undefined`. The question doesn't seem to have been designed with the null use case in mind, but certainly can be added if we need a quick fix to this problem.

One solution could be to ignore options that are null/undefined when calculating statistics, though care should be taken to ensure that the number of responses and the statistics calculation is not affected.

**Comment by damithc** [comment] 2023-08-04 13:20
Thanks for investigating this, @samuelfangjw 

> Root cause is weight given to NEITE option is null/undefined instead of a number. Likely causing issues when calculating per recipient stats.

The funny thing is, a similar session in the one (out of five) course doesn't have this problem. Given below is the corresponding question from the session that doesn't have this problem.

![image](https://github.com/TEAMMATES/teammates/assets/1673303/ab1bd6c4-a009-4990-b494-aa51199ab257)

Perhaps only certain responses to this question triggers this problem? In that case it is possible that one of six sessions doesn't have that 'trigger' data.

**Comment by damithc** [comment] 2023-08-04 13:25
> I believe it would be possible if the question has no responses that have selected the null option.

Yup, this seems to be the case. Respondents have chosen the NEITE option in the problematic sessions but no one has chosen it in the session that works.

**Comment by damithc** [comment] 2023-08-04 13:28
Would adding a weight to that column fix the problem? Also, would it wipe out the existing responses?

**Comment by samuelfangjw** [comment] 2023-08-04 13:38
> Would adding a weight to that column fix the problem? Also, would it wipe out the existing responses? 

Not sure if it will wipe existing responses, we will have to look into it. 

Adding a weight will fix it, but my concern is that there doesn't seem to be an appropriate weight to assign to the option.

**Comment by damithc** [comment] 2023-08-05 03:31
We need to get someone working on this quickly, as the user is stuck with un-downloadable results.

**Comment by jasonqiu212** [comment] 2023-08-05 05:17
I can work on this issue.

I will follow @samuelfangjw's proposed solution:
> One solution could be to ignore options that are null/undefined when calculating statistics, though care should be taken to ensure that the number of responses and the statistics calculation is not affected.

**Comment by damithc** [comment] 2023-08-05 05:43
> I can work on this issue.
> 
> I will follow @samuelfangjw's proposed solution:
> 
> > One solution could be to ignore options that are null/undefined when calculating statistics, though care should be taken to ensure that the number of responses and the statistics calculation is not affected.

Great. Thanks @jasonqiu212

**Comment by jasonqiu212** [comment] 2023-08-05 08:57
Update:
- [x] Assign null weights to special constant of `NO_VALUE`
- [ ] Skip over null weights when calculating average weight stats
- [ ] Testing

Will finish PR by tonight!

**Closed** 2023-08-19 07:56 UTC
Labels: p.Urgent, s.ToInvestigate
