### ISSUE TITLE
Instructor: unpublish responses: Add quotation marks around session name

### ISSUE THREAD

**Issue by amarlearning** [TEAMMATES/teammates#7345] opened 2017-05-20 14:04 UTC
Quotation marks should be added around the session name for the prompt to unpublish responses. In the screenshot below, the message should state `Are you sure you want to unpublish the session "Second team feedback session"?`

[screenshot added]
![screenshot from 2017-05-20 18-57-19](https://cloud.githubusercontent.com/assets/9383897/26276284/0ac613d6-3d92-11e7-9cae-418e4484c952.png)

**Comment by chowyb** [comment] 2017-05-20 14:55
I'm not sure what you mean by the `unpublishing session` being set to lower case, but in the case of the message it looks okay.

In normal circumstances it displays `Are you sure you want to unpublish the session <session name>?`, where the session name may not explicitly state it is a feedback session, since it is defined by the user. As such, leaving "session" inside is acceptable.

**Comment by amarlearning** [comment] 2017-05-20 15:14
> I'm not sure what you mean by the unpublishing session being set to lower case, but in the case of the message, it looks okay.

I mean the `<session name>` should be lower-case. A word with upper case first letter doesn't look good in the middle of the sentence.

**Comment by chowyb** [comment] 2017-05-20 15:39
> A word with upper case first letter doesn't look good in the middle of the sentence.

Maybe we could change it to be in quotation marks instead (ie. `"<session name>"`)? This way, it won't look too bad, while still keeping the session name the same (which avoids the possibility of confusing the user by suddenly providing a name that looks different.

**Comment by amarlearning** [comment] 2017-05-20 15:42
@chowyb Yeah, that sounds good.

**Comment by chowyb** [comment] 2017-05-20 16:17
Edited title and description of issue to use the suggestions discussed. Also, I noticed that publishing responses already uses the quotation marks for session names, so this should help to make things consistent.

**Comment by malenchite** [comment] 2017-06-13 14:46
This issue appears to be resolved. I went to work on it, but the files from the master already uses quotation marks for the unpublish prompt.

**Comment by chowyb** [comment] 2017-06-14 01:26
Confirmed; this was fixed in #7466, closing this issue.

**Closed by chowyb** 2017-06-14 01:26 UTC
Labels: d.FirstTimers, f-Sessions, p.Low
