### ISSUE TITLE
Student: edit submission: show evaluees in alphabetical order

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/teammates#8607] opened 2018-03-07 05:07 UTC
Scenario:
Student submits responses to a question where she has to select evaluees. Then, students loads the submission page again to edit/view responses.

Current:
Evaluees are not shown in any order.
![image](https://user-images.githubusercontent.com/1673303/37074404-a6832250-2207-11e8-90ea-57d3ed49c221.png)

Suggested:
Show evaluees in alphabetical order.

**Comment by bqnguyen94** [comment] 2018-03-07 13:46
I can't reproduce this locally. The recipients are ordered alphabetically at every page load. Am I missing anything??
![1](https://user-images.githubusercontent.com/11720085/37095428-dd444e9c-2250-11e8-8630-93bd43742cf4.gif)

**Comment by damithc** [comment] 2018-03-07 14:18
I observed this when I was moderating a students' responses. May be the behavior is limited to that feature?

**Comment by tran-tien-dat** [comment] 2018-03-07 14:31
I believe that it's ordered in alphabetical order of the student's emails, not their names.

**Comment by damithc** [comment] 2018-03-07 14:45
> I believe that it's ordered in alphabetical order of the student's emails, not their names.

Oh? in that case it can give the illusion of alphabetical ordering when in the sample course :-p

**Comment by mbi90** [comment] 2018-03-25 10:28
I'd like to work on this

**Comment by brennanw31** [comment] 2021-06-09 19:06
I'd like to work on this

**Comment by henrique2Zs** [comment] 2021-06-27 12:44
Hi guys. Can I work on this? I'm thinking to try the same code of @moazbaghdadi how the referred comments above. I understood that were a problem with the tests when that code was proved. However, the tests are already fixed in another issue.

**Comment by A-GHOSH-dev** [comment] 2021-08-21 07:36
I would like to work on this.

**Comment by t-cheepeng** [comment] 2021-08-22 02:13
@A-GHOSH-dev Hi, I see that you have multiple issues that you have taken up. Please complete the other issues first before coming back and requesting to work on this. Thanks

**Comment by NicolasCwy** [comment] 2021-11-25 09:27
Hi would it be ok, if I give this a try!

**Comment by UsamaMahboob** [comment] 2021-11-26 17:30
Hi, could I tackle this issue?

**Comment by t-cheepeng** [comment] 2021-11-27 07:17
@NicolasCwy Hi, please go ahead

@UsamaMahboob Hi, as the previous commenter came first, we will let him try the issue. Please look for another issue to tackle. Thanks

**Comment by NicolasCwy** [comment] 2021-11-27 09:51
Can I check if this is a Numerical-scale question, I am trying to replicate the issue but am unable to find the question type that supports a selection box for students. Most of the question types that use students feedback have a fixed student order

![image](https://user-images.githubusercontent.com/25302138/143676364-4aa6b61e-8e18-4e0a-a951-3a943e74e253.png)
Numerical-Scale option

![image](https://user-images.githubusercontent.com/25302138/143676404-885dc8c3-23f4-4324-9b10-104b4744c70c.png)
Multiple answer

**Comment by damithc** [comment] 2021-11-27 15:02
> Can I check if this is a Rank-recipients question, I am trying to replicate the issue but am unable to find the question type that supports a selection box for students to choose a particular students names. Most of the question types that use students as options have a fixed student order, wondering if the UI has changed as it is quite an old issue

@NicolasCwy the dropdown boxes appear when you have a question setting such as the below (i.e., limit the number of recipients)

![image](https://user-images.githubusercontent.com/1673303/143686585-5588514c-d26d-46f9-ab13-0ec300f5f8ed.png)

**Comment by NicolasCwy** [comment] 2021-11-28 04:56
@damithc Not sure if I'm doing something wrong but I am unable to save the max number of students to be 5. Everytime I try to preview the form as a student it shows one box. Saving and reloading the feedback session changes the value back to 1 maximum number of student each respondent should give feedback to?

![Change recepient limit](https://user-images.githubusercontent.com/25302138/143730145-35dfcb82-5fef-46ee-95f6-86347a318925.gif)

**Comment by damithc** [comment] 2021-11-28 05:42
> Seems to be related to #11474

Good catch @NicolasCwy . Yes, I think so too. I think this will have to wait till that bug is fixed.

**Closed** 2022-01-16 01:07 UTC
Labels: a-UIX, p.Low, good first issue, help wanted
